const {SlashCommandBuilder}=require('discord.js');const CS=require('../../services/clanSystem');const H=require('../../modules/clanHub');const {guildLang}=require('../../services/i18n');
const data=new SlashCommandBuilder().setName('clan-manage').setDescription('Manage your community Clan').setDescriptionLocalizations({vi:'Quản lý Clan cộng đồng'})
.addSubcommand(s=>s.setName('contribute').setDescription('Contribute CXu to Clan Points').addIntegerOption(o=>o.setName('amount').setDescription('CXu amount (1 CXu = 1 Clan Point)').setRequired(true).setMinValue(1)))
.addSubcommand(s=>s.setName('review').setDescription('Approve or decline a join application').addStringOption(o=>o.setName('application_id').setDescription('Application ID').setRequired(true)).addStringOption(o=>o.setName('decision').setDescription('Decision').setRequired(true).addChoices({name:'Approve',value:'APPROVED'},{name:'Decline',value:'DECLINED'})))
.addSubcommand(s=>s.setName('role').setDescription('Change a Clan member role (Owner only)').addUserOption(o=>o.setName('user').setDescription('Clan member').setRequired(true)).addStringOption(o=>o.setName('role').setDescription('Role').setRequired(true).addChoices({name:'Phó Hội',value:'DEPUTY'},{name:'Quân Sư',value:'STRATEGIST'},{name:'Tinh Anh',value:'ELITE'},{name:'Thành Viên',value:'MEMBER'})))
.addSubcommand(s=>s.setName('kick').setDescription('Remove a member from the Clan').addUserOption(o=>o.setName('user').setDescription('Clan member').setRequired(true)).addStringOption(o=>o.setName('reason').setDescription('Reason').setMaxLength(300)))
.addSubcommand(s=>s.setName('leave').setDescription('Leave your current Clan'))
.addSubcommand(s=>s.setName('transfer-owner').setDescription('Transfer Clan ownership').addUserOption(o=>o.setName('user').setDescription('New Clan Owner').setRequired(true)))
.addSubcommand(s=>s.setName('disband').setDescription('Permanently disband your Clan (Owner only)').addStringOption(o=>o.setName('confirm_name').setDescription('Enter the exact Clan name').setRequired(true)));
module.exports={data,prefix:['clanmanage'],async execute(i){try{const sub=i.options.getSubcommand();if(sub==='contribute'){const r=await CS.contributeCXU(i.user.id,i.options.getInteger('amount'));return i.reply({content:`✅ ${r.amount.toLocaleString()} CXu → ${r.amount.toLocaleString()} Clan Points${r.rankUp?`\n🎉 **${r.fromRank.name} → ${r.toRank.name}**`:''}`,flags:64});}const x=await CS.byUser(i.user.id);if(!x)throw new Error('NOT_IN_CLAN');if(sub==='review'){await CS.reviewApplication(x.clan,i.options.getString('application_id'),i.user.id,i.options.getString('decision'));return i.reply({content:'✅ Application updated.',flags:64});}if(sub==='role'){await CS.setRank(x.clan,i.options.getUser('user').id,i.options.getString('role'),i.user.id);return i.reply({content:'✅ Member role updated.',flags:64});}if(sub==='kick'){await CS.removeMember(x.clan,i.options.getUser('user').id,i.user.id,i.options.getString('reason')||'');return i.reply({content:'✅ Member removed.',flags:64});}if(sub==='leave'){await CS.leave(i.user.id);return i.reply({content:'✅ You left the Clan.',flags:64});}if(sub==='transfer-owner'){await CS.transferOwner(i.user.id,i.options.getUser('user').id);return i.reply({content:`👑 Ownership transferred to <@${i.options.getUser('user').id}>.`,flags:64});}if(sub==='disband'){const c=await CS.disband(i.user.id,i.options.getString('confirm_name'));return i.reply({content:`🗑️ Clan **${c.name}** permanently disbanded.`,flags:64});}}catch(e){return i.reply({content:`❌ ${e.message}`,flags:64});}},async executePrefix(m){return m.reply('🏰 Open `?clan` for the Clan Hub. Secure management actions are available through `/clan-manage`.');}};
