const Bank=require('../models/BankAccount');
const Dev=require('../models/DeveloperSettings');
const {ensureWallet}=require('./economyWallet');
async function config(){const d=await Dev.findOneAndUpdate({key:'global'},{$setOnInsert:{key:'global'}},{upsert:true,returnDocument:'after',setDefaultsOnInsert:true});return d.bank;}
async function account(userId){return Bank.findOneAndUpdate({userId:String(userId)},{$setOnInsert:{userId:String(userId),lastInterestAt:new Date()}},{upsert:true,returnDocument:'after',setDefaultsOnInsert:true});}
async function settle(userId){const [a,c]=await Promise.all([account(userId),config()]);if(!c.enabled||a.balance<=0)return a;const hours=Math.floor((Date.now()-new Date(a.lastInterestAt).getTime())/3600000);const periods=Math.floor(hours/Math.max(1,c.compoundHours));if(periods<=0)return a;const periodRate=(Number(c.annualRatePercent)||0)/100*(Number(c.compoundHours)||24)/(365*24);const before=a.balance;const after=Math.min(Number(c.maxBalance)||1e9,before*Math.pow(1+periodRate,periods));const interest=Math.max(0,Math.floor(after-before));a.balance+=interest;a.accruedInterest+=interest;a.lifetimeInterest+=interest;a.lastInterestAt=new Date(new Date(a.lastInterestAt).getTime()+periods*c.compoundHours*3600000);await a.save();return a;}
async function deposit(userId,amount){amount=Math.floor(Number(amount));const c=await config();if(!c.enabled)throw new Error('DISABLED');if(!Number.isFinite(amount)||amount<c.minDeposit)throw new Error('MIN_DEPOSIT');const [a,w]=await Promise.all([settle(userId),ensureWallet(userId)]);if(w.cstar<amount)throw new Error('INSUFFICIENT');if(a.balance+amount>c.maxBalance)throw new Error('MAX_BALANCE');w.cstar-=amount;a.balance+=amount;await w.save();try{await a.save();}catch(e){w.cstar+=amount;await w.save();throw e;}return {account:a,wallet:w,config:c};}
async function withdraw(userId,amount){amount=Math.floor(Number(amount));if(!Number.isFinite(amount)||amount<=0)throw new Error('INVALID_AMOUNT');const [a,w]=await Promise.all([settle(userId),ensureWallet(userId)]);if(a.balance<amount)throw new Error('INSUFFICIENT_BANK');a.balance-=amount;w.cstar+=amount;await a.save();try{await w.save();}catch(e){a.balance+=amount;await a.save();throw e;}return {account:a,wallet:w};}
async function setConfig(values){const d=await Dev.findOneAndUpdate({key:'global'},{$setOnInsert:{key:'global'}},{upsert:true,returnDocument:'after',setDefaultsOnInsert:true});for(const [k,v] of Object.entries(values))if(v!==undefined)d.bank[k]=v;await d.save();return d.bank;}
module.exports={config,account,settle,deposit,withdraw,setConfig};
