const Clan=require('../models/Clan'),Member=require('../models/ClanMember'),Application=require('../models/ClanApplication'),Audit=require('../models/ClanAudit'),Shop=require('../models/ClanShopItem'),Order=require('../models/ClanOrder');
const {ensureWallet}=require('./economyWallet');
const PERMS=['members','applications','shop','treasury','missions','events','announcements','ranks','settings'];const RANKS=['LEADER','DEPUTY','STRATEGIST','ELITE','MEMBER'];
async function create({ownerGuildId,ownerId,name,tag=''}){if(await Member.findOne({userId:ownerId}))throw new Error('ALREADY_IN_CLAN');const clan=await Clan.create({ownerGuildId,ownerId,name:String(name).trim(),tag:String(tag).trim().toUpperCase(),currency:{name:'CXu',symbol:'CXu'}});await Member.create({clanId:clan._id,userId:ownerId,rank:'LEADER',trust:100});await audit(clan._id,ownerId,'CLAN_CREATED','',{name:clan.name});return clan;}
async function byUser(userId){const member=await Member.findOne({userId:String(userId)}).lean();if(!member)return null;const clan=await Clan.findById(member.clanId).lean();return clan?{clan,member}:null;}
function rankDef(clan,key){return (clan.ranks||[]).find(x=>x.key===key)}async function can(userId,clan,permission){if(String(clan.ownerId)===String(userId))return true;const m=await Member.findOne({clanId:clan._id,userId:String(userId)}).lean();if(!m)return false;const r=rankDef(clan,m.rank);return Boolean(r&&((r.permissions||[]).includes('*')||(r.permissions||[]).includes(permission)));}
async function audit(clanId,actorId,action,reason='',meta={},targetId=''){return Audit.create({clanId,actorId:String(actorId||''),action,reason:String(reason||'').slice(0,500),meta,targetId:String(targetId||'')});}
async function adjustMember(clanId,userId,{currency=0,contribution=0,trust=0},actorId,reason=''){const m=await Member.findOne({clanId,userId:String(userId)});if(!m)throw new Error('CLAN_MEMBER_NOT_FOUND');m.contribution=Math.max(0,m.contribution+Math.trunc(contribution));m.trust=Math.max(0,Math.min(100,m.trust+Math.trunc(trust)));await m.save();await audit(clanId,actorId,'MEMBER_CHANGED',reason,{contribution,trust},userId);return m;}
async function apply(clanId,userId,message=''){if(await Member.findOne({userId:String(userId)}))throw new Error('ALREADY_IN_CLAN');const clan=await Clan.findById(clanId);if(!clan)throw new Error('CLAN_NOT_FOUND');if(await Application.findOne({clanId,userId:String(userId),status:'PENDING'}))throw new Error('APPLICATION_EXISTS');const row=await Application.create({clanId,userId:String(userId),message:String(message).slice(0,500)});await audit(clanId,userId,'APPLICATION_CREATED');return row;}
async function reviewApplication(clan,appId,actorId,decision){if(!(await can(actorId,clan,'applications')))throw new Error('FORBIDDEN');const app=await Application.findOne({_id:appId,clanId:clan._id,status:'PENDING'});if(!app)throw new Error('APPLICATION_NOT_FOUND');if(decision==='APPROVED'){if(await Member.findOne({userId:app.userId}))throw new Error('ALREADY_IN_CLAN');const count=await Member.countDocuments({clanId:clan._id});if(count>=clan.memberCap)throw new Error('CLAN_FULL');await Member.create({clanId:clan._id,userId:app.userId});}app.status=decision;app.reviewedBy=String(actorId);app.reviewedAt=new Date();await app.save();await audit(clan._id,actorId,`APPLICATION_${decision}`,'',{},app.userId);return app;}
async function setRank(clan,targetId,rank,actorId){if(!(await can(actorId,clan,'ranks'))&&String(clan.ownerId)!==String(actorId))throw new Error('FORBIDDEN');if(!RANKS.includes(rank)||rank==='LEADER')throw new Error('INVALID_RANK');const target=await Member.findOne({clanId:clan._id,userId:String(targetId)});if(!target)throw new Error('CLAN_MEMBER_NOT_FOUND');if(target.rank==='LEADER')throw new Error('CANNOT_CHANGE_LEADER');target.rank=rank;await target.save();await audit(clan._id,actorId,'MEMBER_RANK_CHANGED','',{rank},targetId);return target;}
async function removeMember(clan,targetId,actorId,reason=''){if(!(await can(actorId,clan,'members')))throw new Error('FORBIDDEN');if(String(clan.ownerId)===String(targetId))throw new Error('CANNOT_REMOVE_LEADER');const row=await Member.findOneAndDelete({clanId:clan._id,userId:String(targetId)});if(!row)throw new Error('CLAN_MEMBER_NOT_FOUND');await audit(clan._id,actorId,'MEMBER_REMOVED',reason,{},targetId);return row;}
async function depositCXU(userId,amount){amount=Math.trunc(Number(amount));if(!Number.isFinite(amount)||amount<=0)throw new Error('INVALID_AMOUNT');const x=await byUser(userId);if(!x)throw new Error('NOT_IN_CLAN');const w=await ensureWallet(userId);if(w.cstar<amount)throw new Error('INSUFFICIENT_CXU');w.cstar-=amount;await w.save();try{const clan=await Clan.findByIdAndUpdate(x.clan._id,{$inc:{treasury:amount}},{returnDocument:'after'});await audit(clan._id,userId,'TREASURY_DEPOSIT_CXU','',{amount});return{clan,wallet:w,amount};}catch(e){w.cstar+=amount;await w.save().catch(()=>{});throw e;}}
async function withdrawCXU(userId,amount){amount=Math.trunc(Number(amount));if(!Number.isFinite(amount)||amount<=0)throw new Error('INVALID_AMOUNT');const x=await byUser(userId);if(!x)throw new Error('NOT_IN_CLAN');if(!(await can(userId,x.clan,'treasury')))throw new Error('FORBIDDEN');const clan=await Clan.findOneAndUpdate({_id:x.clan._id,treasury:{$gte:amount}},{$inc:{treasury:-amount}},{returnDocument:'after'});if(!clan)throw new Error('INSUFFICIENT_TREASURY');try{const w=await ensureWallet(userId);w.cstar+=amount;await w.save();await audit(clan._id,userId,'TREASURY_WITHDRAW_CXU','',{amount});return{clan,wallet:w,amount};}catch(e){await Clan.updateOne({_id:x.clan._id},{$inc:{treasury:amount}}).catch(()=>{});throw e;}}
async function buy(clan,itemId,userId){const item=await Shop.findOne({_id:itemId,clanId:clan._id,enabled:true});if(!item)throw new Error('ITEM_NOT_FOUND');if(item.stock===0)throw new Error('OUT_OF_STOCK');if(!(await Member.exists({clanId:clan._id,userId:String(userId)})))throw new Error('CLAN_MEMBER_NOT_FOUND');const w=await ensureWallet(userId);if(w.cstar<item.price)throw new Error('INSUFFICIENT_CXU');w.cstar-=item.price;await w.save();try{if(item.stock>0){item.stock--;await item.save();}const order=await Order.create({clanId:clan._id,itemId:item._id,userId:String(userId),itemName:item.name,type:item.type,price:item.price,status:item.type==='VIRTUAL'?'FULFILLED':'PENDING'});await audit(clan._id,userId,'SHOP_PURCHASE_CXU','',{itemId:String(item._id),price:item.price,type:item.type});return order;}catch(e){w.cstar+=item.price;await w.save().catch(()=>{});throw e;}}
module.exports={PERMS,RANKS,create,byUser,can,audit,adjustMember,apply,reviewApplication,setRank,removeMember,depositCXU,withdrawCXU,buy};
