const Clan=require('../models/Clan'),Member=require('../models/ClanMember'),Application=require('../models/ClanApplication'),Audit=require('../models/ClanAudit');
const {ensureWallet}=require('./economyWallet');
const {rankForPoints}=require('../config/clanRanks');
const PERMS=['members','applications','settings'];const RANKS=['LEADER','DEPUTY','STRATEGIST','ELITE','MEMBER'];
async function create({ownerGuildId,ownerId,name,tag='',description=''}){if(await Member.findOne({userId:String(ownerId)}))throw new Error('ALREADY_IN_CLAN');const clean=String(name||'').trim();if(clean.length<2)throw new Error('NAME_TOO_SHORT');const clan=await Clan.create({ownerGuildId,ownerId:String(ownerId),name:clean,tag:String(tag||'').trim().toUpperCase(),description:String(description||'').trim(),privacy:'APPLICATION',clanRank:'D',clanPoints:0,currency:{name:'CXu',symbol:'CXu'}});await Member.create({clanId:clan._id,userId:String(ownerId),rank:'LEADER',trust:100});await audit(clan._id,ownerId,'CLAN_CREATED','',{name:clan.name});return clan;}
async function byUser(userId){const member=await Member.findOne({userId:String(userId)}).lean();if(!member)return null;const clan=await Clan.findById(member.clanId).lean();return clan?{clan,member}:null;}
function rankDef(clan,key){return (clan.ranks||[]).find(x=>x.key===key)}
async function can(userId,clan,permission){if(String(clan.ownerId)===String(userId))return true;const m=await Member.findOne({clanId:clan._id,userId:String(userId)}).lean();if(!m)return false;const r=rankDef(clan,m.rank);return Boolean(r&&((r.permissions||[]).includes('*')||(r.permissions||[]).includes(permission)));}
async function audit(clanId,actorId,action,reason='',meta={},targetId=''){return Audit.create({clanId,actorId:String(actorId||''),action,reason:String(reason||'').slice(0,500),meta,targetId:String(targetId||'')});}
async function apply(clanId,userId,message=''){if(await Member.findOne({userId:String(userId)}))throw new Error('ALREADY_IN_CLAN');const clan=await Clan.findById(clanId);if(!clan)throw new Error('CLAN_NOT_FOUND');if(await Application.findOne({clanId,userId:String(userId),status:'PENDING'}))throw new Error('APPLICATION_EXISTS');const row=await Application.create({clanId,userId:String(userId),message:String(message||'').slice(0,500)});await audit(clanId,userId,'APPLICATION_CREATED');return row;}
async function reviewApplication(clan,appId,actorId,decision){if(!(await can(actorId,clan,'applications')))throw new Error('FORBIDDEN');const app=await Application.findOne({_id:appId,clanId:clan._id,status:'PENDING'});if(!app)throw new Error('APPLICATION_NOT_FOUND');if(decision==='APPROVED'){if(await Member.findOne({userId:app.userId}))throw new Error('ALREADY_IN_CLAN');const count=await Member.countDocuments({clanId:clan._id});if(count>=clan.memberCap)throw new Error('CLAN_FULL');await Member.create({clanId:clan._id,userId:app.userId});await Application.updateMany({userId:app.userId,status:'PENDING',_id:{$ne:app._id}},{$set:{status:'CANCELLED'}});}app.status=decision;app.reviewedBy=String(actorId);app.reviewedAt=new Date();await app.save();await audit(clan._id,actorId,`APPLICATION_${decision}`,'',{},app.userId);return app;}
async function setRank(clan,targetId,rank,actorId){if(String(clan.ownerId)!==String(actorId))throw new Error('OWNER_ONLY');if(!RANKS.includes(rank)||rank==='LEADER')throw new Error('INVALID_RANK');const target=await Member.findOne({clanId:clan._id,userId:String(targetId)});if(!target)throw new Error('CLAN_MEMBER_NOT_FOUND');if(target.rank==='LEADER')throw new Error('CANNOT_CHANGE_LEADER');target.rank=rank;await target.save();await audit(clan._id,actorId,'MEMBER_ROLE_CHANGED','',{rank},targetId);return target;}
async function removeMember(clan,targetId,actorId,reason=''){if(!(await can(actorId,clan,'members')))throw new Error('FORBIDDEN');if(String(clan.ownerId)===String(targetId))throw new Error('CANNOT_REMOVE_LEADER');const actor=await Member.findOne({clanId:clan._id,userId:String(actorId)}).lean();const target=await Member.findOne({clanId:clan._id,userId:String(targetId)});if(!target)throw new Error('CLAN_MEMBER_NOT_FOUND');const order={LEADER:100,DEPUTY:80,STRATEGIST:60,ELITE:40,MEMBER:10};if(String(clan.ownerId)!==String(actorId)&&(order[actor?.rank]||0)<=(order[target.rank]||0))throw new Error('ROLE_TOO_LOW');await target.deleteOne();await audit(clan._id,actorId,'MEMBER_REMOVED',reason,{},targetId);return target;}
async function contributeCXU(userId,amount){amount=Math.trunc(Number(amount));if(!Number.isFinite(amount)||amount<=0)throw new Error('INVALID_AMOUNT');const x=await byUser(userId);if(!x)throw new Error('NOT_IN_CLAN');const wallet=await ensureWallet(userId);if(wallet.cstar<amount)throw new Error('INSUFFICIENT_CXU');wallet.cstar-=amount;await wallet.save();try{const member=await Member.findOneAndUpdate({clanId:x.clan._id,userId:String(userId)},{$inc:{contribution:amount}},{returnDocument:'after'});const before=rankForPoints(x.clan.clanPoints||0);const projected=(x.clan.clanPoints||0)+amount;const after=rankForPoints(projected);const clan=await Clan.findByIdAndUpdate(x.clan._id,{$inc:{clanPoints:amount},$set:{clanRank:after.key}},{returnDocument:'after'});await audit(clan._id,userId,'CLAN_CONTRIBUTION_CXU','',{amount,points:amount,fromRank:before.key,toRank:after.key});return{clan,member,wallet,amount,rankUp:before.key!==after.key,fromRank:before,toRank:after};}catch(e){wallet.cstar+=amount;await wallet.save().catch(()=>{});throw e;}}
async function leave(userId){const x=await byUser(userId);if(!x)throw new Error('NOT_IN_CLAN');if(String(x.clan.ownerId)===String(userId))throw new Error('TRANSFER_OR_DISBAND_FIRST');await Member.deleteOne({clanId:x.clan._id,userId:String(userId)});await audit(x.clan._id,userId,'MEMBER_LEFT');return x.clan;}
async function transferOwner(userId,targetId){const x=await byUser(userId);if(!x)throw new Error('NOT_IN_CLAN');if(String(x.clan.ownerId)!==String(userId))throw new Error('OWNER_ONLY');if(String(targetId)===String(userId))throw new Error('INVALID_TARGET');const target=await Member.findOne({clanId:x.clan._id,userId:String(targetId)});if(!target)throw new Error('CLAN_MEMBER_NOT_FOUND');const owner=await Member.findOne({clanId:x.clan._id,userId:String(userId)});owner.rank='DEPUTY';target.rank='LEADER';await Promise.all([owner.save(),target.save(),Clan.updateOne({_id:x.clan._id},{$set:{ownerId:String(targetId)}})]);await audit(x.clan._id,userId,'OWNER_TRANSFERRED','',{},targetId);return Clan.findById(x.clan._id);}
async function disband(userId,confirmName){const x=await byUser(userId);if(!x)throw new Error('NOT_IN_CLAN');if(String(x.clan.ownerId)!==String(userId))throw new Error('OWNER_ONLY');if(String(confirmName||'').trim()!==x.clan.name)throw new Error('CONFIRM_NAME_MISMATCH');const id=x.clan._id;await audit(id,userId,'CLAN_DISBANDED','',{name:x.clan.name});const legacyModels=['ClanMissionProgress','ClanMission','ClanEvent','ClanShopItem','ClanOrder'];for(const modelName of legacyModels){try{const M=require(`../models/${modelName}`);await M.deleteMany({clanId:id});}catch{}}await Promise.all([Member.deleteMany({clanId:id}),Application.deleteMany({clanId:id})]);await Clan.deleteOne({_id:id});return x.clan;}
async function findClan(name){const q=String(name||'').trim();if(!q)throw new Error('NAME_REQUIRED');const escaped=q.replace(/[.*+?^${}()|[\]\\]/g,'\\$&');return Clan.findOne({$or:[{name:new RegExp(`^${escaped}$`,'i')},{tag:q.toUpperCase()}]}).lean();}
module.exports={PERMS,RANKS,create,byUser,can,audit,apply,reviewApplication,setRank,removeMember,contributeCXU,leave,transferOwner,disband,findClan};
