const CreatureProfile=require('../models/CreatureProfile');
const {byId,randomPet,pets}=require('./creatureCatalog');
const ORBS={basic:{label:'Basic Orb',bonus:0},great:{label:'Great Orb',bonus:.12},ultra:{label:'Ultra Orb',bonus:.25},celestial:{label:'Celestial Orb',bonus:.40},secret:{label:'Secret Orb',bonus:.55}};
const BASE={N:.82,R:.66,VR:.50,SR:.34,SSR:.18,UR:0,GR:0};
const CAPS={N:.98,R:.94,VR:.88,SR:.78,SSR:.62,UR:0,GR:0};
const ZONES={meadow:{label:'Verdant Meadow',elements:['NORMAL','NATURE','LIGHT'],unlock:0},volcano:{label:'Ember Volcano',elements:['FIRE','ELECTRIC','DARK'],unlock:5},tundra:{label:'Frozen Tundra',elements:['ICE','WATER','LIGHT'],unlock:10},abyss:{label:'Astral Abyss',elements:['DARK','ELECTRIC','NORMAL'],unlock:15}};
const DEX_MILESTONES=[5,10,15,20,25];
const DEX_REWARDS={5:{essence:100,basic:5},10:{essence:250,great:3},15:{essence:500,ultra:2},20:{essence:900,celestial:1},25:{essence:1600,secret:1}};
async function profile(uid){return CreatureProfile.findOneAndUpdate({userId:String(uid)},{$setOnInsert:{userId:String(uid)}},{upsert:true,returnDocument:'after',setDefaultsOnInsert:true});}
function zonePet(zone){const z=ZONES[zone]||ZONES.meadow,pool=pets.filter(x=>x.huntable===true&&z.elements.includes(x.element));return Math.random()<.88&&pool.length?pool[Math.floor(Math.random()*pool.length)]:randomPet();}
async function hunt(uid,zone){const p=await profile(uid),now=Date.now(),cd=15000;if(zone&&ZONES[zone]){if(p.pets.length<ZONES[zone].unlock)return{locked:true,need:ZONES[zone].unlock,zone};p.hunt.zone=zone;}if(p.hunt.lastAt&&now-p.hunt.lastAt.getTime()<cd)return{cooldown:cd-(now-p.hunt.lastAt.getTime())};const pet=zonePet(p.hunt.zone);p.hunt.lastAt=new Date();p.hunt.total++;p.missions=p.missions||{};const __d=new Date().toISOString().slice(0,10);if(p.missions.dailyDate!==__d){p.missions.dailyDate=__d;p.missions.dailyHunts=0;p.missions.dailyBattles=0;p.missions.dailyClaimed=false;}p.missions.dailyHunts=(p.missions.dailyHunts||0)+1;p.hunt.encounterPetId=pet.id;p.hunt.encounterExpiresAt=new Date(now+120000);await p.save();return{pet,profile:p,zone:p.hunt.zone};}
async function capture(uid,orb){if(!ORBS[orb])throw new Error('INVALID_ORB');const p=await profile(uid);if(!p.hunt.encounterPetId||!p.hunt.encounterExpiresAt||p.hunt.encounterExpiresAt<Date.now())throw new Error('NO_ENCOUNTER');if((p.orbs?.[orb]||0)<1)throw new Error('NO_ORB');const pet=byId(p.hunt.encounterPetId);if(!pet)throw new Error('INVALID_ENCOUNTER');if(pet.eventOnly)throw new Error('EVENT_ONLY_PET');p.orbs[orb]-=1;const base=BASE[pet.rarity],cap=CAPS[pet.rarity];if(!Number.isFinite(base)||!Number.isFinite(cap))throw new Error('INVALID_RARITY');const chance=Math.min(cap,base+ORBS[orb].bonus);const success=Math.random()<chance;p.hunt.encounterPetId=undefined;p.hunt.encounterExpiresAt=undefined;let duplicate=false,essenceGain=0;if(success){const own=p.pets.find(x=>x.petId===pet.id);if(own){own.copies++;duplicate=true;essenceGain=20+Math.max(0,['N','R','VR','SR','SSR','UR','GR'].indexOf(pet.rarity))*10;p.essence+=essenceGain;p.progression.totalEssenceEarned+=essenceGain;}else p.pets.push({petId:pet.id});p.hunt.captures++;p.missions.weeklyCaptures=(p.missions.weeklyCaptures||0)+1;p.hunt.streak++;p.hunt.bestStreak=Math.max(p.hunt.bestStreak||0,p.hunt.streak);}else{p.hunt.fails++;p.hunt.streak=0;}await p.save();return{success,pet,chance,profile:p,orb,duplicate,essenceGain};}
function xpNeeded(level){return 80+level*35;}
function stats(pet,owned){const lv=Math.max(1,owned?.level||1),m=1+(lv-1)*.035,skill=1+((owned?.skillLevel||1)-1)*.018,enh=1+(owned?.enhance||0)*.02;let hp=pet.hp*m*enh,atk=pet.atk*m*skill*enh,def=pet.def*m*enh,spd=pet.spd*(1+(lv-1)*.012)*(1+(owned?.enhance||0)*.005);for(const r of (owned?.refine||[])){if(r.stat==='hpPct')hp*=1+r.value/100;if(r.stat==='atkPct')atk*=1+r.value/100;if(r.stat==='defPct')def*=1+r.value/100;if(r.stat==='speedPct')spd*=1+r.value/100}return{hp:Math.round(hp),atk:Math.round(atk),def:Math.round(def),spd:Math.round(spd)};}
function teamPets(p){return (p.team||[]).map(id=>{const own=p.pets.find(x=>String(x._id)===String(id)),pet=own&&byId(own.petId);return pet?{pet,own,stats:stats(pet,own)}:null;}).filter(Boolean).slice(0,3);}
function ownedByNumber(p,num){return p.pets[Math.max(0,Number(num)-1)];}
async function setTeam(uid,slot,num){const p=await profile(uid),own=ownedByNumber(p,num);if(!own||slot<1||slot>3)throw new Error('INVALID_PET');const id=String(own._id),team=[...(p.team||[])].filter(x=>String(x)!==id);while(team.length<3)team.push(null);team[slot-1]=id;p.team=team.filter(Boolean);await p.save();return{p,own,pet:byId(own.petId)};}
async function setCompanion(uid,num){const p=await profile(uid),own=ownedByNumber(p,num);if(!own)throw new Error('INVALID_PET');p.activePetId=String(own._id);await p.save();return{p,own,pet:byId(own.petId)};}
async function toggleFlag(uid,num,flag){const p=await profile(uid),own=ownedByNumber(p,num);if(!own)throw new Error('INVALID_PET');own[flag]=!own[flag];await p.save();return{p,own,pet:byId(own.petId),value:own[flag]};}
async function levelUp(uid,num){const p=await profile(uid),own=ownedByNumber(p,num);if(!own)throw new Error('INVALID_PET');if(own.level>=100)throw new Error('MAX_LEVEL');const cost=Math.ceil(xpNeeded(own.level)*.75);if(p.essence<cost)throw new Error('NO_ESSENCE');p.essence-=cost;own.level++;own.xp=0;await p.save();return{p,own,pet:byId(own.petId),cost};}
async function skillUp(uid,num){const p=await profile(uid),own=ownedByNumber(p,num);if(!own)throw new Error('INVALID_PET');if(own.skillLevel>=10)throw new Error('MAX_SKILL');const cost=150*own.skillLevel;if(p.essence<cost)throw new Error('NO_ESSENCE');p.essence-=cost;own.skillLevel++;await p.save();return{p,own,pet:byId(own.petId),cost};}
async function claimDex(uid,milestone){const p=await profile(uid),m=Number(milestone);if(!DEX_MILESTONES.includes(m)||p.pets.length<m)throw new Error('MILESTONE_LOCKED');if(p.dex.claimedMilestones.includes(m))throw new Error('ALREADY_CLAIMED');const r=DEX_REWARDS[m];p.essence+=r.essence||0;p.progression.totalEssenceEarned+=r.essence||0;for(const k of ['basic','great','ultra','celestial','secret'])if(r[k])p.orbs[k]+=r[k];p.dex.claimedMilestones.push(m);await p.save();return{p,reward:r,milestone:m};}
const ADV={FIRE:'NATURE',NATURE:'WATER',WATER:'FIRE',LIGHT:'DARK',DARK:'LIGHT',ICE:'ELECTRIC',ELECTRIC:'ICE'};
function duel(a,b){const A=teamPets(a).map(x=>({...x,hp:x.stats.hp})),B=teamPets(b).map(x=>({...x,hp:x.stats.hp}));if(!A.length||!B.length)throw new Error('TEAM_REQUIRED');let ai=0,bi=0,round=0;const log=[];while(ai<A.length&&bi<B.length&&round<80){round++;const x=A[ai],y=B[bi],first=x.stats.spd>=y.stats.spd?[[x,y,'A'],[y,x,'B']]:[[y,x,'B'],[x,y,'A']];for(const [atk,def,side] of first){if(atk.hp<=0||def.hp<=0)continue;const adv=ADV[atk.pet.element]===def.pet.element?1.25:ADV[def.pet.element]===atk.pet.element?0.85:1;const dmg=Math.max(1,Math.round((atk.stats.atk*1.55-def.stats.def*.65)*adv*(.9+Math.random()*.2)));def.hp-=dmg;if(log.length<12)log.push(`${atk.pet.name} → ${def.pet.name}: -${dmg} HP${adv>1?' ✦':''}`);if(def.hp<=0){if(side==='A')bi++;else ai++;break;}}}return{winner:ai<A.length?'A':'B',rounds:round,log};}
async function applyPvpResult(winner,loser){winner.pvp.wins++;winner.pvp.seasonWins++;winner.pvp.streak++;winner.pvp.bestStreak=Math.max(winner.pvp.bestStreak||0,winner.pvp.streak);winner.pvp.rating+=18;winner.essence+=35;winner.progression.totalEssenceEarned+=35;loser.pvp.losses++;loser.pvp.seasonLosses++;loser.pvp.streak=0;loser.pvp.rating=Math.max(0,loser.pvp.rating-12);loser.essence+=10;loser.progression.totalEssenceEarned+=10;winner.pvp.lastBattleAt=new Date();loser.pvp.lastBattleAt=new Date();await Promise.all([winner.save(),loser.save()]);}
module.exports={ORBS,ZONES,DEX_MILESTONES,DEX_REWARDS,profile,hunt,capture,xpNeeded,stats,teamPets,setTeam,setCompanion,toggleFlag,levelUp,skillUp,claimDex,duel,applyPvpResult,ADV};
