const S=require('./creatureService');
const C=require('./creatureCatalog');
const CFG=require('./creatureV5Config');
const Economy=require('./economyWallet');
const RELICS={none:{name:'None',mult:1},fang:{name:'Crimson Fang',mult:1.08},aegis:{name:'Astral Aegis',mult:1.10},moon:{name:'Moon Core',mult:1.13},crown:{name:'Void Crown',mult:1.17}};

const RECOVERY={};function rc(){const c=CFG.current();return{fullMinutes:c.recoveryFullMinutes,koMinutes:c.recoveryKoMinutes,minBattlePct:c.minBattlePct,winHealPct:c.winHealPct}}
function recoveryState(o,maxHp,now=Date.now()){
  maxHp=Math.max(1,Number(maxHp||1)); let hp=o.currentHp==null?maxHp:Math.max(0,Math.min(maxHp,Number(o.currentHp)));
  const start=o.recoveryStartedAt?new Date(o.recoveryStartedAt).getTime():0,end=o.recoveryEndsAt?new Date(o.recoveryEndsAt).getTime():0;
  if(end&&end>start&&hp<maxHp){const pct=Math.max(0,Math.min(1,(now-start)/(end-start)));hp=Math.min(maxHp,Math.round(hp+(maxHp-hp)*pct));}
  const ko=o.koUntil&&new Date(o.koUntil).getTime()>now; const remaining=hp>=maxHp?0:Math.max(0,end-now);
  return{hp,maxHp,ko,remaining,ready:!ko&&hp/maxHp>=rc().minBattlePct};
}
function stampRecovery(o,maxHp,hp,ko=false){const now=Date.now();hp=Math.max(0,Math.min(maxHp,Math.round(hp)));o.currentHp=hp;o.recoveryStartedAt=new Date(now);const missing=1-hp/maxHp;const ms=Math.max(0,Math.round(rc().fullMinutes*60000*missing));o.recoveryEndsAt=new Date(now+ms);o.koUntil=ko?new Date(now+rc().koMinutes*60000):undefined;}
function syncRecovery(p){for(const x of S.teamPets(p)){const st=boostedStats(x.pet,x.own),r=recoveryState(x.own,st.hp);x.own.currentHp=r.hp;if(!r.remaining&&r.hp>=st.hp){x.own.recoveryStartedAt=undefined;x.own.recoveryEndsAt=undefined;x.own.koUntil=undefined;}}return p;}
function recoverySummary(p){syncRecovery(p);return S.teamPets(p).map(x=>{const st=boostedStats(x.pet,x.own),r=recoveryState(x.own,st.hp);return{own:x.own,pet:x.pet,...r}})}
function applyBattleRecovery(p,win,boss=false){for(const x of S.teamPets(p)){const st=boostedStats(x.pet,x.own),r=recoveryState(x.own,st.hp);let damage=st.hp*(boss?(win?.42:.72):(win?.25:.52))*(.85+Math.random()*.3);let hp=Math.max(0,r.hp-Math.round(damage));if(win)hp=Math.min(st.hp,hp+Math.round(st.hp*rc().winHealPct));stampRecovery(x.own,st.hp,hp,hp<=0);}}

const starCost=s=>({essence:CFG.current().starEssenceBase*(s+1)*(s+1),copies:Math.max(1,Math.ceil((s+1)/2))});
function accNeed(l){return 150+Math.floor(l*70+Math.pow(l,1.35)*20)}
async function addCxu(uid,amount){amount=Math.max(0,Math.floor(Number(amount)||0));if(!amount)return 0;const w=await Economy.ensureWallet(uid);w.cstar=Math.max(0,Number(w.cstar||0)+amount);await w.save();return amount;}
async function gainAccountXp(p,xp,uid=p.userId){p.progression.accountXp=(p.progression.accountXp||0)+xp;let ups=0,cxu=0;const cfg=CFG.current();while(p.progression.accountXp>=accNeed(p.progression.accountLevel||1)){p.progression.accountXp-=accNeed(p.progression.accountLevel||1);p.progression.accountLevel=(p.progression.accountLevel||1)+1;ups++;cxu+=cfg.levelUpCxuBase+(p.progression.accountLevel||1)*cfg.levelUpCxuPerLevel;}if(cxu&&uid)await addCxu(uid,cxu);return{ups,cxu}}
async function ascend(uid,num){const cfg=await CFG.get();if(!cfg.enabled)throw Error('V5_DISABLED');const p=await S.profile(uid),o=p.pets[Number(num)-1];if(!o)throw Error('INVALID_PET');if((o.stars||0)>=cfg.maxStars)throw Error('MAX_STARS');const c=starCost(o.stars||0);if(p.essence<c.essence)throw Error('NO_ESSENCE');if((o.copies||1)<c.copies+1)throw Error('NO_COPIES');p.essence-=c.essence;o.copies-=c.copies;o.stars=(o.stars||0)+1;await gainAccountXp(p,40+o.stars*10);await p.save();return{p,o,pet:C.byId(o.petId),cost:c};}
function boostedStats(pet,o){const b=S.stats(pet,o),star=1+(o.stars||0)*.055,relic=RELICS[o.relic||'none']||RELICS.none;return Object.fromEntries(Object.entries(b).map(([k,v])=>[k,Math.round(v*star*relic.mult)]));}
async function equipRelic(uid,num,key){const p=await S.profile(uid),o=p.pets[Number(num)-1];if(!o)throw Error('INVALID_PET');if(!RELICS[key])throw Error('INVALID_RELIC');const unlock={none:1,fang:5,aegis:12,moon:25,crown:40}[key];if((p.progression.accountLevel||1)<unlock)throw Error('RELIC_LOCKED');o.relic=key;await p.save();return{p,o,relic:RELICS[key]};}
function enemy(stage,boss=false){const lv=Math.max(1,stage),m=1+lv*.12+(boss?.8:0);return{hp:Math.round((150+lv*28)*m),atk:Math.round((22+lv*4)*m),def:Math.round((12+lv*2.2)*m),name:boss?`Rift Boss ${Math.ceil(lv/5)}`:`Wild Vanguard ${lv}`};}
function teamPower(p){return S.teamPets(p).reduce((n,x)=>{const z=boostedStats(x.pet,x.own);return n+z.hp+z.atk*4+z.def*3+z.spd*2},0)}
async function adventure(uid,boss=false){const cfg=await CFG.get();if(!cfg.enabled)throw Error('V5_DISABLED');const p=await S.profile(uid);syncRecovery(p);if(!S.teamPets(p).length)throw Error('TEAM_REQUIRED');if(recoverySummary(p).some(x=>!x.ready))throw Error('PET_RECOVERING');const stage=p.progression.adventureStage||1,e=enemy(stage,boss),power=teamPower(p),need=e.hp+e.atk*8+e.def*5;const win=power*(.9+Math.random()*.2)>=need;let essence=0,xp=0,cxu=0,levelReward={ups:0,cxu:0};if(win){essence=boss?cfg.bossEssenceBase+stage*cfg.bossEssenceStage:cfg.adventureEssenceBase+stage*cfg.adventureEssenceStage;xp=boss?cfg.bossXpBase+stage*cfg.bossXpStage:cfg.adventureXpBase+stage*cfg.adventureXpStage;p.essence+=essence;p.progression.totalEssenceEarned+=essence;if(boss){p.progression.bossKills=(p.progression.bossKills||0)+1;p.missions.weeklyBoss=(p.missions.weeklyBoss||0)+1}else p.progression.adventureStage=stage+1;cxu=boss?cfg.bossCxuBase+stage*cfg.bossCxuStage:cfg.adventureCxuBase+stage*cfg.adventureCxuStage;await addCxu(uid,cxu);levelReward=await gainAccountXp(p,xp,uid);}applyBattleRecovery(p,win,boss);p.missions.dailyBattles=(p.missions.dailyBattles||0)+1;await checkAchievements(p);await p.save();return{p,win,enemy:e,power,need,essence,xp,cxu,levelReward,stage,boss};}
function day(){return new Date().toISOString().slice(0,10)} function week(){const d=new Date(),x=new Date(Date.UTC(d.getUTCFullYear(),d.getUTCMonth(),d.getUTCDate()));x.setUTCDate(x.getUTCDate()+4-(x.getUTCDay()||7));return `${x.getUTCFullYear()}-${Math.ceil((((x-new Date(Date.UTC(x.getUTCFullYear(),0,1)))/86400000)+1)/7)}`}
async function syncMissions(p){if(p.missions.dailyDate!==day()){p.missions.dailyDate=day();p.missions.dailyHunts=0;p.missions.dailyBattles=0;p.missions.dailyClaimed=false}if(p.missions.weeklyKey!==week()){p.missions.weeklyKey=week();p.missions.weeklyCaptures=0;p.missions.weeklyBoss=0;p.missions.weeklyClaimed=false}}
async function claimMission(uid,type){const cfg=await CFG.get();if(!cfg.enabled)throw Error('V5_DISABLED');const p=await S.profile(uid);await syncMissions(p);let reward;if(type==='daily'){if(p.missions.dailyClaimed||p.missions.dailyHunts<cfg.dailyHunts||p.missions.dailyBattles<cfg.dailyBattles)throw Error('MISSION_LOCKED');reward={essence:cfg.dailyEssence,great:cfg.dailyGreat,cxu:cfg.dailyCxu};p.missions.dailyClaimed=true}else{if(p.missions.weeklyClaimed||p.missions.weeklyCaptures<cfg.weeklyCaptures||p.missions.weeklyBoss<cfg.weeklyBoss)throw Error('MISSION_LOCKED');reward={essence:cfg.weeklyEssence,ultra:cfg.weeklyUltra,celestial:cfg.weeklyCelestial,cxu:cfg.weeklyCxu};p.missions.weeklyClaimed=true}p.essence+=reward.essence;for(const k of ['great','ultra','celestial'])if(reward[k])p.orbs[k]+=reward[k];await addCxu(uid,reward.cxu);const levelReward=await gainAccountXp(p,type==='daily'?100:400,uid);await p.save();return{p,reward,type,levelReward}}
async function checkAchievements(p){const add=(id,ok)=>{if(ok&&!p.achievements.includes(id))p.achievements.push(id)};add('FIRST_CAPTURE',(p.hunt.captures||0)>=1);add('COLLECTOR_16',p.pets.length>=16);add('COLLECTOR_25',p.pets.length>=25);add('STAR_5',p.pets.some(x=>(x.stars||0)>=5));add('STAR_10',p.pets.some(x=>(x.stars||0)>=10));add('BOSS_10',(p.progression.bossKills||0)>=10);add('ARENA_25',(p.pvp.wins||0)>=25);}
module.exports={addCxu,RECOVERY,rc,recoveryState,syncRecovery,recoverySummary,applyBattleRecovery,RELICS,starCost,accNeed,gainAccountXp,ascend,boostedStats,equipRelic,adventure,syncMissions,claimMission,checkAchievements,teamPower};
