const DeveloperSettings=require('../models/DeveloperSettings');
const DEFAULTS={enabled:true,maxStars:10,starEssenceBase:250,recoveryFullMinutes:20,recoveryKoMinutes:30,minBattlePct:.20,winHealPct:.08,adventureEssenceBase:35,adventureEssenceStage:5,bossEssenceBase:120,bossEssenceStage:18,adventureXpBase:30,adventureXpStage:4,bossXpBase:100,bossXpStage:10,dailyEssence:300,dailyGreat:2,weeklyEssence:1200,weeklyUltra:2,weeklyCelestial:1,dailyHunts:5,dailyBattles:3,weeklyCaptures:15,weeklyBoss:3,adventureCxuBase:20,adventureCxuStage:2,bossCxuBase:80,bossCxuStage:8,dailyCxu:250,weeklyCxu:1000,levelUpCxuBase:100,levelUpCxuPerLevel:25,refineEnabled:true,enhanceEnabled:true,releaseEnabled:true,multiReleaseEnabled:true,eventsEnabled:true,wheelEnabled:true,refineStoneBaseCost:2,multiReleaseMax:50,protectHighRarity:true};
let cache={...DEFAULTS},cacheUntil=0;
function clean(v={}){const o={...DEFAULTS,...v};for(const k of Object.keys(DEFAULTS)){if(typeof DEFAULTS[k]==='number'){o[k]=Number(o[k]);if(!Number.isFinite(o[k]))o[k]=DEFAULTS[k];}}o.enabled=o.enabled!==false;return o;}
async function get(){if(Date.now()<cacheUntil)return cache;const d=await DeveloperSettings.findOne({key:'global'}).lean();cache=clean(d?.creatureV5);cacheUntil=Date.now()+30000;return cache;}
function current(){return cache;}
async function set(patch){const $set={};for(const [k,v] of Object.entries(patch))$set[`creatureV5.${k}`]=v;const d=await DeveloperSettings.findOneAndUpdate({key:'global'},{$set,$setOnInsert:{key:'global'}},{upsert:true,returnDocument:'after',setDefaultsOnInsert:true}).lean();cache=clean(d?.creatureV5);cacheUntil=Date.now()+30000;return cache;}
async function reset(){const d=await DeveloperSettings.findOneAndUpdate({key:'global'},{$set:{creatureV5:DEFAULTS},$setOnInsert:{key:'global'}},{upsert:true,returnDocument:'after',setDefaultsOnInsert:true}).lean();cache=clean(d?.creatureV5);cacheUntil=Date.now()+30000;return cache;}
module.exports={DEFAULTS,get,current,set,reset};
