const S=require('./creatureService'),C=require('./creatureCatalog'),M=require('./creatureV6Catalog'),CFG=require('./creatureV5Config'),{ensureWallet}=require('./economyWallet');
const REFINE_STATS={atkPct:[1,15],defPct:[1,15],hpPct:[1,18],critRate:[.5,12],critDmg:[2,20],speedPct:[.5,10],lifesteal:[.3,8],critResist:[.5,12],damageReduction:[.2,8],healing:[1,15],effectResist:[.5,12],effectAccuracy:[.5,12],energyGain:[.5,10],accuracy:[.5,12]};
function own(p,n){return p.pets[Math.max(0,Number(n)-1)]} function protectedPet(p,o){return !o||o.locked;}
function rollValue(max){const r=Math.random();const pct=r<.60?.35:r<.85?.55:r<.95?.72:r<.99?.87:r<.999?.96:1;return Math.round(max*pct*100)/100} function tier(v,max){const q=v/max;return q>=.97?'SECRET':q>=.90?'MYTHIC':q>=.78?'LEGENDARY':q>=.62?'EPIC':q>=.45?'RARE':'NORMAL'}
function rollLine(exclude=[]){const keys=Object.keys(REFINE_STATS).filter(x=>!exclude.includes(x)),stat=keys[Math.floor(Math.random()*keys.length)],[min,max]=REFINE_STATS[stat];const value=Math.max(min,rollValue(max));return{stat,value,tier:tier(value,max),locked:false}}
async function refine(uid,n,locks=[]){const cfg=await CFG.get();if(!cfg.refineEnabled)throw Error('SYSTEM_DISABLED');const p=await S.profile(uid),o=own(p,n);if(!o)throw Error('INVALID_PET');p.materials=p.materials||{};const locked=(o.refine||[]).filter((x,i)=>x.locked||locks.includes(i));if(locked.length>=4)throw Error('ALL_LOCKED');const cost=(cfg.refineStoneBaseCost||2)+locked.length*3;if((p.materials.refineStone||0)<cost)throw Error('NO_REFINE_STONE');p.materials.refineStone-=cost;const next=[...locked.map(x=>({...x.toObject?.()||x}))];while(next.length<4)next.push(rollLine(next.map(x=>x.stat)));o.refine=next;await p.save();return{p,o,pet:C.byId(o.petId),cost}}
async function enhance(uid,n){const cfg=await CFG.get();if(!cfg.enhanceEnabled)throw Error('SYSTEM_DISABLED');const p=await S.profile(uid),o=own(p,n);if(!o)throw Error('INVALID_PET');if((o.enhance||0)>=15)throw Error('MAX_ENHANCE');p.materials=p.materials||{};const lv=o.enhance||0,costStone=1+Math.floor(lv/3),cxu=1000*(lv+1);if((p.materials.enhanceStone||0)<costStone)throw Error('NO_ENHANCE_STONE');const w=await ensureWallet(uid);if((w.cstar||0)<cxu)throw Error('NO_CXU');const chance=lv<5?1:lv<10?.78:.55;if(Math.random()<chance)o.enhance=lv+1;p.materials.enhanceStone-=costStone;w.cstar-=cxu;await Promise.all([p.save(),w.save()]);return{p,o,pet:C.byId(o.petId),costStone,cxu,chance,success:o.enhance>lv}}
function releaseReward(o,pet){const idx=['N','R','VR','SR','SSR','UR','GR'].indexOf(pet.rarity);return{cxu:50+Math.max(0,idx)*75+o.level*3,petEssence:1+Math.max(0,idx)*2}}
async function release(uid,n){const cfg=await CFG.get();if(!cfg.releaseEnabled)throw Error('SYSTEM_DISABLED');const p=await S.profile(uid),o=own(p,n);if(!o)throw Error('INVALID_PET');const pet=C.byId(o.petId);if(protectedPet(p,o))throw Error('PROTECTED');
const r=releaseReward(o,pet),w=await ensureWallet(uid);
o.favorite=false;
if(String(p.activePetId)===String(o._id))p.activePetId=null;
p.team=(p.team||[]).filter(x=>String(x)!==String(o._id));
p.pets.splice(Number(n)-1,1);p.materials.petEssence=(p.materials.petEssence||0)+r.petEssence;w.cstar=(w.cstar||0)+r.cxu;await Promise.all([p.save(),w.save()]);return{pet,reward:r}}
async function multiRelease(uid,rarity='N',limit=25){const cfg=await CFG.get();if(!cfg.multiReleaseEnabled)throw Error('SYSTEM_DISABLED');limit=Math.min(limit,cfg.multiReleaseMax||50);const p=await S.profile(uid),allowed=['N','R','VR','SR'];if(!allowed.includes(rarity))throw Error('RARITY_PROTECTED');const picks=p.pets.map((o,i)=>({o,i,pet:C.byId(o.petId)})).filter(x=>x.pet?.rarity===rarity&&!protectedPet(p,x.o)&&(x.o.enhance||0)<5&&(x.o.stars||0)<3&&!(x.o.refine||[]).some(r=>['MYTHIC','SECRET'].includes(r.tier))).slice(0,Math.min(50,limit));if(!picks.length)throw Error('NO_RELEASE_TARGETS');let cxu=0,petEssence=0;for(const x of picks){const r=releaseReward(x.o,x.pet);cxu+=r.cxu;petEssence+=r.petEssence}const ids=new Set(picks.map(x=>String(x.o._id)));p.pets=p.pets.filter(o=>!ids.has(String(o._id)));p.materials.petEssence=(p.materials.petEssence||0)+petEssence;const w=await ensureWallet(uid);w.cstar=(w.cstar||0)+cxu;await Promise.all([p.save(),w.save()]);return{count:picks.length,cxu,petEssence,rarity}}
async function daily(uid){const cfg=await CFG.get();if(!cfg.eventsEnabled)throw Error('SYSTEM_DISABLED');const p=await S.profile(uid),d=new Date().toISOString().slice(0,10);if(p.welfare?.lastDaily&&new Date(p.welfare.lastDaily).toISOString().slice(0,10)===d)throw Error('DAILY_CLAIMED');p.welfare.lastDaily=new Date();p.materials.luckyTicket=(p.materials.luckyTicket||0)+1;p.essence+=100;const w=await ensureWallet(uid);w.cstar=(w.cstar||0)+100;await Promise.all([p.save(),w.save()]);return{cxu:100,essence:100,ticket:1}}
const WHEEL=[['CXu 250',40],['Pet Essence ×3',25],['Great Orb ×1',15],['Enhance Stone ×1',10],['Refine Shard ×1',7],['Refine Stone ×1',2.5],['Celestial Orb ×1',.45],['Pet Frame: Celestial',.05]];
async function spin(uid){const cfg=await CFG.get();if(!cfg.eventsEnabled||!cfg.wheelEnabled)throw Error('SYSTEM_DISABLED');const p=await S.profile(uid);if((p.materials.luckyTicket||0)<1)throw Error('NO_TICKET');p.materials.luckyTicket--;let r=Math.random()*100,prize=WHEEL[0][0];for(const [x,w] of WHEEL){r-=w;if(r<=0){prize=x;break}}const wallet=await ensureWallet(uid);if(prize==='CXu 250')wallet.cstar=(wallet.cstar||0)+250;else if(prize==='Pet Essence ×3')p.materials.petEssence=(p.materials.petEssence||0)+3;else if(prize==='Great Orb ×1')p.orbs.great++;else if(prize==='Enhance Stone ×1')p.materials.enhanceStone=(p.materials.enhanceStone||0)+1;else if(prize==='Refine Shard ×1')p.materials.refineShard=(p.materials.refineShard||0)+1;else if(prize==='Refine Stone ×1')p.materials.refineStone=(p.materials.refineStone||0)+1;else if(prize==='Celestial Orb ×1')p.orbs.celestial++;else {p.materials.petEssence=(p.materials.petEssence||0)+10;}await Promise.all([p.save(),wallet.save()]);return{prize}}
module.exports={M,REFINE_STATS,WHEEL,own,protectedPet,refine,enhance,release,multiRelease,daily,spin};