const CreatureProfile=require('../models/CreatureProfile');
const {byId,randomPet}=require('./creatureCatalog');
const ORBS={basic:{label:'Basic Orb',bonus:0},great:{label:'Great Orb',bonus:.12},ultra:{label:'Ultra Orb',bonus:.25},celestial:{label:'Celestial Orb',bonus:.40},secret:{label:'Secret Orb',bonus:.55}};
const BASE={COMMON:.82,UNCOMMON:.68,RARE:.52,EPIC:.36,LEGENDARY:.22,MYTHIC:.11,CELESTIAL:.055,SECRET:.012};
const CAPS={COMMON:.98,UNCOMMON:.96,RARE:.92,EPIC:.85,LEGENDARY:.72,MYTHIC:.55,CELESTIAL:.38,SECRET:.20};
async function profile(uid){return CreatureProfile.findOneAndUpdate({userId:String(uid)},{$setOnInsert:{userId:String(uid)}},{upsert:true,returnDocument:'after',setDefaultsOnInsert:true});}
async function hunt(uid){const p=await profile(uid),now=Date.now(),cd=20000;if(p.hunt.lastAt&&now-p.hunt.lastAt.getTime()<cd)return{cooldown:cd-(now-p.hunt.lastAt.getTime())};const pet=randomPet();p.hunt.lastAt=new Date();p.hunt.total++;p.hunt.encounterPetId=pet.id;p.hunt.encounterExpiresAt=new Date(now+120000);await p.save();return{pet,profile:p};}
async function capture(uid,orb){if(!ORBS[orb])throw new Error('INVALID_ORB');const p=await profile(uid);if(!p.hunt.encounterPetId||!p.hunt.encounterExpiresAt||p.hunt.encounterExpiresAt<Date.now())throw new Error('NO_ENCOUNTER');if((p.orbs?.[orb]||0)<1)throw new Error('NO_ORB');const pet=byId(p.hunt.encounterPetId);p.orbs[orb]-=1;const chance=Math.min(CAPS[pet.rarity],BASE[pet.rarity]+ORBS[orb].bonus);const success=Math.random()<chance;p.hunt.encounterPetId=undefined;p.hunt.encounterExpiresAt=undefined;if(success){const own=p.pets.find(x=>x.petId===pet.id);if(own)own.copies++;else p.pets.push({petId:pet.id});p.hunt.captures++;}else p.hunt.fails++;await p.save();return{success,pet,chance,profile:p,orb};}
function stats(pet,owned){const lv=Math.max(1,owned?.level||1),m=1+(lv-1)*.035;return{hp:Math.round(pet.hp*m),atk:Math.round(pet.atk*m),def:Math.round(pet.def*m),spd:Math.round(pet.spd*(1+(lv-1)*.012))};}
function teamPets(p){return (p.team||[]).map(id=>{const own=p.pets.find(x=>String(x._id)===String(id));const pet=own&&byId(own.petId);return pet?{pet,own,stats:stats(pet,own)}:null;}).filter(Boolean).slice(0,3);}
const ADV={FIRE:'NATURE',NATURE:'WATER',WATER:'FIRE',LIGHT:'DARK',DARK:'LIGHT',ICE:'ELECTRIC',ELECTRIC:'ICE'};
function duel(a,b){const A=teamPets(a).map(x=>({...x,hp:x.stats.hp})),B=teamPets(b).map(x=>({...x,hp:x.stats.hp}));if(!A.length||!B.length)throw new Error('TEAM_REQUIRED');let ai=0,bi=0,round=0;const log=[];while(ai<A.length&&bi<B.length&&round<80){round++;const x=A[ai],y=B[bi];const first=x.stats.spd>=y.stats.spd?[[x,y,'A'],[y,x,'B']]:[[y,x,'B'],[x,y,'A']];for(const [atk,def,side] of first){if(atk.hp<=0||def.hp<=0)continue;const adv=ADV[atk.pet.element]===def.pet.element?1.25:ADV[def.pet.element]===atk.pet.element?0.85:1;const dmg=Math.max(1,Math.round((atk.stats.atk*1.55-def.stats.def*.65)*adv*(.9+Math.random()*.2)));def.hp-=dmg;if(log.length<12)log.push(`${atk.pet.name} → ${def.pet.name}: -${dmg} HP${adv>1?' ⚡':''}`);if(def.hp<=0){if(side==='A')bi++;else ai++;break;}}
 }
 const winner=ai<A.length?'A':'B';return{winner,rounds:round,log};}
module.exports={ORBS,profile,hunt,capture,stats,teamPets,duel};
