const Profile=require('../models/CreatureProfile'),Listing=require('../models/CreatureMarketListing'),Trade=require('../models/CreatureTrade'),War=require('../models/CreatureClanWar'),Member=require('../models/ClanMember'),Clan=require('../models/Clan'),Catalog=require('./creatureCatalog'),{ensureWallet,walletFilter}=require('./economyWallet'),UserEconomy=require('../models/UserEconomy');
const BREED_COST=500,BREED_CD=12*3600e3,MARKET_FEE=.05;
async function profile(uid){return Profile.findOneAndUpdate({userId:String(uid)},{$setOnInsert:{userId:String(uid)}},{upsert:true,returnDocument:'after',setDefaultsOnInsert:true})}
function own(p,n){return p.pets[Number(n)-1]||null}function transferable(p,o){return o&&!o.locked&&!o.favorite&&!p.team.map(String).includes(String(o._id))&&String(p.activePetId||'')!==String(o._id)}
function snap(o){return{petId:o.petId,level:o.level,xp:o.xp,copies:o.copies,nickname:o.nickname,essence:o.essence,stars:o.stars,relic:o.relic,favorite:false,locked:false,skillLevel:o.skillLevel,capturedAt:o.capturedAt,currentHp:o.currentHp}}
async function debit(uid,n){await ensureWallet(uid);const x=await UserEconomy.findOneAndUpdate({...walletFilter(uid),cstar:{$gte:n}},{$inc:{cstar:-n}},{returnDocument:'after'});if(!x)throw new Error('INSUFFICIENT_CXU');return x}
async function credit(uid,n){await ensureWallet(uid);return UserEconomy.findOneAndUpdate(walletFilter(uid),{$inc:{cstar:n}},{returnDocument:'after'})}
async function breed(uid,a,b){const p=await profile(uid),x=own(p,a),y=own(p,b);if(!x||!y||String(x._id)===String(y._id))throw new Error('INVALID_PARENTS');const until=p.social?.breedUntil?new Date(p.social.breedUntil).getTime():0;if(until>Date.now())throw new Error(`BREED_COOLDOWN:${until}`);if((x.level||1)<10||(y.level||1)<10)throw new Error('PARENTS_LEVEL_10');await debit(uid,BREED_COST);const chosen=Math.random()<.5?x:y,child={petId:chosen.petId,level:1,xp:0,copies:1,essence:0,stars:0,relic:'none',favorite:false,locked:false,skillLevel:1,currentHp:null};p.pets.push(child);p.social=p.social||{};p.social.breedUntil=new Date(Date.now()+BREED_CD);p.social.bred=(p.social.bred||0)+1;await p.save();return{pet:Catalog.byId(chosen.petId),cost:BREED_COST,until:p.social.breedUntil}}
async function createTrade(fromId,toId,a,b){if(String(fromId)===String(toId))throw new Error('INVALID_TARGET');const p=await profile(fromId),q=await profile(toId),x=own(p,a),y=own(q,b);if(!transferable(p,x)||!transferable(q,y))throw new Error('PET_NOT_TRANSFERABLE');return Trade.create({fromId:String(fromId),toId:String(toId),fromPetId:String(x._id),toPetId:String(y._id),expiresAt:new Date(Date.now()+10*60e3)})}
async function resolveTrade(id,uid,accept){const t=await Trade.findById(id);if(!t||t.status!=='PENDING'||t.expiresAt<new Date())throw new Error('TRADE_EXPIRED');if(String(t.toId)!==String(uid))throw new Error('NOT_YOURS');if(!accept){t.status='DECLINED';await t.save();return t}const p=await profile(t.fromId),q=await profile(t.toId),x=p.pets.id(t.fromPetId),y=q.pets.id(t.toPetId);if(!transferable(p,x)||!transferable(q,y))throw new Error('PET_NOT_TRANSFERABLE');const xs=snap(x),ys=snap(y);x.deleteOne();y.deleteOne();p.pets.push(ys);q.pets.push(xs);await p.save();await q.save();t.status='ACCEPTED';await t.save();return t}
async function list(uid,n,price){price=Math.floor(Number(price));if(price<100)throw new Error('MIN_PRICE_100');const p=await profile(uid),o=own(p,n);if(!transferable(p,o))throw new Error('PET_NOT_TRANSFERABLE');const s=snap(o);o.deleteOne();await p.save();try{return await Listing.create({sellerId:String(uid),pet:s,price})}catch(e){p.pets.push(s);await p.save();throw e}}
async function browse(){return Listing.find({status:'ACTIVE'}).sort({createdAt:-1}).limit(10).lean()}
async function buy(uid,id){const l=await Listing.findOneAndUpdate({_id:id,status:'ACTIVE',sellerId:{$ne:String(uid)}},{$set:{status:'SOLD',buyerId:String(uid),soldAt:new Date()}},{returnDocument:'after'});if(!l)throw new Error('LISTING_UNAVAILABLE');try{await debit(uid,l.price)}catch(e){l.status='ACTIVE';l.buyerId=undefined;l.soldAt=undefined;await l.save();throw e}const sellerNet=Math.floor(l.price*(1-MARKET_FEE));try{const p=await profile(uid);p.pets.push(l.pet);await p.save();await credit(l.sellerId,sellerNet);return{listing:l,sellerNet,fee:l.price-sellerNet}}catch(e){await credit(uid,l.price).catch(()=>{});l.status='ACTIVE';l.buyerId=undefined;l.soldAt=undefined;await l.save().catch(()=>{});throw e}}
async function cancel(uid,id){const l=await Listing.findOneAndUpdate({_id:id,sellerId:String(uid),status:'ACTIVE'},{$set:{status:'CANCELLED'}},{returnDocument:'after'});if(!l)throw new Error('LISTING_UNAVAILABLE');const p=await profile(uid);p.pets.push(l.pet);await p.save();return l}
async function clanOf(uid){const m=await Member.findOne({userId:String(uid)}).lean();if(!m)return null;return Clan.findById(m.clanId).lean()}
async function clanPower(clanId){const ms=await Member.find({clanId}).sort({contribution:-1}).limit(10).lean();let total=0;for(const m of ms){const p=await Profile.findOne({userId:m.userId}).lean();if(!p)continue;for(const id of (p.team||[])){const o=(p.pets||[]).find(x=>String(x._id)===String(id));if(!o)continue;const c=Catalog.byId(o.petId);if(c)total+=(c.base?.hp||50)+4*(c.base?.atk||10)+3*(c.base?.def||10)+2*(c.base?.spd||10)+(o.level||1)*12+(o.stars||0)*100;}}return total}
async function challengeWar(uid,targetUid){const a=await clanOf(uid),b=await clanOf(targetUid);if(!a||!b||String(a._id)===String(b._id))throw new Error('INVALID_CLANS');return War.create({challengerClanId:a._id,defenderClanId:b._id,challengerId:String(uid),defenderId:String(targetUid),expiresAt:new Date(Date.now()+15*60e3)})}
async function resolveWar(id,uid,accept){const w=await War.findById(id);if(!w||w.status!=='PENDING'||w.expiresAt<new Date())throw new Error('WAR_EXPIRED');if(String(w.defenderId)!==String(uid))throw new Error('NOT_YOURS');if(!accept){w.status='DECLINED';await w.save();return w}const ap=await clanPower(w.challengerClanId),bp=await clanPower(w.defenderClanId),ar=ap*(.9+Math.random()*.2),br=bp*(.9+Math.random()*.2);w.challengerPower=Math.round(ap);w.defenderPower=Math.round(bp);w.winnerClanId=ar>=br?w.challengerClanId:w.defenderClanId;w.status='COMPLETED';await w.save();await Clan.updateOne({_id:w.winnerClanId},{$inc:{clanPoints:250}});return w}
module.exports={BREED_COST,BREED_CD,breed,createTrade,resolveTrade,list,browse,buy,cancel,challengeWar,resolveWar,clanOf};