const L={
'en':{achievements:'View Creature achievements',adventure:'Play Creature PvE adventure',ascend:'Raise a Creature star without changing appearance',battle:'Challenge another player to Pet PvP',bosshunt:'Fight a Creature boss',collection:'View your Creature collection',dex:'View or claim Creature Dex milestones',hunt:'Hunt a wild Creature',missions:'View daily and weekly Creature missions',pet:'Open Creature Hunt profile',petmanage:'Train and manage a captured Pet',relics:'View Creature relic equipment',team:'View or edit your 3-Pet team'},
'vi':{achievements:'Xem thành tựu Creature',adventure:'Chơi phiêu lưu PvE Creature',ascend:'Nâng Sao Creature mà không đổi ngoại hình',battle:'Thách đấu Pet PvP với người chơi khác',bosshunt:'Chiến đấu Boss Creature',collection:'Xem bộ sưu tập Creature',dex:'Xem hoặc nhận mốc Creature Dex',hunt:'Săn Creature hoang dã',missions:'Xem nhiệm vụ Creature ngày và tuần',pet:'Mở hồ sơ Creature Hunt',petmanage:'Huấn luyện và quản lý Pet đã thu phục',relics:'Xem trang bị Di vật Creature',team:'Xem hoặc chỉnh đội 3 Pet'},
'de':{achievements:'Creature-Erfolge anzeigen',adventure:'Creature-PvE-Abenteuer spielen',ascend:'Creature-Stern ohne Aussehensänderung erhöhen',battle:'Spieler zum Pet-PvP herausfordern',bosshunt:'Creature-Boss bekämpfen',collection:'Creature-Sammlung anzeigen',dex:'Creature-Dex-Meilensteine anzeigen oder abholen',hunt:'Wildes Creature jagen',missions:'Tägliche und wöchentliche Creature-Missionen',pet:'Creature-Hunt-Profil öffnen',petmanage:'Gefangenes Pet trainieren und verwalten',relics:'Creature-Relikte anzeigen',team:'3-Pet-Team anzeigen oder bearbeiten'},
'es':{achievements:'Ver logros de Creature',adventure:'Jugar aventura PvE de Creature',ascend:'Subir estrella sin cambiar la apariencia',battle:'Desafiar a otro jugador a Pet PvP',bosshunt:'Luchar contra un jefe Creature',collection:'Ver tu colección de Creature',dex:'Ver o reclamar hitos del Creature Dex',hunt:'Cazar una Creature salvaje',missions:'Ver misiones diarias y semanales',pet:'Abrir perfil de Creature Hunt',petmanage:'Entrenar y gestionar un Pet capturado',relics:'Ver reliquias de Creature',team:'Ver o editar tu equipo de 3 Pets'},
'fr':{achievements:'Voir les succès Creature',adventure:'Jouer une aventure PvE Creature',ascend:"Augmenter l'étoile sans changer l'apparence",battle:'Défier un joueur en Pet PvP',bosshunt:'Combattre un boss Creature',collection:'Voir votre collection Creature',dex:'Voir ou réclamer les paliers Creature Dex',hunt:'Chasser une Creature sauvage',missions:'Voir les missions quotidiennes et hebdomadaires',pet:'Ouvrir le profil Creature Hunt',petmanage:'Entraîner et gérer un Pet capturé',relics:'Voir les reliques Creature',team:'Voir ou modifier votre équipe de 3 Pets'},
'id':{achievements:'Lihat pencapaian Creature',adventure:'Mainkan petualangan PvE Creature',ascend:'Naikkan bintang tanpa mengubah tampilan',battle:'Tantang pemain lain ke Pet PvP',bosshunt:'Lawan bos Creature',collection:'Lihat koleksi Creature',dex:'Lihat atau klaim milestone Creature Dex',hunt:'Berburu Creature liar',missions:'Lihat misi harian dan mingguan',pet:'Buka profil Creature Hunt',petmanage:'Latih dan kelola Pet tangkapan',relics:'Lihat relik Creature',team:'Lihat atau edit tim 3 Pet'},
'ja':{achievements:'Creatureの実績を表示',adventure:'Creature PvE冒険をプレイ',ascend:'外見を変えずにCreatureの星を上げる',battle:'他のプレイヤーにPet PvPを挑む',bosshunt:'Creatureボスと戦う',collection:'Creatureコレクションを表示',dex:'Creature Dexのマイルストーンを表示・受取',hunt:'野生のCreatureをハント',missions:'デイリー・ウィークリーミッションを表示',pet:'Creature Huntプロフィールを開く',petmanage:'捕獲したPetを育成・管理',relics:'Creatureレリックを表示',team:'3体Petチームを表示・編集'},
'ko':{achievements:'Creature 업적 보기',adventure:'Creature PvE 모험 플레이',ascend:'외형 변경 없이 Creature 별 상승',battle:'다른 플레이어에게 Pet PvP 도전',bosshunt:'Creature 보스 전투',collection:'Creature 컬렉션 보기',dex:'Creature Dex 마일스톤 보기 또는 수령',hunt:'야생 Creature 사냥',missions:'일일 및 주간 Creature 미션 보기',pet:'Creature Hunt 프로필 열기',petmanage:'포획한 Pet 훈련 및 관리',relics:'Creature 유물 보기',team:'3-Pet 팀 보기 또는 편집'},
'pt-BR':{achievements:'Ver conquistas de Creature',adventure:'Jogar aventura PvE de Creature',ascend:'Aumentar estrela sem mudar a aparência',battle:'Desafiar outro jogador para Pet PvP',bosshunt:'Lutar contra um chefe Creature',collection:'Ver sua coleção de Creature',dex:'Ver ou resgatar marcos do Creature Dex',hunt:'Caçar uma Creature selvagem',missions:'Ver missões diárias e semanais',pet:'Abrir perfil do Creature Hunt',petmanage:'Treinar e gerenciar um Pet capturado',relics:'Ver relíquias de Creature',team:'Ver ou editar sua equipe de 3 Pets'},
'pt-PT':{achievements:'Ver conquistas de Creature',adventure:'Jogar aventura PvE de Creature',ascend:'Aumentar estrela sem alterar a aparência',battle:'Desafiar outro jogador para Pet PvP',bosshunt:'Lutar contra um chefe Creature',collection:'Ver a tua coleção de Creature',dex:'Ver ou recolher marcos do Creature Dex',hunt:'Caçar uma Creature selvagem',missions:'Ver missões diárias e semanais',pet:'Abrir perfil do Creature Hunt',petmanage:'Treinar e gerir um Pet capturado',relics:'Ver relíquias de Creature',team:'Ver ou editar a tua equipa de 3 Pets'},
'zh-CN':{achievements:'查看Creature成就',adventure:'进行Creature PvE冒险',ascend:'提升Creature星级且不改变外观',battle:'向其他玩家发起Pet PvP挑战',bosshunt:'挑战Creature首领',collection:'查看Creature收藏',dex:'查看或领取Creature Dex里程碑',hunt:'狩猎野生Creature',missions:'查看Creature每日和每周任务',pet:'打开Creature Hunt资料',petmanage:'训练和管理已捕获的Pet',relics:'查看Creature遗物装备',team:'查看或编辑3-Pet队伍'},
'zh-TW':{achievements:'查看Creature成就',adventure:'進行Creature PvE冒險',ascend:'提升Creature星級且不改變外觀',battle:'向其他玩家發起Pet PvP挑戰',bosshunt:'挑戰Creature首領',collection:'查看Creature收藏',dex:'查看或領取Creature Dex里程碑',hunt:'狩獵野生Creature',missions:'查看Creature每日和每週任務',pet:'開啟Creature Hunt資料',petmanage:'訓練和管理已捕獲的Pet',relics:'查看Creature遺物裝備',team:'查看或編輯3-Pet隊伍'}};

const SOCIAL={
'en':{breed:'Breed two eligible Pets',pettrade:'Trade Pets safely with another player',petmarket:'Use the player Pet marketplace',clanpetwar:'Challenge another guild to a Pet war'},
'vi':{breed:'Phối giống hai Pet đủ điều kiện',pettrade:'Trao đổi Pet an toàn với người chơi khác',petmarket:'Sử dụng chợ Pet giữa người chơi',clanpetwar:'Thách đấu Pet War với guild khác'},
'de':{breed:'Zwei geeignete Pets züchten',pettrade:'Pets sicher mit Spielern tauschen',petmarket:'Spieler-Pet-Marktplatz nutzen',clanpetwar:'Andere Gilde zum Pet-Krieg herausfordern'},
'es':{breed:'Criar dos Pets elegibles',pettrade:'Intercambiar Pets de forma segura',petmarket:'Usar el mercado de Pets',clanpetwar:'Desafiar otro gremio a guerra Pet'},
'fr':{breed:'Reproduire deux Pets éligibles',pettrade:'Échanger des Pets en sécurité',petmarket:'Utiliser le marché des Pets',clanpetwar:'Défier une guilde en guerre Pet'},
'id':{breed:'Breed dua Pet yang memenuhi syarat',pettrade:'Trade Pet dengan aman',petmarket:'Gunakan marketplace Pet',clanpetwar:'Tantang guild lain ke Pet War'},
'ja':{breed:'条件を満たす2体のPetを繁育',pettrade:'他プレイヤーと安全にPet交換',petmarket:'Petマーケットを利用',clanpetwar:'他ギルドにPet戦を挑む'},
'ko':{breed:'조건을 충족한 Pet 두 마리 브리딩',pettrade:'다른 플레이어와 안전하게 Pet 교환',petmarket:'Pet 마켓 이용',clanpetwar:'다른 길드에 Pet 전쟁 도전'},
'pt-BR':{breed:'Cruzar dois Pets elegíveis',pettrade:'Trocar Pets com segurança',petmarket:'Usar o mercado de Pets',clanpetwar:'Desafiar outra guilda para guerra Pet'},
'pt-PT':{breed:'Cruzar dois Pets elegíveis',pettrade:'Trocar Pets em segurança',petmarket:'Usar o mercado de Pets',clanpetwar:'Desafiar outra guilda para guerra Pet'},
'zh-CN':{breed:'繁育两只符合条件的Pet',pettrade:'与其他玩家安全交易Pet',petmarket:'使用玩家Pet市场',clanpetwar:'向其他公会发起Pet战争'},
'zh-TW':{breed:'繁育兩隻符合條件的Pet',pettrade:'與其他玩家安全交易Pet',petmarket:'使用玩家Pet市場',clanpetwar:'向其他公會發起Pet戰爭'}};for(const [k,v] of Object.entries(SOCIAL))Object.assign(L[k],v);

const ECON={
'en':{petshop:'Open the Pet Shop',worldboss:'Fight the scheduled Pet World Boss'},'vi':{petshop:'Mở Pet Shop',worldboss:'Chiến đấu Boss Thế Giới Pet theo khung giờ'},'de':{petshop:'Pet-Shop öffnen',worldboss:'Geplanten Pet-Weltboss bekämpfen'},'es':{petshop:'Abrir la tienda Pet',worldboss:'Luchar contra el jefe mundial Pet programado'},'fr':{petshop:'Ouvrir la boutique Pet',worldboss:'Combattre le World Boss Pet programmé'},'id':{petshop:'Buka Pet Shop',worldboss:'Lawan World Boss Pet terjadwal'},'ja':{petshop:'Petショップを開く',worldboss:'時間限定Petワールドボスと戦う'},'ko':{petshop:'Pet 상점 열기',worldboss:'시간제 Pet 월드 보스 전투'},'pt-BR':{petshop:'Abrir a loja Pet',worldboss:'Lutar contra o World Boss Pet agendado'},'pt-PT':{petshop:'Abrir a loja Pet',worldboss:'Lutar contra o World Boss Pet agendado'},'zh-CN':{petshop:'打开Pet商店',worldboss:'挑战定时Pet世界首领'},'zh-TW':{petshop:'開啟Pet商店',worldboss:'挑戰定時Pet世界首領'}};
for(const [k,v] of Object.entries(ECON))Object.assign(L[k],v);
function descriptions(key){
  const out={};
  const discordLocale={
    'pt-PT':'pt-BR'
  };
  for(const [lang,x] of Object.entries(L)){
    if(lang==='en') continue;
    const locale=discordLocale[lang]||lang;
    if(x?.[key]) out[locale]=x[key];
  }
  return out;
}
module.exports={L,descriptions};
