const FishingSettings=require('../models/FishingSettings');
const {RARITIES,RODS,BAITS}=require('../modules/fishing/config');
const DEFAULTS={enabled:true,cooldownMs:8000,starterBait:20,maxBag:250,sellAllEnabled:true,rankingEnabled:true,scoreWeights:{catch:2,weight:.4,dex:250,bestWeight:2}};
async function row(){return FishingSettings.findOneAndUpdate({key:'global'},{$setOnInsert:{key:'global'}},{upsert:true,returnDocument:'after',setDefaultsOnInsert:true});}
async function get(){const r=await row();const chances=Object.fromEntries(RARITIES.map(x=>[x.id,Number(r.rarityChances?.get?.(x.id)??x.chance)]));const scores=Object.fromEntries(RARITIES.map(x=>[x.id,Number(r.rarityScores?.get?.(x.id)??x.score)]));const baits={};for(const [k,v] of Object.entries(BAITS)){const o=r.baitOverrides?.get?.(k)||{};baits[k]={...v,...o,cost:Number(o.cost??v.cost),qty:Number(o.qty??v.qty),luck:Number(o.luck??v.luck),weight:Number(o.weight??v.weight)};}const rods=RODS.map((v,i)=>{const o=r.rodOverrides?.get?.(String(i))||{};return {...v,...o,fish:Number(o.fish??v.fish),kg:Number(o.kg??v.kg),cost:Number(o.cost??v.cost),luck:Number(o.luck??v.luck),weight:Number(o.weight??v.weight)};});return{enabled:r.enabled,cooldownMs:r.cooldownMs,starterBait:r.starterBait,maxBag:r.maxBag,sellAllEnabled:r.sellAllEnabled,rankingEnabled:r.rankingEnabled,rarityChances:chances,rarityScores:scores,baits,rods,scoreWeights:{...DEFAULTS.scoreWeights,...(r.scoreWeights||{})}};}
async function setGeneral(v,actor){const patch={updatedBy:actor};for(const k of ['cooldownMs','starterBait','maxBag'])if(v[k]!=null)patch[k]=Number(v[k]);for(const k of ['enabled','sellAllEnabled','rankingEnabled'])if(v[k]!=null)patch[k]=!!v[k];return FishingSettings.findOneAndUpdate({key:'global'},{$set:patch,$setOnInsert:{key:'global'}},{upsert:true,returnDocument:'after'});}
async function setRarities(text,actor){const parts=text.split(/[\n,]+/).map(x=>x.trim()).filter(Boolean),map={};for(const p of parts){const [id,val]=p.split('=').map(x=>x.trim());if(!RARITIES.some(r=>r.id===id))throw new Error(`Unknown rarity: ${id}`);const n=Number(val);if(!Number.isFinite(n)||n<0)throw new Error(`Invalid chance: ${p}`);map[id]=n;}const merged=Object.fromEntries(RARITIES.map(r=>[r.id,map[r.id]??r.chance]));const total=Object.values(merged).reduce((a,b)=>a+b,0);if(Math.abs(total-100)>.0001)throw new Error(`Rarity total must equal 100%. Current: ${total}`);return FishingSettings.findOneAndUpdate({key:'global'},{$set:{rarityChances:merged,updatedBy:actor},$setOnInsert:{key:'global'}},{upsert:true,returnDocument:'after'});}
async function setBait(key,text,actor){if(!BAITS[key])throw new Error('Unknown bait.');const [cost,qty,luck,weight]=text.split('|').map(x=>Number(x.trim()));if([cost,qty,luck,weight].some(x=>!Number.isFinite(x)||x<0))throw new Error('Use: cost | qty | luck | weight');const r=await row();r.baitOverrides.set(key,{cost,qty,luck,weight});r.updatedBy=actor;return r.save();}
async function setRod(level,text,actor){if(!RODS[level])throw new Error('Unknown rod level.');const [fish,kg,cost,luck,weight]=text.split('|').map(x=>Number(x.trim()));if([fish,kg,cost,luck,weight].some(x=>!Number.isFinite(x)||x<0))throw new Error('Use: fish | kg | cost | luck | weight');const r=await row();r.rodOverrides.set(String(level),{fish,kg,cost,luck,weight});r.updatedBy=actor;return r.save();}
async function setScore(text,actor){const [catchW,weight,dex,bestWeight]=text.split('|').map(x=>Number(x.trim()));if([catchW,weight,dex,bestWeight].some(x=>!Number.isFinite(x)||x<0))throw new Error('Use: catch | weight | dex | bestWeight');return FishingSettings.findOneAndUpdate({key:'global'},{$set:{scoreWeights:{catch:catchW,weight,dex,bestWeight},updatedBy:actor},$setOnInsert:{key:'global'}},{upsert:true,returnDocument:'after'});}
async function reset(actor){await FishingSettings.deleteOne({key:'global'});const r=await row();r.updatedBy=actor;return r.save();}
module.exports={get,setGeneral,setRarities,setBait,setRod,setScore,reset};
