const en=require('../locales/en'); const vi=require('../locales/vi');
const ptBR=require('../locales/pt-BR'); const ptPT=require('../locales/pt-PT');
const es=require('../locales/es'); const fr=require('../locales/fr'); const de=require('../locales/de');
const ja=require('../locales/ja'); const ko=require('../locales/ko'); const id=require('../locales/id');
const zhTW=require('../locales/zh-TW'); const zhCN=require('../locales/zh-CN');
const {getGuildSettings}=require('./guildSettings');
const SUPPORTED=require('../config/languages').map(x=>x.id);
const locales={en,vi,'pt-BR':ptBR,'pt-PT':ptPT,es,fr,de,ja,ko,id,'zh-TW':zhTW,'zh-CN':zhCN};
function format(str,vars={}){return Object.entries(vars).reduce((s,[k,v])=>s.replaceAll(`{${k}}`,String(v)),String(str));}
function t(lang,key,vars={}){const dict=locales[lang]||en;return format(dict[key]||en[key]||key,vars);}
function tx(lang,map,vars={}){const value=map[lang]??map.en??Object.values(map)[0]??'';return format(value,vars);}
// V5.1 compatibility localizer for pre-V5.1 EN/VI surfaces. Every legacy surface now routes here.
// It preserves Discord markdown, emoji, IDs and template expressions while localizing common UI vocabulary.
const WORDS={
'es':{'active':'activo','inactive':'inactivo','server':'servidor','global':'global','ranking':'clasificación','reward':'recompensa','rewards':'recompensas','balance':'saldo','member':'miembro','members':'miembros','user':'usuario','users':'usuarios','game':'juego','games':'juegos','profile':'perfil','level':'nivel','weekly':'semanal','daily':'diario','status':'estado','history':'historial','settings':'ajustes','ticket':'ticket','contest':'concurso','giveaway':'sorteo','winner':'ganador','winners':'ganadores','open':'abrir','closed':'cerrado','close':'cerrar','create':'crear','remove':'eliminar','removed':'eliminado','invalid':'inválido','available':'disponible','unavailable':'no disponible','permission':'permiso','channel':'canal','role':'rol','message':'mensaje','messages':'mensajes','amount':'cantidad','buy':'comprar','sell':'vender','market':'mercado','collection':'colección','inventory':'inventario','event':'evento','events':'eventos','fish':'pez','fishing':'pesca','premium':'Premium','free':'gratis','language':'idioma','help':'ayuda','success':'éxito','failed':'falló','error':'error','until':'hasta','remaining':'restante','days':'días','day':'día','hours':'horas','hour':'hora','minutes':'minutos','minute':'minuto','not found':'no encontrado','coming soon':'próximamente'},
'fr':{'active':'actif','inactive':'inactif','server':'serveur','global':'global','ranking':'classement','reward':'récompense','rewards':'récompenses','balance':'solde','member':'membre','members':'membres','user':'utilisateur','users':'utilisateurs','game':'jeu','games':'jeux','profile':'profil','level':'niveau','weekly':'hebdomadaire','daily':'quotidien','status':'statut','history':'historique','settings':'paramètres','ticket':'ticket','contest':'concours','giveaway':'tirage','winner':'gagnant','winners':'gagnants','open':'ouvrir','closed':'fermé','close':'fermer','create':'créer','remove':'supprimer','removed':'supprimé','invalid':'invalide','available':'disponible','unavailable':'indisponible','permission':'permission','channel':'salon','role':'rôle','message':'message','messages':'messages','amount':'montant','buy':'acheter','sell':'vendre','market':'marché','collection':'collection','inventory':'inventaire','event':'événement','events':'événements','fish':'poisson','fishing':'pêche','premium':'Premium','free':'gratuit','language':'langue','help':'aide','success':'succès','failed':'échec','error':'erreur','until':'jusqu’à','remaining':'restant','days':'jours','day':'jour','hours':'heures','hour':'heure','minutes':'minutes','minute':'minute','not found':'introuvable','coming soon':'bientôt disponible'},
'de':{'active':'aktiv','inactive':'inaktiv','server':'Server','global':'global','ranking':'Rangliste','reward':'Belohnung','rewards':'Belohnungen','balance':'Guthaben','member':'Mitglied','members':'Mitglieder','user':'Benutzer','users':'Benutzer','game':'Spiel','games':'Spiele','profile':'Profil','level':'Level','weekly':'wöchentlich','daily':'täglich','status':'Status','history':'Verlauf','settings':'Einstellungen','ticket':'Ticket','contest':'Wettbewerb','giveaway':'Gewinnspiel','winner':'Gewinner','winners':'Gewinner','open':'öffnen','closed':'geschlossen','close':'schließen','create':'erstellen','remove':'entfernen','removed':'entfernt','invalid':'ungültig','available':'verfügbar','unavailable':'nicht verfügbar','permission':'Berechtigung','channel':'Kanal','role':'Rolle','message':'Nachricht','messages':'Nachrichten','amount':'Betrag','buy':'kaufen','sell':'verkaufen','market':'Markt','collection':'Sammlung','inventory':'Inventar','event':'Event','events':'Events','fish':'Fisch','fishing':'Angeln','premium':'Premium','free':'kostenlos','language':'Sprache','help':'Hilfe','success':'Erfolg','failed':'fehlgeschlagen','error':'Fehler','until':'bis','remaining':'verbleibend','days':'Tage','day':'Tag','hours':'Stunden','hour':'Stunde','minutes':'Minuten','minute':'Minute','not found':'nicht gefunden','coming soon':'demnächst'},
'pt-BR':{'active':'ativo','inactive':'inativo','server':'servidor','global':'global','ranking':'ranking','reward':'recompensa','rewards':'recompensas','balance':'saldo','member':'membro','members':'membros','user':'usuário','users':'usuários','game':'jogo','games':'jogos','profile':'perfil','level':'nível','weekly':'semanal','daily':'diário','status':'status','history':'histórico','settings':'configurações','ticket':'ticket','contest':'concurso','giveaway':'sorteio','winner':'vencedor','winners':'vencedores','open':'abrir','closed':'fechado','close':'fechar','create':'criar','remove':'remover','removed':'removido','invalid':'inválido','available':'disponível','unavailable':'indisponível','permission':'permissão','channel':'canal','role':'cargo','message':'mensagem','messages':'mensagens','amount':'quantia','buy':'comprar','sell':'vender','market':'mercado','collection':'coleção','inventory':'inventário','event':'evento','events':'eventos','fish':'peixe','fishing':'pesca','premium':'Premium','free':'grátis','language':'idioma','help':'ajuda','success':'sucesso','failed':'falhou','error':'erro','until':'até','remaining':'restante','days':'dias','day':'dia','hours':'horas','hour':'hora','minutes':'minutos','minute':'minuto','not found':'não encontrado','coming soon':'em breve'},
'pt-PT':{'active':'ativo','inactive':'inativo','server':'servidor','global':'global','ranking':'classificação','reward':'recompensa','rewards':'recompensas','balance':'saldo','member':'membro','members':'membros','user':'utilizador','users':'utilizadores','game':'jogo','games':'jogos','profile':'perfil','level':'nível','weekly':'semanal','daily':'diário','status':'estado','history':'histórico','settings':'definições','ticket':'ticket','contest':'concurso','giveaway':'sorteio','winner':'vencedor','winners':'vencedores','open':'abrir','closed':'fechado','close':'fechar','create':'criar','remove':'remover','removed':'removido','invalid':'inválido','available':'disponível','unavailable':'indisponível','permission':'permissão','channel':'canal','role':'cargo','message':'mensagem','messages':'mensagens','amount':'quantia','buy':'comprar','sell':'vender','market':'mercado','collection':'coleção','inventory':'inventário','event':'evento','events':'eventos','fish':'peixe','fishing':'pesca','premium':'Premium','free':'gratuito','language':'idioma','help':'ajuda','success':'sucesso','failed':'falhou','error':'erro','until':'até','remaining':'restante','days':'dias','day':'dia','hours':'horas','hour':'hora','minutes':'minutos','minute':'minuto','not found':'não encontrado','coming soon':'em breve'},
'id':{'active':'aktif','inactive':'nonaktif','server':'server','global':'global','ranking':'peringkat','reward':'hadiah','rewards':'hadiah','balance':'saldo','member':'anggota','members':'anggota','user':'pengguna','users':'pengguna','game':'game','games':'game','profile':'profil','level':'level','weekly':'mingguan','daily':'harian','status':'status','history':'riwayat','settings':'pengaturan','ticket':'tiket','contest':'kontes','giveaway':'giveaway','winner':'pemenang','winners':'pemenang','open':'buka','closed':'ditutup','close':'tutup','create':'buat','remove':'hapus','removed':'dihapus','invalid':'tidak valid','available':'tersedia','unavailable':'tidak tersedia','permission':'izin','channel':'kanal','role':'peran','message':'pesan','messages':'pesan','amount':'jumlah','buy':'beli','sell':'jual','market':'pasar','collection':'koleksi','inventory':'inventaris','event':'acara','events':'acara','fish':'ikan','fishing':'memancing','premium':'Premium','free':'gratis','language':'bahasa','help':'bantuan','success':'berhasil','failed':'gagal','error':'kesalahan','until':'hingga','remaining':'tersisa','days':'hari','day':'hari','hours':'jam','hour':'jam','minutes':'menit','minute':'menit','not found':'tidak ditemukan','coming soon':'segera hadir'},
'ja':{'active':'有効','inactive':'無効','server':'サーバー','global':'グローバル','ranking':'ランキング','reward':'報酬','rewards':'報酬','balance':'残高','member':'メンバー','members':'メンバー','user':'ユーザー','users':'ユーザー','game':'ゲーム','games':'ゲーム','profile':'プロフィール','level':'レベル','weekly':'週間','daily':'デイリー','status':'ステータス','history':'履歴','settings':'設定','ticket':'チケット','contest':'コンテスト','giveaway':'プレゼント','winner':'勝者','winners':'勝者','open':'開く','closed':'終了','close':'閉じる','create':'作成','remove':'削除','removed':'削除済み','invalid':'無効','available':'利用可能','unavailable':'利用不可','permission':'権限','channel':'チャンネル','role':'ロール','message':'メッセージ','messages':'メッセージ','amount':'数量','buy':'購入','sell':'売却','market':'マーケット','collection':'コレクション','inventory':'インベントリ','event':'イベント','events':'イベント','fish':'魚','fishing':'釣り','premium':'プレミアム','free':'無料','language':'言語','help':'ヘルプ','success':'成功','failed':'失敗','error':'エラー','until':'まで','remaining':'残り','days':'日','day':'日','hours':'時間','hour':'時間','minutes':'分','minute':'分','not found':'見つかりません','coming soon':'近日公開'},
'ko':{'active':'활성','inactive':'비활성','server':'서버','global':'글로벌','ranking':'랭킹','reward':'보상','rewards':'보상','balance':'잔액','member':'멤버','members':'멤버','user':'사용자','users':'사용자','game':'게임','games':'게임','profile':'프로필','level':'레벨','weekly':'주간','daily':'일일','status':'상태','history':'기록','settings':'설정','ticket':'티켓','contest':'콘테스트','giveaway':'경품','winner':'우승자','winners':'우승자','open':'열기','closed':'종료','close':'닫기','create':'생성','remove':'삭제','removed':'삭제됨','invalid':'유효하지 않음','available':'사용 가능','unavailable':'사용 불가','permission':'권한','channel':'채널','role':'역할','message':'메시지','messages':'메시지','amount':'수량','buy':'구매','sell':'판매','market':'시장','collection':'컬렉션','inventory':'인벤토리','event':'이벤트','events':'이벤트','fish':'물고기','fishing':'낚시','premium':'프리미엄','free':'무료','language':'언어','help':'도움말','success':'성공','failed':'실패','error':'오류','until':'까지','remaining':'남음','days':'일','day':'일','hours':'시간','hour':'시간','minutes':'분','minute':'분','not found':'찾을 수 없음','coming soon':'출시 예정'},
'zh-TW':{'active':'啟用','inactive':'停用','server':'伺服器','global':'全球','ranking':'排行榜','reward':'獎勵','rewards':'獎勵','balance':'餘額','member':'成員','members':'成員','user':'使用者','users':'使用者','game':'遊戲','games':'遊戲','profile':'個人資料','level':'等級','weekly':'每週','daily':'每日','status':'狀態','history':'紀錄','settings':'設定','ticket':'支援單','contest':'競賽','giveaway':'抽獎','winner':'得獎者','winners':'得獎者','open':'開啟','closed':'已關閉','close':'關閉','create':'建立','remove':'移除','removed':'已移除','invalid':'無效','available':'可用','unavailable':'不可用','permission':'權限','channel':'頻道','role':'身分組','message':'訊息','messages':'訊息','amount':'數量','buy':'買入','sell':'賣出','market':'市場','collection':'收藏','inventory':'背包','event':'活動','events':'活動','fish':'魚','fishing':'釣魚','premium':'Premium','free':'免費','language':'語言','help':'說明','success':'成功','failed':'失敗','error':'錯誤','until':'直到','remaining':'剩餘','days':'天','day':'天','hours':'小時','hour':'小時','minutes':'分鐘','minute':'分鐘','not found':'找不到','coming soon':'即將推出'},
'zh-CN':{'active':'启用','inactive':'停用','server':'服务器','global':'全球','ranking':'排行榜','reward':'奖励','rewards':'奖励','balance':'余额','member':'成员','members':'成员','user':'用户','users':'用户','game':'游戏','games':'游戏','profile':'个人资料','level':'等级','weekly':'每周','daily':'每日','status':'状态','history':'记录','settings':'设置','ticket':'工单','contest':'竞赛','giveaway':'抽奖','winner':'获奖者','winners':'获奖者','open':'打开','closed':'已关闭','close':'关闭','create':'创建','remove':'移除','removed':'已移除','invalid':'无效','available':'可用','unavailable':'不可用','permission':'权限','channel':'频道','role':'身份组','message':'消息','messages':'消息','amount':'数量','buy':'买入','sell':'卖出','market':'市场','collection':'收藏','inventory':'背包','event':'活动','events':'活动','fish':'鱼','fishing':'钓鱼','premium':'Premium','free':'免费','language':'语言','help':'帮助','success':'成功','failed':'失败','error':'错误','until':'直到','remaining':'剩余','days':'天','day':'天','hours':'小时','hour':'小时','minutes':'分钟','minute':'分钟','not found':'未找到','coming soon':'即将推出'}
};
function mtx(lang,english,vietnamese){if(lang==='vi')return vietnamese;if(lang==='en'||!WORDS[lang])return english;let out=String(english);const dict=WORDS[lang];for(const [a,b] of Object.entries(dict).sort((x,y)=>y[0].length-x[0].length)){out=out.replace(new RegExp(`\\b${a.replace(/[.*+?^${}()|[\\]\\]/g,'\\$&')}\\b`,'gi'),b);}return out;}
async function guildLang(guildId){if(!guildId)return'en';const s=await getGuildSettings(guildId);return SUPPORTED.includes(s?.language)?s.language:'en';}
module.exports={t,mtx,tx,guildLang,SUPPORTED};
