const MarketAsset=require('../models/MarketAsset');const MarketPortfolio=require('../models/MarketPortfolio');const MarketEvents=require('./marketEventService');const UserEconomy=require('../models/UserEconomy');const {walletFilter,ensureWallet}=require('./economyWallet');
const TICK_MS=15*60*1000;
const SEEDS=[
 ['CRGI','Corgi Coin','CRYPTO','Digital',1284,.055],['NOVA','Nova Token','CRYPTO','Digital',742,.07],['BYTE','ByteChain','CRYPTO','Digital',2410,.06],['LUNA','Luna Shard','CRYPTO','Digital',386,.08],
 ['PAWT','Paw Technologies','STOCK','Technology',925,.035],['ORBT','Orbit Works','STOCK','Industry',1630,.03],['EMBER','Ember Energy','STOCK','Energy',1180,.04],['MINT','Mint Foods','STOCK','Consumer',540,.025],
 ['CIX','Corgi Composite Index','SECURITIES','Index',10000,.012],['TECHX','Tech Basket','SECURITIES','Fund',5000,.018],['GROW','Growth Basket','SECURITIES','Fund',3200,.02],['SAFE','Stable Basket','SECURITIES','Fund',2500,.008]
];
async function seed(){for(const [symbol,name,category,sector,price,volatility] of SEEDS)await MarketAsset.updateOne({symbol},{$setOnInsert:{symbol,name,category,sector,price,previousPrice:price,open:price,high:price,low:price,volatility,lastTickAt:new Date(0),lastDailyOpenAt:new Date()}},{upsert:true});}
function utcDay(d=new Date()){return d.toISOString().slice(0,10)}
async function tick({force=false}={}){await seed();const assets=await MarketAsset.find({enabled:true});const now=new Date();if(!force&&assets.length&&assets.every(a=>a.lastTickAt&&now-a.lastTickAt<TICK_MS))return assets;const {events}=await MarketEvents.cycle();const globalSentiment=(Math.random()+Math.random()-1)*.008;for(const a of assets){const old=a.price;if(!a.lastDailyOpenAt||utcDay(a.lastDailyOpenAt)!==utcDay(now)){a.open=old;a.high=old;a.low=old;a.volume=0;a.lastDailyOpenAt=now;}const natural=(Math.random()+Math.random()-1)*a.volatility*.35;const eventPressure=MarketEvents.modifierFor(a.symbol,events);a.sentiment=Math.max(-.03,Math.min(.03,(a.sentiment||0)*.75+globalSentiment));a.trend=Math.max(-.02,Math.min(.02,(a.trend||0)*.85+natural*.15));const mean=((a.open||old)-old)/Math.max(1,old)*.04;const shock=Math.max(-.06,Math.min(.06,natural+eventPressure+a.sentiment+a.trend+mean));const next=Math.max(10,Number((old*(1+shock)).toFixed(2)));a.previousPrice=old;a.price=next;a.high=Math.max(a.high||next,next);a.low=Math.min(a.low||next,next);a.volume+=(100+Math.floor(Math.random()*5000));a.lastTickAt=now;await a.save();}return assets;}
async function list({refresh=true}={}){
  if(refresh) await tick();
  return MarketAsset.find({enabled:true})
    .sort({category:1,symbol:1})
    .lean();
}
async function portfolio(userId,{refresh=true}={}){const [p,w,assets]=await Promise.all([MarketPortfolio.findOneAndUpdate({userId:String(userId)},{$setOnInsert:{userId:String(userId)}},{upsert:true,returnDocument:'after'}),ensureWallet(userId),list({refresh})]);const prices=new Map(assets.map(a=>[a.symbol,a.price]));let invested=0,value=0;for(const x of p.positions){invested+=x.avgCost*x.quantity;value+=(prices.get(x.symbol)||0)*x.quantity;}return{p,w,assets,invested,value,unrealized:value-invested};}
async function buy(userId,symbol,quantity){quantity=Number(quantity);if(!Number.isInteger(quantity)||quantity<1||quantity>100000)throw Error('INVALID_QUANTITY');await tick();const a=await MarketAsset.findOne({symbol:String(symbol).toUpperCase(),enabled:true});if(!a)throw Error('ASSET_NOT_FOUND');const cost=Math.ceil(a.price*quantity);await ensureWallet(userId);const w=await UserEconomy.findOneAndUpdate({...walletFilter(userId),cstar:{$gte:cost}},{$inc:{cstar:-cost}},{returnDocument:'after'});if(!w)throw Error('INSUFFICIENT_CXU');const p=await MarketPortfolio.findOneAndUpdate({userId:String(userId)},{$setOnInsert:{userId:String(userId)}},{upsert:true,returnDocument:'after'});const pos=p.positions.find(x=>x.symbol===a.symbol);if(pos){const total=pos.quantity+quantity;pos.avgCost=((pos.avgCost*pos.quantity)+(a.price*quantity))/total;pos.quantity=total;}else p.positions.push({symbol:a.symbol,quantity,avgCost:a.price});p.trades=(p.trades||0)+1;await p.save();return{asset:a,quantity,cost,w};}
async function sell(userId,symbol,quantity){quantity=Number(quantity);if(!Number.isInteger(quantity)||quantity<1||quantity>100000)throw Error('INVALID_QUANTITY');await tick();const a=await MarketAsset.findOne({symbol:String(symbol).toUpperCase(),enabled:true});if(!a)throw Error('ASSET_NOT_FOUND');const p=await MarketPortfolio.findOne({userId:String(userId)});const pos=p?.positions.find(x=>x.symbol===a.symbol);if(!pos||pos.quantity<quantity)throw Error('NOT_ENOUGH_ASSET');const proceeds=Math.floor(a.price*quantity),realized=(a.price-pos.avgCost)*quantity;pos.quantity-=quantity;if(pos.quantity<=0)p.positions=p.positions.filter(x=>x.symbol!==a.symbol);p.realizedPnl=(p.realizedPnl||0)+realized;p.trades=(p.trades||0)+1;await p.save();const w=await UserEconomy.findOneAndUpdate(walletFilter(userId),{$inc:{cstar:proceeds}},{returnDocument:'after'});return{asset:a,quantity,proceeds,realized,w};}
module.exports={SEEDS,TICK_MS,seed,tick,list,portfolio,buy,sell};
