const WB=require('../models/WorldBossState'),S=require('./creatureService'),C=require('./creatureCatalog');
const UE=require('../models/UserEconomy'),{ensureWallet,walletFilter}=require('./economyWallet');
const SPAWN_HOURS=[0,6,12,18],WINDOW_MIN=30,FREE_ATTACKS=3,EXTRA_ATTACK_COST=2000;
const BOSS={id:'void-crystal-dragon',name:'Void Crystal Dragon'};
const QUALITIES=[
 {key:'RARE',label:'Rare',chance:40,hp:5000000,atk:900,def:500,spd:90,power:25000,reward:1},
 {key:'EPIC',label:'Epic',chance:30,hp:9000000,atk:1350,def:700,spd:104,power:40000,reward:1.25},
 {key:'LEGENDARY',label:'Legendary',chance:18,hp:17500000,atk:2160,def:1000,spd:117,power:70000,reward:1.6},
 {key:'MYTHIC',label:'Mythic',chance:9,hp:35000000,atk:3600,def:1600,spd:135,power:125000,reward:2.1},
 {key:'DIVINE',label:'Divine',chance:2.5,hp:75000000,atk:6300,def:2500,spd:162,power:250000,reward:3},
 {key:'PRIMORDIAL',label:'Primordial',chance:.5,hp:150000000,atk:10800,def:4000,spd:189,power:500000,reward:5}
];
function qualityRoll(){let r=Math.random()*100;for(const q of QUALITIES){if(r<q.chance)return q;r-=q.chance}return QUALITIES[0]}
function windowNow(d=new Date()){const h=d.getUTCHours(),hour=[...SPAWN_HOURS].reverse().find(x=>x<=h);if(hour==null)return null;const start=new Date(Date.UTC(d.getUTCFullYear(),d.getUTCMonth(),d.getUTCDate(),hour,0,0));const end=new Date(start.getTime()+WINDOW_MIN*60000);if(d<start||d>=end)return null;return{start,end,key:start.toISOString().replace(/[-:]/g,'').slice(0,13)}}
async function state(){const w=windowNow();if(!w)return null;let row=await WB.findOne({spawnKey:w.key});if(row)return row;const q=qualityRoll();try{return await WB.create({spawnKey:w.key,bossId:BOSS.id,name:BOSS.name,quality:q.key,qualityLabel:q.label,maxHp:q.hp,hp:q.hp,atk:q.atk,def:q.def,spd:q.spd,power:q.power,startsAt:w.start,endsAt:w.end,status:'ACTIVE'})}catch(e){if(e?.code===11000)return WB.findOne({spawnKey:w.key});throw e}}
function teamStats(p){const team=(p.team||[]).map(id=>p.pets.find(x=>String(x._id)===String(id))).filter(Boolean).slice(0,3);return team.reduce((a,o)=>{const pet=C.byId(o.petId);if(!pet)return a;const st=S.stats(pet,o);a.hp+=st.hp;a.atk+=st.atk;a.def+=st.def;a.spd+=st.spd;a.power+=st.hp+st.atk*4+st.def*3+st.spd*2;return a},{hp:0,atk:0,def:0,spd:0,power:0,count:team.length})}
function rollDrop(mult=1){const r=Math.random()*100/mult;if(r<0.00001)return['Primordial World Orb','impossible'];if(r<0.00011)return['Divine Ascension Orb','divine'];if(r<0.00111)return['Mythic Evolution Orb','mythic'];if(r<0.01111)return['Ancient Skill Crystal','legendary'];if(r<0.11111)return['World Boss Relic Shard','epic'];if(r<1.11111)return['Enhancement Core','rare'];if(r<6.11111)return['Refine Stone','uncommon'];return['Boss Token','common']}
function qualityOf(b){return QUALITIES.find(x=>x.key===b.quality)||QUALITIES[0]}
async function chargeAttack(uid,b){const used=Number(b.attacks?.get?.(String(uid))||0);if(used<FREE_ATTACKS)return{used,cost:0};await ensureWallet(uid);const w=await UE.findOneAndUpdate({...walletFilter(uid),cstar:{$gte:EXTRA_ATTACK_COST}},{$inc:{cstar:-EXTRA_ATTACK_COST}},{returnDocument:'after'});if(!w)throw Error('INSUFFICIENT_CXU');return{used,cost:EXTRA_ATTACK_COST}}
async function refund(uid,n){if(n>0)await UE.updateOne(walletFilter(uid),{$inc:{cstar:n}}).catch(()=>{})}
async function grantMaterial(uid,drop){const p=await S.profile(uid);p.materials=p.materials||{};p.materials.bossToken=(p.materials.bossToken||0)+1;if(drop==='Enhancement Core')p.materials.enhancementCore=(p.materials.enhancementCore||0)+1;else if(drop==='Refine Stone')p.materials.refineStone=(p.materials.refineStone||0)+1;else if(drop==='Ancient Skill Crystal')p.materials.skillCrystal=(p.materials.skillCrystal||0)+1;else if(drop.includes('Orb'))p.materials.worldOrb=(p.materials.worldOrb||0)+1;else if(drop.includes('Relic'))p.materials.worldRelicShard=(p.materials.worldRelicShard||0)+1;await p.save()}
async function settle(b){const locked=await WB.findOneAndUpdate({_id:b._id,status:'DEFEATED',settledAt:null},{$set:{settledAt:new Date()}},{returnDocument:'after'});if(!locked)return b;const ranking=[...locked.contributions.entries()].map(([userId,damage])=>({userId,damage:Number(damage||0)})).sort((a,z)=>z.damage-a.damage);const q=qualityOf(locked),rewards=[];for(let i=0;i<ranking.length;i++){const x=ranking[i];let cxu=0,tokens=0;if(i===0){cxu=Math.round(10000*q.reward);tokens=10}else if(i<3){cxu=Math.round(6000*q.reward);tokens=7}else if(i<10){cxu=Math.round(3000*q.reward);tokens=4}else if(x.damage>0){cxu=Math.round(500*q.reward);tokens=1}if(String(x.userId)===String(locked.killerId)){cxu+=Math.round(5000*q.reward);tokens+=5}await ensureWallet(x.userId);await UE.updateOne(walletFilter(x.userId),{$inc:{cstar:cxu}});const p=await S.profile(x.userId);p.materials.bossToken=(p.materials.bossToken||0)+tokens;await p.save();rewards.push({userId:x.userId,rank:i+1,damage:x.damage,cxu,bossToken:tokens,kind:String(x.userId)===String(locked.killerId)?'BOSS_SLAYER':'DAMAGE'})}locked.rewards=rewards;await locked.save();return locked}
async function attack(uid){const b=await state();if(!b)throw Error('WORLD_BOSS_CLOSED');if(b.status!=='ACTIVE'||b.hp<=0)throw Error('WORLD_BOSS_DEFEATED');const p=await S.profile(uid),ts=teamStats(p);if(!ts.count)throw Error('NO_TEAM');const pay=await chargeAttack(uid,b);try{const q=qualityOf(b);const offense=Math.max(1,ts.atk*2.25+ts.power*.055);const mitigation=Math.max(.12,1000/(1000+b.def));const speed=Math.max(.75,Math.min(1.25,1+(ts.spd-b.spd)/1000));const retaliation=Math.max(0,b.atk-ts.def*.55);const survival=Math.max(.35,Math.min(1,ts.hp/(ts.hp+retaliation*2)));const damage=Math.max(1,Math.floor(offense*mitigation*speed*survival*(.9+Math.random()*.2)));const uidKey=String(uid);const fresh=await WB.findOneAndUpdate({_id:b._id,status:'ACTIVE',hp:{$gt:0}},{$inc:{hp:-damage,[`contributions.${uidKey}`]:damage,[`attacks.${uidKey}`]:1}},{returnDocument:'after'});if(!fresh){await refund(uid,pay.cost);throw Error('WORLD_BOSS_DEFEATED')}let killed=false;if(fresh.hp<=0){const won=await WB.findOneAndUpdate({_id:fresh._id,status:'ACTIVE',hp:{$lte:0}},{$set:{hp:0,status:'DEFEATED',killerId:uidKey}},{returnDocument:'after'});if(won){killed=true;Object.assign(fresh,won.toObject());await settle(won)}}const [drop,tier]=rollDrop(q.reward);await grantMaterial(uid,drop);return{boss:fresh,damage,drop,tier,power:ts.power,cost:pay.cost,attackNumber:pay.used+1,freeRemaining:Math.max(0,FREE_ATTACKS-(pay.used+1)),killed}}catch(e){await refund(uid,pay.cost);throw e}}
function leaderboard(b,limit=10){return [...(b?.contributions?.entries?.()||[])].map(([userId,damage])=>({userId,damage:Number(damage||0)})).sort((a,z)=>z.damage-a.damage).slice(0,limit)}
function attacksFor(b,uid){return Number(b?.attacks?.get?.(String(uid))||0)}
module.exports={SPAWN_HOURS,WINDOW_MIN,FREE_ATTACKS,EXTRA_ATTACK_COST,QUALITIES,BOSS,state,attack,windowNow,leaderboard,attacksFor};
