const {EmbedBuilder,ActionRowBuilder,ButtonBuilder,ButtonStyle,ModalBuilder,TextInputBuilder,TextInputStyle}=require('discord.js');
const P=require('./progression');

function row(...buttons){return new ActionRowBuilder().addComponents(...buttons);}
function back(){return row(new ButtonBuilder().setCustomId('dev:home').setLabel('Developer Home').setEmoji('⬅️').setStyle(ButtonStyle.Secondary));}
function input(id,label,value,required=true){const x=new TextInputBuilder().setCustomId(id).setLabel(label).setStyle(TextInputStyle.Short).setRequired(required);if(value!==undefined&&value!==null&&String(value)!=='')x.setValue(String(value));return new ActionRowBuilder().addComponents(x);}
async function levelPage(){const s=await P.settings(),c=s.progression;const e=new EmbedBuilder().setColor(0xF59E0B).setTitle('⚔️ Global Level & EXP Control').setDescription('One Discord user = one global Level/EXP profile across every server. Default curve is intentionally slower at high levels.').addFields({name:'EXP per qualified message',value:`**${c.xpMin}–${c.xpMax} EXP**`,inline:true},{name:'Cooldown',value:`**${c.cooldownSeconds}s**`,inline:true},{name:'Maximum Level',value:`**${c.maxLevel.toLocaleString()}**`,inline:true},{name:'Curve',value:`EXP next ≈ **${c.curveBase} × (1 + Level / ${c.curveDivisor}) ^ ${c.curvePower}**`});return{embeds:[e],components:[row(new ButtonBuilder().setCustomId('progdev:level:edit').setLabel('Edit EXP Config').setEmoji('⚙️').setStyle(ButtonStyle.Primary),new ButtonBuilder().setCustomId('progdev:level:advanced').setLabel('Advanced Curve').setEmoji('📈').setStyle(ButtonStyle.Secondary),new ButtonBuilder().setCustomId('progdev:level:user').setLabel('Adjust User').setEmoji('🧑‍💻').setStyle(ButtonStyle.Success)),back()]};}
async function rankingPage(){const s=await P.settings(),w=P.weekInfo(),r=s.rankingRewards;const e=new EmbedBuilder().setColor(0xF59E0B).setTitle('🏆 Global Weekly Ranking Control').setDescription(`Current season: **${w.key}**\nCountdown: <t:${Math.floor(w.end.getTime()/1000)}:R>\n\n**Approve Reward** snapshots the current Top 100 and pays everybody automatically. It can be pressed whenever you choose, but only once per weekly season.`).addFields({name:'🥇 #1 • Thần Vương Vô Địch (7d)',value:`${Number(r.top1).toLocaleString()} <:cxu_coin:1551759873241251912> CXu`,inline:true},{name:'🥈 #2 • Á Vương Vô Địch (7d)',value:`${Number(r.top2).toLocaleString()} <:cxu_coin:1551759873241251912> CXu`,inline:true},{name:'🥉 #3 • Quý Vương Vô Địch (7d)',value:`${Number(r.top3).toLocaleString()} <:cxu_coin:1551759873241251912> CXu`,inline:true},{name:'#4–10 • Chiến Thần Top 10 (7d)',value:`${Number(r.top4to10).toLocaleString()} <:cxu_coin:1551759873241251912> CXu`,inline:true},{name:'#11–100 • Đại Gia Mới Nổi (7d)',value:`${Number(r.top11to100).toLocaleString()} <:cxu_coin:1551759873241251912> CXu`,inline:true});return{embeds:[e],components:[row(new ButtonBuilder().setCustomId('progdev:ranking:approve').setLabel('Approve Reward').setEmoji('🎁').setStyle(ButtonStyle.Success),new ButtonBuilder().setCustomId('progdev:ranking:edit').setLabel('Edit Rewards').setEmoji('⚙️').setStyle(ButtonStyle.Primary)),back()]};}

async function levelModal(){const s=await P.settings(),c=s.progression;return new ModalBuilder().setCustomId('progdev:modal:level').setTitle('Level & EXP Configuration').addComponents(input('xpMin','Minimum EXP per message',c.xpMin),input('xpMax','Maximum EXP per message',c.xpMax),input('cooldown','Cooldown seconds',c.cooldownSeconds),input('curveBase','Curve base EXP',c.curveBase),input('curvePower','Curve power (1.01 - 3.00)',c.curvePower));}
async function rewardModal(){const s=await P.settings(),r=s.rankingRewards;return new ModalBuilder().setCustomId('progdev:modal:rewards').setTitle('Weekly Ranking Rewards').addComponents(input('top1','Top 1 <:cxu_coin:1551759873241251912> CXu',r.top1),input('top2','Top 2 <:cxu_coin:1551759873241251912> CXu',r.top2),input('top3','Top 3 <:cxu_coin:1551759873241251912> CXu',r.top3),input('top4to10','Top 4-10 <:cxu_coin:1551759873241251912> CXu',r.top4to10),input('top11to100','Top 11-100 <:cxu_coin:1551759873241251912> CXu',r.top11to100));}




function userLevelModal(){return new ModalBuilder().setCustomId('progdev:modal:userlevel').setTitle('Developer • Set User Level/EXP').addComponents(input('userId','Discord User ID','123456789012345678'),input('level','Level (1 - 100000)','1'),input('xp','Current level EXP','0'));}
async function advancedLevelModal(){const s=await P.settings(),c=s.progression;return new ModalBuilder().setCustomId('progdev:modal:advancedlevel').setTitle('Advanced Level Curve').addComponents(input('maxLevel','Maximum Level (max 100000)',c.maxLevel),input('curveDivisor','Curve divisor',c.curveDivisor));}

module.exports={levelPage,rankingPage,levelModal,userLevelModal,advancedLevelModal,rewardModal};
