const SeasonalEvent=require('../models/SeasonalEvent');const SeasonalInventory=require('../models/SeasonalInventory');const UserEconomy=require('../models/UserEconomy');const {walletFilter,ensureWallet}=require('./economyWallet');
const N=(en,vi,br,pt,es,fr,de,ja,ko,id,tw,cn)=>new Map(Object.entries({en,vi,'pt-BR':br,'pt-PT':pt,es,fr,de,ja,ko,id,'zh-TW':tw,'zh-CN':cn}));
const templates=[
 {key:'lunar-new-year',name:N('Lunar New Year','Tết Nguyên Đán','Ano Novo Lunar','Ano Novo Lunar','Año Nuevo Lunar','Nouvel An lunaire','Mondneujahr','旧正月','설날','Tahun Baru Imlek','農曆新年','农历新年'),materials:[
  ['rice','🌾',N('Rice','Gạo','Arroz','Arroz','Arroz','Riz','Reis','米','쌀','Beras','米','大米'),.14],
  ['leaf','🍃',N('Wrapping Leaf','Lá gói','Folha para embrulhar','Folha para embrulhar','Hoja para envolver','Feuille d’emballage','Wickelblatt','包み葉','포장 잎','Daun pembungkus','包裝葉','包装叶'),.10],
  ['bean','🫘',N('Mung Bean','Đậu xanh','Feijão-mungo','Feijão-mungo','Frijol mungo','Haricot mungo','Mungbohne','緑豆','녹두','Kacang hijau','綠豆','绿豆'),.08]],recipes:[['banh','🟩',N('Bánh Chưng / Bánh Tét','Bánh Chưng / Bánh Tét','Bánh Chưng / Bánh Tét','Bánh Chưng / Bánh Tét','Bánh Chưng / Bánh Tét','Bánh Chưng / Bánh Tét','Bánh Chưng / Bánh Tét','バインチュン / バインテット','반쯩 / 반뗏','Bánh Chưng / Bánh Tét','粽餅 / 越南年糕','越南方粽 / 年糕'),{rice:3,leaf:2,bean:2}]],red:.03},
 {key:'christmas',name:N('Christmas','Giáng Sinh','Natal','Natal','Navidad','Noël','Weihnachten','クリスマス','크리스마스','Natal','聖誕節','圣诞节'),materials:[
  ['pine','🌲',N('Pine Branch','Cành thông','Galho de pinheiro','Ramo de pinheiro','Rama de pino','Branche de sapin','Tannenzweig','松の枝','소나무 가지','Ranting pinus','松枝','松枝'),.15],
  ['snow','❄️',N('Snow','Tuyết','Neve','Neve','Nieve','Neige','Schnee','雪','눈','Salju','雪','雪'),.12],
  ['carrot','🥕',N('Carrot','Cà rốt','Cenoura','Cenoura','Zanahoria','Carotte','Karotte','ニンジン','당근','Wortel','胡蘿蔔','胡萝卜'),.07],
  ['ornament','⭐',N('Ornament','Đồ trang trí','Enfeite','Enfeite','Adorno','Décoration','Schmuck','オーナメント','장식','Ornamen','裝飾品','装饰品'),.04]],recipes:[
  ['tree','🎄',N('Christmas Tree','Cây thông Giáng Sinh','Árvore de Natal','Árvore de Natal','Árbol de Navidad','Sapin de Noël','Weihnachtsbaum','クリスマスツリー','크리스마스 트리','Pohon Natal','聖誕樹','圣诞树'),{pine:4,ornament:2}],
  ['snowman','☃️',N('Snowman','Người tuyết','Boneco de neve','Boneco de neve','Muñeco de nieve','Bonhomme de neige','Schneemann','雪だるま','눈사람','Manusia salju','雪人','雪人'),{snow:4,carrot:1}]]},
 {key:'mid-autumn',name:N('Mid-Autumn Festival','Tết Trung Thu','Festival do Meio do Outono','Festival do Meio do Outono','Festival del Medio Otoño','Fête de la mi-automne','Mittherbstfest','中秋節','중추절','Festival Pertengahan Musim Gugur','中秋節','中秋节'),materials:[
  ['flour','🌾',N('Flour','Bột','Farinha','Farinha','Harina','Farine','Mehl','小麦粉','밀가루','Tepung','麵粉','面粉'),.15],
  ['filling','🥮',N('Mooncake Filling','Nhân bánh','Recheio de bolo lunar','Recheio de bolo lunar','Relleno de pastel de luna','Garniture de gâteau de lune','Mondkuchenfüllung','月餅の餡','월병 소','Isian kue bulan','月餅餡','月饼馅'),.10],
  ['yolk','🥚',N('Salted Egg Yolk','Trứng muối','Gema de ovo salgada','Gema de ovo salgada','Yema de huevo salada','Jaune d’œuf salé','Gesalzenes Eigelb','塩漬け卵黄','소금에 절인 달걀노른자','Kuning telur asin','鹹蛋黃','咸蛋黄'),.05]],recipes:[['mooncake','🥮',N('Mooncake','Bánh Trung Thu','Bolo lunar','Bolo lunar','Pastel de luna','Gâteau de lune','Mondkuchen','月餅','월병','Kue bulan','月餅','月饼'),{flour:3,filling:2,yolk:1}]]},
 {key:'halloween',name:N('Halloween','Halloween','Halloween','Halloween','Halloween','Halloween','Halloween','ハロウィン','할로윈','Halloween','萬聖節','万圣节'),materials:[
  ['pumpkin','🎃',N('Pumpkin','Bí ngô','Abóbora','Abóbora','Calabaza','Citrouille','Kürbis','カボチャ','호박','Labu','南瓜','南瓜'),.14],
  ['candy','🍬',N('Candy','Kẹo','Doce','Doce','Dulce','Bonbon','Süßigkeit','キャンディ','사탕','Permen','糖果','糖果'),.11],
  ['spirit','👻',N('Spirit','Linh hồn','Espírito','Espírito','Espíritu','Esprit','Geist','霊魂','영혼','Roh','靈魂','灵魂'),.04]],recipes:[['halloween-treat','🧺',N('Halloween Treat','Giỏ quà Halloween','Cesta de Halloween','Cesto de Halloween','Cesta de Halloween','Panier d’Halloween','Halloween-Korb','ハロウィンバスケット','할로윈 바구니','Keranjang Halloween','萬聖節禮籃','万圣节礼篮'),{pumpkin:2,candy:3,spirit:1}]]},
 {key:'easter',name:N('Easter','Lễ Phục Sinh','Páscoa','Páscoa','Pascua','Pâques','Ostern','イースター','부활절','Paskah','復活節','复活节'),materials:[
  ['egg','🥚',N('Easter Egg','Trứng Phục Sinh','Ovo de Páscoa','Ovo de Páscoa','Huevo de Pascua','Œuf de Pâques','Osterei','イースターエッグ','부활절 달걀','Telur Paskah','復活節彩蛋','复活节彩蛋'),.15],
  ['ribbon','🎀',N('Ribbon','Ruy băng','Fita','Fita','Cinta','Ruban','Band','リボン','리본','Pita','緞帶','丝带'),.07]],recipes:[['basket','🧺',N('Easter Basket','Giỏ Phục Sinh','Cesta de Páscoa','Cesto de Páscoa','Cesta de Pascua','Panier de Pâques','Osterkorb','イースターバスケット','부활절 바구니','Keranjang Paskah','復活節禮籃','复活节礼篮'),{egg:4,ribbon:1}]]},
 {key:'new-year',name:N('New Year','Năm Mới','Ano Novo','Ano Novo','Año Nuevo','Nouvel An','Neujahr','新年','새해','Tahun Baru','新年','新年'),materials:[
  ['firework','🎆',N('Firework Token','Pháo hoa','Ficha de fogos','Ficha de fogo de artifício','Ficha de fuegos artificiales','Jeton de feu d’artifice','Feuerwerksmarke','花火トークン','불꽃놀이 토큰','Token kembang api','煙火代幣','烟花代币'),.12],
  ['spark','✨',N('Spark','Tia sáng','Faísca','Faísca','Chispa','Étincelle','Funke','きらめき','불꽃','Percikan','火花','火花'),.07]],recipes:[['celebration','🎇',N('New Year Celebration','Lễ mừng Năm Mới','Celebração de Ano Novo','Celebração de Ano Novo','Celebración de Año Nuevo','Célébration du Nouvel An','Neujahrsfeier','新年のお祝い','새해 축하','Perayaan Tahun Baru','新年慶典','新年庆典'),{firework:3,spark:2}]]}
];
function names(en,vi,br,pt,es,fr,de,ja,ko,id,tw,cn){return N(en,vi,br,pt,es,fr,de,ja,ko,id,tw,cn);}
async function seed(){for(const t of templates){const mats=t.materials.map(([key,emoji,name,dropRate])=>({key,emoji,name,dropRate,minQty:1,maxQty:2}));const rr=t.recipes||[t.recipe];const recipes=rr.map(([key,emoji,name,needs])=>({key,emoji,name,needs:new Map(Object.entries(needs)),boxKey:t.key}));await SeasonalEvent.updateOne({key:t.key},{$setOnInsert:{key:t.key,enabled:false,name:t.name,materials:mats,recipes,cstarMin:250,cstarMax:5000,eligibleGames:['*'],directRedEnvelopeRate:t.red||0}},{upsert:true});}}
async function active(){await seed();const now=new Date();return SeasonalEvent.find({enabled:true,startAt:{$lte:now},endAt:{$gte:now}}).lean();}
async function inventory(uid){return SeasonalInventory.findOneAndUpdate({userId:String(uid)},{$setOnInsert:{userId:String(uid)}},{upsert:true,returnDocument:'after'});}
async function rollDrop(uid,gameId){const events=await active(),drops=[];if(!events.length)return drops;const inv=await inventory(uid);for(const e of events){if(!(e.eligibleGames||['*']).includes('*')&&!e.eligibleGames.includes(gameId))continue;for(const m of e.materials||[]){if(Math.random()<m.dropRate){const q=m.minQty+Math.floor(Math.random()*(m.maxQty-m.minQty+1));inv.materials.set(`${e.key}:${m.key}`,Number(inv.materials.get(`${e.key}:${m.key}`)||0)+q);drops.push({event:e.key,key:m.key,emoji:m.emoji,qty:q,name:m.name});}}if(e.directRedEnvelopeRate&&Math.random()<e.directRedEnvelopeRate){const amount=Math.floor(e.cstarMin+Math.random()*(e.cstarMax-e.cstarMin+1));await ensureWallet(uid);await UserEconomy.updateOne(walletFilter(uid),{$inc:{cstar:amount}});drops.push({event:e.key,key:'red-envelope',emoji:'🧧',qty:1,cstar:amount});}}if(drops.length)await inv.save();return drops;}
async function craft(uid,eventKey,recipeKey){const e=await SeasonalEvent.findOne({key:eventKey,enabled:true});if(!e)throw new Error('EVENT_NOT_ACTIVE');const r=e.recipes.find(x=>x.key===recipeKey);if(!r)throw new Error('UNKNOWN_RECIPE');const inv=await inventory(uid);for(const [k,q] of r.needs.entries())if(Number(inv.materials.get(`${e.key}:${k}`)||0)<q)throw new Error('MISSING_MATERIALS');for(const [k,q] of r.needs.entries())inv.materials.set(`${e.key}:${k}`,Number(inv.materials.get(`${e.key}:${k}`)||0)-q);inv.boxes.set(e.key,Number(inv.boxes.get(e.key)||0)+1);await inv.save();return{event:e,recipe:r};}
async function openBox(uid,eventKey){const e=await SeasonalEvent.findOne({key:eventKey});const inv=await inventory(uid);if(!e||Number(inv.boxes.get(eventKey)||0)<1)throw new Error('NO_BOX');inv.boxes.set(eventKey,Number(inv.boxes.get(eventKey)||0)-1);const amount=Math.floor(e.cstarMin+Math.random()*(e.cstarMax-e.cstarMin+1));await ensureWallet(uid);await UserEconomy.updateOne(walletFilter(uid),{$inc:{cstar:amount}});await inv.save();return amount;}
module.exports={seed,active,inventory,rollDrop,craft,openBox};
