const GuildSettings=require('../models/GuildSettings');
const SeasonalEvent=require('../models/SeasonalEvent');
const State=require('../models/SeasonalAlertState');
const {tx}=require('./i18n');
function local(map,lang){if(!map)return'';if(typeof map.get==='function')return map.get(lang)||map.get('en')||'';return map[lang]||map.en||'';}
function stateOf(e,now){if(!e.enabled)return null;if(e.startAt&&now<e.startAt)return'upcoming';if((!e.startAt||now>=e.startAt)&&(!e.endAt||now<=e.endAt))return'active';if(e.endAt&&now>e.endAt)return'ended';return null;}
const words={
 active:{en:'Event started!',vi:'Sự kiện đã bắt đầu!','pt-BR':'O evento começou!','pt-PT':'O evento começou!',es:'¡El evento ha comenzado!',fr:'L’événement a commencé !',de:'Das Event hat begonnen!',ja:'イベントが開始しました！',ko:'이벤트가 시작되었습니다!',id:'Event telah dimulai!','zh-TW':'活動已開始！','zh-CN':'活动已开始！'},
 ended:{en:'Event ended.',vi:'Sự kiện đã kết thúc.','pt-BR':'O evento terminou.','pt-PT':'O evento terminou.',es:'El evento ha terminado.',fr:'L’événement est terminé.',de:'Das Event ist beendet.',ja:'イベントは終了しました。',ko:'이벤트가 종료되었습니다.',id:'Event telah berakhir.','zh-TW':'活動已結束。','zh-CN':'活动已结束。'},
 hint:{en:'Play eligible Game Hub activities to receive bonus event materials, craft event items, then exchange each crafted item for 1 Gift Box.',vi:'Chơi các hoạt động Game Hub hợp lệ để nhận thêm nguyên liệu sự kiện, chế tạo vật phẩm rồi đổi mỗi vật phẩm đã chế tạo lấy 1 Hộp Quà.','pt-BR':'Jogue atividades elegíveis do Game Hub para receber materiais extras, fabricar itens e trocar cada item fabricado por 1 Caixa de Presente.','pt-PT':'Joga atividades elegíveis do Game Hub para receber materiais extra, fabricar itens e trocar cada item fabricado por 1 Caixa de Presente.',es:'Juega actividades elegibles del Game Hub para obtener materiales extra, fabricar objetos y cambiar cada objeto fabricado por 1 Caja de Regalo.',fr:'Jouez aux activités éligibles du Game Hub pour obtenir des matériaux bonus, fabriquer des objets puis échanger chaque objet fabriqué contre 1 boîte-cadeau.',de:'Spiele geeignete Game-Hub-Aktivitäten, erhalte Bonusmaterialien, stelle Event-Gegenstände her und tausche jeden hergestellten Gegenstand gegen 1 Geschenkbox.',ja:'対象のGame Hubアクティビティを遊んでイベント素材を獲得し、アイテムを作成して、作成したアイテム1個をギフトボックス1個と交換できます。',ko:'대상 Game Hub 활동을 플레이해 이벤트 재료를 추가로 얻고 아이템을 제작한 뒤, 제작 아이템 1개를 선물 상자 1개로 교환하세요.',id:'Mainkan aktivitas Game Hub yang memenuhi syarat untuk mendapat material bonus, buat item event, lalu tukarkan setiap 1 item buatan dengan 1 Kotak Hadiah.','zh-TW':'遊玩符合資格的 Game Hub 活動以獲得額外活動材料，製作活動物品後，每 1 個成品可兌換 1 個禮物盒。','zh-CN':'游玩符合条件的 Game Hub 活动以获得额外活动材料，制作活动物品后，每 1 个成品可兑换 1 个礼物盒。'}
};
async function run(client){const now=new Date();const [events,guilds]=await Promise.all([SeasonalEvent.find({enabled:true}).lean(),GuildSettings.find({'channels.seasonalAnnouncements':{$exists:true,$ne:null}}).lean()]);for(const g of guilds){const ch=await client.channels.fetch(g.channels.seasonalAnnouncements).catch(()=>null);if(!ch?.isTextBased())continue;const lang=g.language||'en';for(const e of events){const state=stateOf(e,now);if(!state||state==='upcoming')continue;const prev=await State.findOne({guildId:g.guildId,eventKey:e.key}).lean();if(prev?.lastState===state)continue;const title=local(e.name,lang)||e.key;const body=state==='active'?`${tx(lang,words.active)}\n\n${tx(lang,words.hint)}`:tx(lang,words.ended);await ch.send(`🎊 **${title}**\n${body}`).catch(()=>{});await State.updateOne({guildId:g.guildId,eventKey:e.key},{$set:{lastState:state,lastSentAt:new Date()}},{upsert:true});}}}
function start(client){run(client).catch(e=>console.warn('Seasonal notifier:',e.message));const timer=setInterval(()=>run(client).catch(e=>console.warn('Seasonal notifier:',e.message)),5*60*1000);timer.unref?.();}
module.exports={run,start};
