const {ensureWallet,walletFilter}=require('./economyWallet');const UserEconomy=require('../models/UserEconomy');
const rounds=new Map();const WINDOW=30000,MIN=10,MAX=1000000;
async function debit(userId,amount){await ensureWallet(userId);return UserEconomy.findOneAndUpdate({...walletFilter(userId),cstar:{$gte:amount}},{$inc:{cstar:-amount}},{returnDocument:'after'});}
async function credit(userId,amount){return UserEconomy.findOneAndUpdate(walletFilter(userId),{$inc:{cstar:amount}},{returnDocument:'after'});}
function key(game,guildId){return `${game}:${guildId}`}
function symbols(){return ['deer','gourd','chicken','fish','crab','shrimp'];}
function labels(x){return {deer:'🦌 Nai',gourd:'🍐 Bầu',chicken:'🐓 Gà',fish:'🐟 Cá',crab:'🦀 Cua',shrimp:'🦐 Tôm'}[x]||x;}
async function place({game,guildId,userId,pick,bet,onResult}){bet=Number(bet);if(!Number.isInteger(bet)||bet<MIN||bet>MAX)throw Error('INVALID_BET');const wallet=await debit(userId,bet);if(!wallet)throw Error('NOT_ENOUGH_CXU');const k=key(game,guildId),now=Date.now();let r=rounds.get(k);if(!r||r.closesAt<=now){r={game,guildId,closesAt:now+WINDOW,bets:[]};rounds.set(k,r);setTimeout(()=>settle(k).catch(console.error),WINDOW+50);}r.bets.push({userId:String(userId),pick,bet,onResult});return {closesAt:r.closesAt,balance:wallet.cstar};}
async function settle(k){const r=rounds.get(k);if(!r)return;rounds.delete(k);let result;if(r.game==='baucua'){const s=symbols();result=[0,0,0].map(()=>s[Math.floor(Math.random()*s.length)]);}else{const dice=[1,2,3].map(()=>1+Math.floor(Math.random()*6)),sum=dice.reduce((a,b)=>a+b,0);result={dice,sum,pick:sum>=11?'big':'small'};}for(const b of r.bets){let returned=0,detail='';if(r.game==='baucua'){const hits=result.filter(x=>x===b.pick).length;returned=hits?b.bet*(hits+1):0;detail=`${result.map(labels).join(' • ')} • ${hits?`trúng ${hits} mặt`:'không trúng'}`;}else{const win=result.pick===b.pick;returned=win?b.bet*2:0;detail=`🎲 ${result.dice.join(' + ')} = ${result.sum} • ${result.pick==='big'?'LỚN':'NHỎ'}`;}const w=returned?await credit(b.userId,returned):await ensureWallet(b.userId);await Promise.resolve(b.onResult?.({returned,net:returned-b.bet,balance:w.cstar,detail})).catch(()=>{});}}
module.exports={place,WINDOW,labels};
