const {EmbedBuilder,ActionRowBuilder,ButtonBuilder,ButtonStyle}=require('discord.js');const T=require('../models/GameTournament');const Hub=require('../modules/gameHub');const UserEconomy=require('../models/UserEconomy');const {walletFilter,ensureWallet}=require('./economyWallet');const {mtx}=require('./i18n');
function parseDate(x){const d=new Date(String(x).trim());if(Number.isNaN(d.getTime()))throw new Error('Invalid date/time. Use ISO format, e.g. 2026-10-01T18:00:00-04:00');return d;}
async function create(o){const g=Hub.get(o.gameId);if(!g||!g.tournament)throw new Error('Game is not eligible for tournaments.');const registrationAt=parseDate(o.registrationAt),startsAt=parseDate(o.startsAt),endsAt=parseDate(o.endsAt);if(!(registrationAt<startsAt&&startsAt<endsAt))throw new Error('Required order: registration < start < end.');return T.create({name:o.name.slice(0,100),gameId:g.id,registrationAt,startsAt,endsAt,maxPlayers:Math.max(2,Math.min(1000,Number(o.maxPlayers)||32)),rewardCstar:Math.max(0,Math.floor(Number(o.rewardCstar)||0)),rules:String(o.rules||'').slice(0,1000),createdBy:o.createdBy});}
async function playerPanel(uid,lang){await tick();const rows=await T.find({status:{$in:['SCHEDULED','REGISTRATION','LIVE']}}).sort({startsAt:1}).limit(8).lean();const desc=rows.length?rows.map(x=>{const g=Hub.get(x.gameId);return `${x.status==='LIVE'?'🔴':x.status==='REGISTRATION'?'🟢':'🗓️'} **${x.name}**\n${g?.emoji||'🎮'} ${mtx(lang,g?.en||x.gameId,g?.vi||x.gameId)} • ${x.participants.length}/${x.maxPlayers}\n<t:${Math.floor(new Date(x.startsAt).getTime()/1000)}:F>`}).join('\n\n'):mtx(lang,'No scheduled tournaments right now.','Hiện chưa có giải đấu được lên lịch.');const e=new EmbedBuilder().setTitle(mtx(lang,'🏆 Tournament Center','🏆 Trung Tâm Giải Đấu')).setDescription(desc);const open=rows.find(x=>x.status==='REGISTRATION'&&!x.participants.includes(String(uid)));const comps=[];if(open)comps.push(new ActionRowBuilder().addComponents(new ButtonBuilder().setCustomId(`tour:join:${uid}:${open._id}`).setLabel(mtx(lang,`Join ${open.name}`,`Tham gia ${open.name}`).slice(0,80)).setEmoji('🏆').setStyle(ButtonStyle.Success)));comps.push(new ActionRowBuilder().addComponents(new ButtonBuilder().setCustomId(`gh:home:${uid}`).setLabel('Game Hub').setStyle(ButtonStyle.Secondary)));return{embeds:[e],components:comps};}
async function join(uid,id,lang){await tick();const t=await T.findOne({_id:id,status:'REGISTRATION'});if(!t)return{error:mtx(lang,'Registration is not open.','Đăng ký hiện không mở.')};if(t.participants.includes(String(uid)))return{error:mtx(lang,'You already joined.','Bạn đã tham gia rồi.')};if(t.participants.length>=t.maxPlayers)return{error:mtx(lang,'Tournament is full.','Giải đấu đã đủ người.')};t.participants.push(String(uid));await t.save();return playerPanel(uid,lang);}
async function submitScore(uid,gameId,score){const t=await T.findOne({gameId,status:'LIVE',participants:String(uid)}).sort({startsAt:-1});if(!t)return;const prev=Number(t.scores.get(String(uid))||0);if(score>prev){t.scores.set(String(uid),score);await t.save();}}
async function tick(){const now=new Date();await T.updateMany({status:'SCHEDULED',registrationAt:{$lte:now}},{$set:{status:'REGISTRATION'}});await T.updateMany({status:'REGISTRATION',startsAt:{$lte:now}},{$set:{status:'LIVE'}});const ending=await T.find({status:'LIVE',endsAt:{$lte:now}});for(const t of ending){const rank=[...t.scores.entries()].sort((a,b)=>b[1]-a[1]);t.winnerIds=rank.slice(0,3).map(x=>x[0]);t.status='FINISHED';await t.save();if(t.rewardCstar&&rank[0]){await ensureWallet(rank[0][0]);await UserEconomy.updateOne(walletFilter(rank[0][0]),{$inc:{cstar:t.rewardCstar}});}}}
function start(client){setInterval(()=>tick().catch(e=>console.warn('Tournament scheduler:',e.message)),60_000).unref();setTimeout(()=>tick().catch(()=>{}),5000);}
async function devPanel(){await tick();const rows=await T.find().sort({startsAt:-1}).limit(10).lean();return{embeds:[new EmbedBuilder().setTitle('🏆 Game Tournament Control').setDescription(rows.length?rows.map(x=>`${x.status==='LIVE'?'🔴':x.status==='REGISTRATION'?'🟢':x.status==='SCHEDULED'?'🗓️':'⚪'} **${x.name}** • ${x.gameId}\n<t:${Math.floor(new Date(x.startsAt).getTime()/1000)}:F> • ${x.participants.length}/${x.maxPlayers} • ${x.rewardCstar.toLocaleString()} 🌟`).join('\n\n'):'No tournaments configured.').setFooter({text:'Schedule next month in advance • automatic registration/start/end'})],components:[new ActionRowBuilder().addComponents(new ButtonBuilder().setCustomId('dev:tournament:create').setLabel('Schedule Tournament').setEmoji('📅').setStyle(ButtonStyle.Success)),new ActionRowBuilder().addComponents(new ButtonBuilder().setCustomId('dev:home').setLabel('Home').setStyle(ButtonStyle.Secondary))]};}
module.exports={create,playerPanel,join,submitScore,tick,start,devPanel};
