const {EmbedBuilder,ActionRowBuilder,ButtonBuilder,ButtonStyle,ModalBuilder,TextInputBuilder,TextInputStyle}=require('discord.js');
const Clan=require('../models/Clan'),Member=require('../models/ClanMember'),App=require('../models/ClanApplication'),Shop=require('../models/ClanShopItem'),Mission=require('../models/ClanMission'),Event=require('../models/ClanEvent'),Audit=require('../models/ClanAudit');
const CS=require('../services/clanSystem');const {guildLang,mtx}=require('../services/i18n');const {ensureWallet}=require('../services/economyWallet');
const CXU='<:cxu_coin:1551759873241251912>';const ranks={LEADER:'Hội Trưởng',DEPUTY:'Phó Hội',STRATEGIST:'Quân Sư',ELITE:'Tinh Anh',MEMBER:'Thành Viên'};
function row(owner){return new ActionRowBuilder().addComponents(
 new ButtonBuilder().setCustomId(`clanhub:members:${owner}`).setLabel('Members').setEmoji('👥').setStyle(ButtonStyle.Secondary),
 new ButtonBuilder().setCustomId(`clanhub:missions:${owner}`).setLabel('Missions').setEmoji('🎯').setStyle(ButtonStyle.Secondary),
 new ButtonBuilder().setCustomId(`clanhub:shop:${owner}`).setLabel('Shop').setEmoji('🛒').setStyle(ButtonStyle.Secondary),
 new ButtonBuilder().setCustomId(`clanhub:treasury:${owner}`).setLabel('Treasury').setEmoji('💰').setStyle(ButtonStyle.Secondary),
 new ButtonBuilder().setCustomId(`clanhub:refresh:${owner}`).setLabel('Refresh').setEmoji('🔄').setStyle(ButtonStyle.Primary));}
function row2(owner){return new ActionRowBuilder().addComponents(
 new ButtonBuilder().setCustomId(`clanhub:applications:${owner}`).setLabel('Applications').setEmoji('📩').setStyle(ButtonStyle.Secondary),
 new ButtonBuilder().setCustomId(`clanhub:events:${owner}`).setLabel('Events').setEmoji('📅').setStyle(ButtonStyle.Secondary),
 new ButtonBuilder().setCustomId(`clanhub:audit:${owner}`).setLabel('Audit').setEmoji('📜').setStyle(ButtonStyle.Secondary),
 new ButtonBuilder().setCustomId(`clanhub:deposit:${owner}`).setLabel('Deposit CXu').setEmoji('➕').setStyle(ButtonStyle.Success));}
async function home(uid,lang='en'){const x=await CS.byUser(uid);if(!x)return{embeds:[new EmbedBuilder().setColor(0x64748b).setTitle('🏰 Clan Hub').setDescription(mtx(lang,'You are not in a Clan. Use `/clan-create` or `/clan-apply`.','Bạn chưa có Clan. Dùng `/clan-create` hoặc `/clan-apply`.'))]};const [count,w]=await Promise.all([Member.countDocuments({clanId:x.clan._id}),ensureWallet(uid)]);const e=new EmbedBuilder().setColor(0x8b5cf6).setTitle(`🏰 Clan Hub • ${x.clan.name}${x.clan.tag?` [${x.clan.tag}]`:''}`).setDescription(x.clan.description||mtx(lang,'Your Clan command center. One button = one direct action.','Trung tâm điều khiển Clan. Một nút = một hành động trực tiếp.')).addFields(
{name:mtx(lang,'Clan Level','Cấp Clan'),value:`${x.clan.level} • ${x.clan.xp.toLocaleString()} XP`,inline:true},{name:mtx(lang,'Members','Thành viên'),value:`${count}/${x.clan.memberCap}`,inline:true},{name:mtx(lang,'Your Rank','Chức vụ'),value:ranks[x.member.rank]||x.member.rank,inline:true},{name:mtx(lang,'Contribution','Đóng góp'),value:x.member.contribution.toLocaleString(),inline:true},{name:'CXu Wallet',value:`${w.cstar.toLocaleString()} ${CXU}`,inline:true},{name:mtx(lang,'Clan Treasury','Quỹ Clan'),value:x.clan.settings?.showTreasury===false?'—':`${x.clan.treasury.toLocaleString()} ${CXU}`,inline:true});return{embeds:[e],components:[row(uid),row2(uid)]};}
async function view(uid,kind,lang){const x=await CS.byUser(uid);if(!x)throw new Error('NOT_IN_CLAN');let title='',lines=[];
 if(kind==='members'){title=mtx(lang,'👥 Clan Members','👥 Thành viên Clan');const a=await Member.find({clanId:x.clan._id}).sort({contribution:-1}).limit(25).lean();lines=a.map((m,n)=>`${n+1}. <@${m.userId}> • **${ranks[m.rank]||m.rank}** • ${m.contribution.toLocaleString()} contrib`);}
 if(kind==='applications'){if(!(await CS.can(uid,x.clan,'applications')))throw new Error('FORBIDDEN');title=mtx(lang,'📩 Pending Applications','📩 Đơn đang chờ');const a=await App.find({clanId:x.clan._id,status:'PENDING'}).sort({createdAt:1}).limit(20).lean();lines=a.map(v=>`• <@${v.userId}> • \`${v._id}\` • ${v.message||'—'}`);}
 if(kind==='shop'){title=mtx(lang,'🛒 Clan Shop • CXu','🛒 Cửa hàng Clan • CXu');const a=await Shop.find({clanId:x.clan._id,enabled:true}).limit(20).lean();lines=a.map(v=>`• **${v.name}** • ${v.price.toLocaleString()} ${CXU} CXu • \`${v._id}\``);}
 if(kind==='missions'){title=mtx(lang,'🎯 Clan Missions','🎯 Nhiệm vụ Clan');const a=await Mission.find({clanId:x.clan._id,enabled:true,endsAt:{$gt:new Date()}}).sort({endsAt:1}).limit(20).lean();lines=a.map(v=>`• **${v.name}** • ${v.metric} ${v.target.toLocaleString()} • +${v.rewardCurrency.toLocaleString()} ${CXU} CXu • +${v.rewardXp.toLocaleString()} XP`);}
 if(kind==='events'){title=mtx(lang,'📅 Clan Events','📅 Sự kiện Clan');const a=await Event.find({clanId:x.clan._id}).sort({startsAt:-1}).limit(20).lean();lines=a.map(v=>`• **${v.name||v.title||'Event'}** • ${v.status||'—'}`);}
 if(kind==='audit'){if(!(await CS.can(uid,x.clan,'settings')))throw new Error('FORBIDDEN');title=mtx(lang,'📜 Clan Audit','📜 Nhật ký Clan');const a=await Audit.find({clanId:x.clan._id}).sort({createdAt:-1}).limit(15).lean();lines=a.map(v=>`• <t:${Math.floor(new Date(v.createdAt).getTime()/1000)}:R> • **${v.action}** • <@${v.actorId}>`);}
 if(kind==='treasury'){title=mtx(lang,'💰 Clan Treasury • CXu','💰 Quỹ Clan • CXu');lines=[mtx(lang,`Treasury: **${x.clan.treasury.toLocaleString()} ${CXU} CXu**\nUse **Deposit CXu** or \`/clan-deposit\`. Authorized officers can use \`/clan-withdraw\`.`,`Quỹ hiện có: **${x.clan.treasury.toLocaleString()} ${CXU} CXu**\nDùng **Deposit CXu** hoặc \`/clan-deposit\`. Người có quyền có thể dùng \`/clan-withdraw\`.`)];}
 return{embeds:[new EmbedBuilder().setColor(0x8b5cf6).setTitle(title).setDescription(lines.length?lines.join('\n').slice(0,4000):mtx(lang,'Nothing here yet.','Chưa có dữ liệu.'))],components:[new ActionRowBuilder().addComponents(new ButtonBuilder().setCustomId(`clanhub:home:${uid}`).setLabel('Clan Hub').setEmoji('🏰').setStyle(ButtonStyle.Primary))]};}
function depositModal(owner){return new ModalBuilder().setCustomId(`clanhub:deposit-submit:${owner}`).setTitle('Deposit CXu to Clan').addComponents(new ActionRowBuilder().addComponents(new TextInputBuilder().setCustomId('amount').setLabel('CXu amount').setStyle(TextInputStyle.Short).setRequired(true).setPlaceholder('1000')));}
async function handle(i,lang){const p=i.customId.split(':'),action=p[1],owner=p[2];if(owner&&i.user.id!==owner)return i.reply({content:mtx(lang,'This Clan Hub belongs to another member. Open your own with `/clan-hub`.','Clan Hub này thuộc thành viên khác. Hãy mở bảng của bạn bằng `/clan-hub`.'),flags:64});try{if(action==='deposit'&&i.isButton())return i.showModal(depositModal(owner));if(action==='deposit-submit'&&i.isModalSubmit()){const amount=Number(i.fields.getTextInputValue('amount').replace(/,/g,''));const r=await CS.depositCXU(i.user.id,amount);return i.reply({content:`✅ +${r.amount.toLocaleString()} ${CXU} CXu → Clan Treasury • ${r.clan.treasury.toLocaleString()} CXu`,flags:64});}if(action==='home'||action==='refresh')return i.update(await home(i.user.id,lang));return i.update(await view(i.user.id,action,lang));}catch(e){return i.reply({content:`❌ ${e.message}`,flags:64}).catch(()=>i.followUp({content:`❌ ${e.message}`,flags:64}));}}
module.exports={home,view,handle,depositModal};
