const {EmbedBuilder,ActionRowBuilder,ButtonBuilder,ButtonStyle,ModalBuilder,TextInputBuilder,TextInputStyle}=require('discord.js');
const Clan=require('../models/Clan'),Member=require('../models/ClanMember'),App=require('../models/ClanApplication');
const CS=require('../services/clanSystem');const {mtx}=require('../services/i18n');const {ensureWallet}=require('../services/economyWallet');const {rankForPoints,nextRank}=require('../config/clanRanks');
const CXU='<:cxu_coin:1551759873241251912>';const roles={LEADER:'👑 Hội Trưởng',DEPUTY:'🛡️ Phó Hội',STRATEGIST:'📋 Quân Sư',ELITE:'⭐ Tinh Anh',MEMBER:'👤 Thành Viên'};
function bar(value,max,size=14){if(!max)return '█'.repeat(size);const n=Math.max(0,Math.min(size,Math.round(value/max*size)));return `${'█'.repeat(n)}${'░'.repeat(size-n)}`;}
function back(owner){return new ActionRowBuilder().addComponents(new ButtonBuilder().setCustomId(`clanhub:home:${owner}`).setLabel('Clan Hub').setEmoji('🏰').setStyle(ButtonStyle.Primary));}
function guestRows(owner){return [new ActionRowBuilder().addComponents(new ButtonBuilder().setCustomId(`clanhub:create:${owner}`).setLabel('Đăng ký Clan').setEmoji('➕').setStyle(ButtonStyle.Success),new ButtonBuilder().setCustomId(`clanhub:apply:${owner}`).setLabel('Tìm / Tham gia').setEmoji('🔎').setStyle(ButtonStyle.Primary),new ButtonBuilder().setCustomId(`clanhub:myapps:${owner}`).setLabel('Đơn đã gửi').setEmoji('📨').setStyle(ButtonStyle.Secondary))];}
function memberRows(owner,isOwner,canManage){const main=[new ButtonBuilder().setCustomId(`clanhub:contribute:${owner}`).setLabel('Cống hiến CXu').setEmoji('💠').setStyle(ButtonStyle.Success),new ButtonBuilder().setCustomId(`clanhub:members:${owner}`).setLabel('Thành viên').setEmoji('👥').setStyle(ButtonStyle.Primary)];if(canManage)main.push(new ButtonBuilder().setCustomId(`clanhub:applications:${owner}`).setLabel('Đơn gia nhập').setEmoji('📥').setStyle(ButtonStyle.Secondary));main.push(new ButtonBuilder().setCustomId(`clanhub:refresh:${owner}`).setLabel('Làm mới').setEmoji('🔄').setStyle(ButtonStyle.Secondary));const rows=[new ActionRowBuilder().addComponents(main)];
 const admin=[];if(canManage)admin.push(new ButtonBuilder().setCustomId(`clanhub:manage:${owner}`).setLabel('Quản lý').setEmoji('🛡️').setStyle(ButtonStyle.Secondary));if(!isOwner)admin.push(new ButtonBuilder().setCustomId(`clanhub:leave:${owner}`).setLabel('Rời Clan').setEmoji('🚪').setStyle(ButtonStyle.Danger));if(isOwner)admin.push(new ButtonBuilder().setCustomId(`clanhub:disband:${owner}`).setLabel('Giải tán Clan').setEmoji('🗑️').setStyle(ButtonStyle.Danger));if(admin.length)rows.push(new ActionRowBuilder().addComponents(admin));return rows;}
async function home(uid,lang='en'){const x=await CS.byUser(uid);if(!x){const pending=await App.countDocuments({userId:String(uid),status:'PENDING'});return{embeds:[new EmbedBuilder().setColor(0x64748b).setTitle('🏰 CLAN HUB • COMMUNITY').setDescription(mtx(lang,'You are not in a Clan yet. Register your own group or find a community to join.','Bạn chưa tham gia Clan. Hãy đăng ký hội nhóm riêng hoặc tìm một cộng đồng để tham gia.')).addFields({name:mtx(lang,'Quick start','Bắt đầu nhanh'),value:mtx(lang,'Use the buttons below — no command memorization required.','Dùng nút bên dưới để thao tác ngay — không cần nhớ lệnh.'),inline:false},{name:mtx(lang,'Pending applications','Đơn đang chờ'),value:String(pending),inline:true})],components:guestRows(uid)};}
 const [count,w,canManage]=await Promise.all([Member.countDocuments({clanId:x.clan._id}),ensureWallet(uid),CS.can(uid,x.clan,'members')]);const rank=rankForPoints(x.clan.clanPoints||0),next=nextRank(rank.key),points=Math.max(0,x.clan.clanPoints||0);const progress=next?Math.max(0,points-rank.minPoints):points;const need=next?next.minPoints-rank.minPoints:0;const e=new EmbedBuilder().setColor(rank.color).setTitle(`${rank.emoji} ${x.clan.name}${x.clan.tag?` • [${x.clan.tag}]`:''}`).setDescription(`${x.clan.description||mtx(lang,'A Corgi-Bot community Clan.','Một Clan cộng đồng trên Corgi-Bot.')}

**${rank.name}**  •  ${next?`${bar(progress,need)} ${points.toLocaleString()} / ${next.minPoints.toLocaleString()} CP`:`${bar(1,1)} MAX RANK • ${points.toLocaleString()} CP`}`).addFields({name:mtx(lang,'🏆 Clan Rank','🏆 Cấp bậc Clan'),value:`**${rank.name}**${next?` → ${next.name}`:' • MAX'}`,inline:true},{name:mtx(lang,'👥 Members','👥 Thành viên'),value:`${count}/${x.clan.memberCap}`,inline:true},{name:mtx(lang,'🪪 Your role','🪪 Chức vụ'),value:roles[x.member.rank]||x.member.rank,inline:true},{name:mtx(lang,'💠 Your contribution','💠 Cống hiến của bạn'),value:`${(x.member.contribution||0).toLocaleString()} CP`,inline:true},{name:'⭐ CXu Wallet',value:`${w.cstar.toLocaleString()} ${CXU}`,inline:true},{name:mtx(lang,'⚡ Rank progression','⚡ Tiến trình cấp bậc'),value:next?mtx(lang,`${(next.minPoints-points).toLocaleString()} Clan Points until ${next.name}. 1 contributed CXu = 1 Clan Point.`, `Còn **${(next.minPoints-points).toLocaleString()} Điểm Clan** để lên **${next.name}**. 1 CXu cống hiến = 1 Điểm Clan.`):mtx(lang,'Maximum Clan rank reached.','Clan đã đạt cấp bậc tối đa.'),inline:false});return{embeds:[e],components:memberRows(uid,String(x.clan.ownerId)===String(uid),canManage)};}
async function view(uid,kind,lang='en'){if(kind==='myapps'){const rows=await App.find({userId:String(uid)}).sort({createdAt:-1}).limit(15).lean();const clans=await Clan.find({_id:{$in:rows.map(r=>r.clanId)}}).lean();const map=new Map(clans.map(c=>[String(c._id),c]));return{embeds:[new EmbedBuilder().setColor(0x64748b).setTitle('📨 '+mtx(lang,'My Clan Applications','Đơn Clan đã gửi')).setDescription(rows.length?rows.map(r=>`• **${map.get(String(r.clanId))?.name||'Clan'}** • ${r.status} • <t:${Math.floor(new Date(r.createdAt).getTime()/1000)}:R>`).join('\n'):mtx(lang,'No applications yet.','Bạn chưa gửi đơn nào.'))],components:guestRows(uid)};}
 const x=await CS.byUser(uid);if(!x)throw new Error('NOT_IN_CLAN');const rank=rankForPoints(x.clan.clanPoints||0);if(kind==='members'){const a=await Member.find({clanId:x.clan._id}).sort({contribution:-1}).limit(25).lean();return{embeds:[new EmbedBuilder().setColor(rank.color).setTitle('👥 '+mtx(lang,'Clan Members','Thành viên Clan')).setDescription(a.map((m,n)=>`${n+1}. <@${m.userId}> • **${roles[m.rank]||m.rank}** • 💠 ${(m.contribution||0).toLocaleString()} CP`).join('\n')||'—')],components:[back(uid)]};}
 if(kind==='applications'){if(!(await CS.can(uid,x.clan,'applications')))throw new Error('FORBIDDEN');const a=await App.find({clanId:x.clan._id,status:'PENDING'}).sort({createdAt:1}).limit(10).lean();const components=[back(uid)];for(const app of a.slice(0,4))components.push(new ActionRowBuilder().addComponents(new ButtonBuilder().setCustomId(`clanhub:approve:${uid}:${app._id}`).setLabel(`Duyệt ${String(app.userId).slice(-4)}`).setEmoji('✅').setStyle(ButtonStyle.Success),new ButtonBuilder().setCustomId(`clanhub:decline:${uid}:${app._id}`).setLabel(`Từ chối ${String(app.userId).slice(-4)}`).setEmoji('❌').setStyle(ButtonStyle.Danger)));return{embeds:[new EmbedBuilder().setColor(rank.color).setTitle('📥 '+mtx(lang,'Join Applications','Đơn xin gia nhập')).setDescription(a.length?a.map(v=>`• <@${v.userId}> • ${v.message||'—'}\n  ID: \`${v._id}\``).join('\n'):mtx(lang,'No pending applications.','Không có đơn đang chờ.'))],components};}
 if(kind==='manage')return{embeds:[new EmbedBuilder().setColor(rank.color).setTitle('🛡️ '+mtx(lang,'Clan Management','Quản lý Clan')).setDescription(mtx(lang,'Use **Applications** to approve/decline requests directly. Member roles, kick, ownership transfer and profile management are available through `/clan-manage`. The Owner alone can disband the Clan.','Dùng **Đơn gia nhập** để duyệt/từ chối trực tiếp. Phân quyền thành viên, kick, chuyển Hội Trưởng và quản lý hồ sơ dùng `/clan-manage`. Chỉ Hội Trưởng được giải tán Clan.'))],components:[back(uid)]};
 return home(uid,lang);}
function modal(id,title,fields){const m=new ModalBuilder().setCustomId(id).setTitle(title);for(const f of fields)m.addComponents(new ActionRowBuilder().addComponents(new TextInputBuilder().setCustomId(f.id).setLabel(f.label).setStyle(f.long?TextInputStyle.Paragraph:TextInputStyle.Short).setRequired(f.required!==false).setMaxLength(f.max||100).setPlaceholder(f.placeholder||'')));return m;}
async function handle(i,lang){const p=i.customId.split(':'),action=p[1],owner=p[2];if(owner&&i.user.id!==owner)return i.reply({content:mtx(lang,'This Clan Hub belongs to another member. Open your own with `/clan`.','Clan Hub này thuộc người khác. Hãy mở Hub của bạn bằng `/clan`.'),flags:64});try{
 if(action==='create'&&i.isButton())return i.showModal(modal(`clanhub:create-submit:${owner}`,'Đăng ký Clan',[{id:'name',label:'Tên Clan',max:60},{id:'tag',label:'Tag Clan (tối đa 8 ký tự)',required:false,max:8},{id:'description',label:'Mô tả Clan',required:false,max:500,long:true}]));
 if(action==='apply'&&i.isButton())return i.showModal(modal(`clanhub:apply-submit:${owner}`,'Tìm / Tham gia Clan',[{id:'name',label:'Tên hoặc Tag Clan',max:60},{id:'message',label:'Lời nhắn xin gia nhập',required:false,max:500,long:true}]));
 if(action==='contribute'&&i.isButton())return i.showModal(modal(`clanhub:contribute-submit:${owner}`,'Cống hiến CXu',[{id:'amount',label:'Số CXu muốn cống hiến',max:20,placeholder:'1000'}]));
 if(action==='disband'&&i.isButton()){const x=await CS.byUser(i.user.id);if(!x||String(x.clan.ownerId)!==String(i.user.id))throw new Error('OWNER_ONLY');return i.showModal(modal(`clanhub:disband-submit:${owner}`,'⚠️ Giải tán Clan',[{id:'name',label:'Nhập chính xác tên Clan để xác nhận',max:60,placeholder:x.clan.name}]));}
 if(action==='leave'&&i.isButton()){await CS.leave(i.user.id);return i.update(await home(i.user.id,lang));}
 if(action==='create-submit'&&i.isModalSubmit()){await CS.create({ownerGuildId:i.guildId,ownerId:i.user.id,name:i.fields.getTextInputValue('name'),tag:i.fields.getTextInputValue('tag'),description:i.fields.getTextInputValue('description')});return i.reply({...await home(i.user.id,lang),flags:64});}
 if(action==='apply-submit'&&i.isModalSubmit()){const clan=await CS.findClan(i.fields.getTextInputValue('name'));if(!clan)throw new Error('CLAN_NOT_FOUND');await CS.apply(clan._id,i.user.id,i.fields.getTextInputValue('message'));return i.reply({content:`✅ ${mtx(lang,'Application sent to','Đã gửi đơn tới')} **${clan.name}**.`,flags:64});}
 if(action==='contribute-submit'&&i.isModalSubmit()){const amount=Number(i.fields.getTextInputValue('amount').replace(/[,. ]/g,''));const r=await CS.contributeCXU(i.user.id,amount);return i.reply({content:`✅ **${r.amount.toLocaleString()} CXu** → **${r.amount.toLocaleString()} Clan Points**${r.rankUp?`\n🎉 **RANK UP: ${r.fromRank.name} → ${r.toRank.name}!**`:''}`,flags:64});}
 if(action==='disband-submit'&&i.isModalSubmit()){const old=await CS.disband(i.user.id,i.fields.getTextInputValue('name'));return i.reply({content:`🗑️ Clan **${old.name}** ${mtx(lang,'has been permanently disbanded.','đã được giải tán và xóa khỏi hệ thống.')}`,flags:64});}
 if((action==='approve'||action==='decline')&&i.isButton()){const x=await CS.byUser(i.user.id);if(!x)throw new Error('NOT_IN_CLAN');await CS.reviewApplication(x.clan,p[3],i.user.id,action==='approve'?'APPROVED':'DECLINED');return i.update(await view(i.user.id,'applications',lang));}
 if(action==='home'||action==='refresh')return i.update(await home(i.user.id,lang));return i.update(await view(i.user.id,action,lang));
 }catch(e){const payload={content:`❌ ${e.message}`,flags:64};if(i.replied||i.deferred)return i.followUp(payload);return i.reply(payload);}}
module.exports={home,view,handle};
