const {EmbedBuilder,ActionRowBuilder,ButtonBuilder,ButtonStyle,AttachmentBuilder}=require('discord.js');
const path=require('path');
const CreatureProfile=require('../models/CreatureProfile');
const S=require('../services/creatureService');
const C=require('../services/creatureCatalog');
const {mtx}=require('../services/i18n');
const rarityEmoji={COMMON:'⚪',UNCOMMON:'🟢',RARE:'🔵',EPIC:'🟣',LEGENDARY:'🟠',MYTHIC:'🔴',CELESTIAL:'🌌',SECRET:'👑'};
const elementEmoji={NORMAL:'⚪',FIRE:'🔥',WATER:'💧',NATURE:'🌿',LIGHT:'✨',DARK:'🌑',ICE:'❄️',ELECTRIC:'⚡'};
const ui=n=>path.join(__dirname,'../../assets/creature-hunt/ui',n);
function ownedLine(p,o){const x=C.byId(o.petId);return x?`${rarityEmoji[x.rarity]} **${x.name}** • ${elementEmoji[x.element]} ${x.element} • Lv.${o.level} • ×${o.copies}`:'';}
async function home(uid,lang){const p=await S.profile(uid),team=S.teamPets(p);const e=new EmbedBuilder().setColor(0x7c5cff).setTitle('🐾 Corgi Creature Hunt').setDescription(mtx(lang,'Hunt creatures, capture them, build a team of 3 and challenge other players.','Săn sinh vật, thu phục, lập đội 3 Pet và thách đấu người chơi khác.')).addFields({name:mtx(lang,'Collection','Bộ sưu tập'),value:`**${p.pets.length}/64** • ${mtx(lang,'Captures','Thu phục')}: **${p.hunt.captures}**`,inline:true},{name:'Orbs',value:`🔵 ${p.orbs.basic} • 🟣 ${p.orbs.great} • 🔴 ${p.orbs.ultra} • 🌌 ${p.orbs.celestial} • 👑 ${p.orbs.secret}`,inline:true},{name:mtx(lang,'PvP','PvP'),value:`🏆 ${p.pvp.wins}W / ${p.pvp.losses}L • ${p.pvp.rating} RP`,inline:true},{name:mtx(lang,'Team','Đội hình'),value:team.length?team.map((x,i)=>`${i+1}. ${rarityEmoji[x.pet.rarity]} ${x.pet.name} Lv.${x.own.level}`).join('\n'):mtx(lang,'No team yet. Use `/team`.','Chưa có đội. Dùng `/team`.'),inline:false}).setFooter({text:'Creature Hunt V1 • 64 Creatures'});return{embeds:[e]};}
async function huntView(uid,lang){const r=await S.hunt(uid);if(r.cooldown)return{content:mtx(lang,`⏳ Hunt again in ${Math.ceil(r.cooldown/1000)}s.`,`⏳ Có thể săn tiếp sau ${Math.ceil(r.cooldown/1000)} giây.`),flags:64};const p=r.pet;const file=new AttachmentBuilder(p.asset,{name:path.basename(p.asset)});const e=new EmbedBuilder().setColor(0x5865f2).setTitle(mtx(lang,'🐾 Wild Creature Appeared!','🐾 Sinh vật hoang dã xuất hiện!')).setDescription(`${rarityEmoji[p.rarity]} **${p.name}**\n${elementEmoji[p.element]} ${p.element} • **${p.rarity}**\n\n${mtx(lang,'Choose one Capture Orb. The encounter expires in 2 minutes.','Chọn một Capture Orb. Cuộc gặp hết hạn sau 2 phút.')}`).setThumbnail(`attachment://${path.basename(p.asset)}`);const row=new ActionRowBuilder().addComponents(new ButtonBuilder().setCustomId(`ch:cap:basic:${uid}`).setLabel('Basic').setEmoji('🔵').setStyle(ButtonStyle.Secondary),new ButtonBuilder().setCustomId(`ch:cap:great:${uid}`).setLabel('Great').setEmoji('🟣').setStyle(ButtonStyle.Primary),new ButtonBuilder().setCustomId(`ch:cap:ultra:${uid}`).setLabel('Ultra').setEmoji('🔴').setStyle(ButtonStyle.Primary),new ButtonBuilder().setCustomId(`ch:cap:celestial:${uid}`).setLabel('Celestial').setEmoji('🌌').setStyle(ButtonStyle.Success),new ButtonBuilder().setCustomId(`ch:cap:secret:${uid}`).setLabel('Secret').setEmoji('👑').setStyle(ButtonStyle.Danger));return{embeds:[e],components:[row],files:[file]};}
async function collection(uid,lang,page=1){const p=await S.profile(uid),rows=[...p.pets].sort((a,b)=>C.RARITIES.indexOf(C.byId(b.petId)?.rarity)-C.RARITIES.indexOf(C.byId(a.petId)?.rarity));const pages=Math.max(1,Math.ceil(rows.length/10));page=Math.max(1,Math.min(pages,page));const body=rows.slice((page-1)*10,page*10).map((o,i)=>`**${(page-1)*10+i+1}.** ${ownedLine(p,o)}`).join('\n')||mtx(lang,'No creatures captured yet. Use `/hunt`.','Chưa thu phục Pet nào. Dùng `/hunt`.');return{embeds:[new EmbedBuilder().setColor(0x57f287).setTitle(`📖 ${mtx(lang,'Creature Collection','Bộ sưu tập Pet')} • ${p.pets.length}/64`).setDescription(body).setFooter({text:`Page ${page}/${pages} • /team slot:<1-3> pet:<number>`})]};}
async function handle(i,lang){const parts=i.customId.split(':');if(parts[1]==='cap'){const orb=parts[2],owner=parts[3];if(i.user.id!==owner)return i.reply({content:mtx(lang,'This encounter belongs to another player.','Cuộc săn này thuộc người chơi khác.'),flags:64});try{const r=await S.capture(owner,orb);const art=r.success?'capture-success.png':'capture-failed.png',file=new AttachmentBuilder(ui(art),{name:art});const e=new EmbedBuilder().setColor(r.success?0x57f287:0xed4245).setTitle(r.success?mtx(lang,'✨ Capture Success!','✨ Thu phục thành công!'):mtx(lang,'💥 Capture Failed','💥 Thu phục thất bại')).setDescription(`${rarityEmoji[r.pet.rarity]} **${r.pet.name}** • ${elementEmoji[r.pet.element]} ${r.pet.element}\n${mtx(lang,'Capture chance','Tỷ lệ thu phục')}: **${(r.chance*100).toFixed(1)}%**\n${r.success?mtx(lang,'Added to your global Collection.','Đã thêm vào Bộ sưu tập Global.'):mtx(lang,'The creature escaped. Hunt again after the cooldown.','Pet đã trốn thoát. Hãy săn lại sau cooldown.')}`).setImage(`attachment://${art}`);return i.update({embeds:[e],components:[],files:[file],attachments:[]});}catch(e){const msg=e.message==='NO_ORB'?mtx(lang,'❌ You do not have that Orb.','❌ Bạn không có Orb này.'):mtx(lang,'❌ This encounter expired or was already resolved.','❌ Cuộc săn đã hết hạn hoặc đã kết thúc.');return i.reply({content:msg,flags:64});}}
 if(parts[1]==='pvp'){const action=parts[2],challenger=parts[3],target=parts[4];if(i.user.id!==target)return i.reply({content:mtx(lang,'Only the challenged player can respond.','Chỉ người bị thách đấu mới có thể phản hồi.'),flags:64});if(action==='decline')return i.update({content:mtx(lang,'❌ PvP challenge declined.','❌ Đã từ chối thách đấu PvP.'),embeds:[],components:[]});const [a,b]=await Promise.all([S.profile(challenger),S.profile(target)]);try{const d=S.duel(a,b),win=d.winner==='A'?a:b,lose=d.winner==='A'?b:a;win.pvp.wins++;win.pvp.seasonWins++;win.pvp.rating+=20;lose.pvp.losses++;lose.pvp.seasonLosses++;lose.pvp.rating=Math.max(0,lose.pvp.rating-15);await Promise.all([win.save(),lose.save()]);const winnerId=d.winner==='A'?challenger:target;return i.update({embeds:[new EmbedBuilder().setColor(0xf1c40f).setTitle('⚔️ Pet PvP • Result').setDescription(d.log.join('\n')).addFields({name:'🏆 Winner',value:`<@${winnerId}>`,inline:true},{name:'Rounds',value:String(d.rounds),inline:true})],components:[]});}catch(e){return i.reply({content:mtx(lang,'❌ Both players need a 1–3 Pet team first. Use `/team`.','❌ Cả hai người chơi cần đội 1–3 Pet trước. Dùng `/team`.'),flags:64});}}
}
module.exports={home,huntView,collection,handle};
