const {EmbedBuilder,ActionRowBuilder,ButtonBuilder,ButtonStyle,StringSelectMenuBuilder}=require('discord.js');
const FarmProfile=require('../models/FarmProfile');const {mtx}=require('../services/i18n');
const CROPS={wheat:{emoji:'🌾',en:'Wheat',vi:'Lúa mì',sec:60,seed:3,xp:4},corn:{emoji:'🌽',en:'Corn',vi:'Ngô',sec:180,seed:7,xp:8},carrot:{emoji:'🥕',en:'Carrot',vi:'Cà rốt',sec:420,seed:14,xp:14},soy:{emoji:'🫘',en:'Soybean',vi:'Đậu nành',sec:900,seed:25,xp:24}};
const need=l=>80+Math.floor(l*35);const num=(m,k)=>Number(m?.get?.(k)||0);const add=(m,k,v)=>m.set(k,Math.max(0,num(m,k)+v));
async function profile(uid){return FarmProfile.findOneAndUpdate({userId:String(uid)},{$setOnInsert:{userId:String(uid)}},{upsert:true,returnDocument:'after',setDefaultsOnInsert:true});}
function cap(p,type){return(type==='silo'?p.siloLevel:p.barnLevel)*60;}function used(m){let n=0;for(const v of m.values())n+=Number(v||0);return n;}
function cropUnlocked(p,id){return{id:1,wheat:1,corn:2,carrot:5,soy:9}[id]<=p.level;}
function objective(p,lang){if(p.tutorialStep===0)return mtx(lang,'Plant your first Wheat plot.','Gieo ô Lúa mì đầu tiên.');if(p.tutorialStep===1)return mtx(lang,'Wait for Wheat to grow, then Harvest.','Chờ Lúa mì lớn rồi Thu hoạch.');if(p.tutorialStep===2)return mtx(lang,'Use the Feed Mill to make animal feed.','Dùng Máy thức ăn để chế biến thức ăn chăn nuôi.');if(p.tutorialStep===3)return mtx(lang,'Collect eggs from your chickens.','Thu trứng từ đàn gà.');return mtx(lang,'Grow, process and complete orders to expand your farm.','Trồng, chế biến và hoàn thành đơn để mở rộng nông trại.');}
function rows(uid,p,lang){return[new ActionRowBuilder().addComponents(
 new ButtonBuilder().setCustomId(`farm:plant:${uid}`).setLabel(mtx(lang,'Plant','Gieo hạt')).setEmoji('🌱').setStyle(ButtonStyle.Success),new ButtonBuilder().setCustomId(`farm:harvest:${uid}`).setLabel(mtx(lang,'Harvest','Thu hoạch')).setEmoji('🌾').setStyle(ButtonStyle.Primary),new ButtonBuilder().setCustomId(`farm:animals:${uid}`).setLabel(mtx(lang,'Animals','Vật nuôi')).setEmoji('🐔').setStyle(ButtonStyle.Secondary),new ButtonBuilder().setCustomId(`farm:process:${uid}`).setLabel(mtx(lang,'Process','Chế biến')).setEmoji('⚙️').setStyle(ButtonStyle.Secondary)),new ActionRowBuilder().addComponents(
 new ButtonBuilder().setCustomId(`farm:orders:${uid}`).setLabel(mtx(lang,'Orders','Đơn hàng')).setEmoji('📦').setStyle(ButtonStyle.Primary),new ButtonBuilder().setCustomId(`farm:shop:${uid}`).setLabel(mtx(lang,'Seed Shop','Cửa hàng giống')).setEmoji('🛒').setStyle(ButtonStyle.Success),new ButtonBuilder().setCustomId(`farm:expand:${uid}`).setLabel(mtx(lang,'Expand','Mở rộng')).setEmoji('🏡').setStyle(ButtonStyle.Secondary),new ButtonBuilder().setCustomId(`farm:guide:${uid}`).setLabel(mtx(lang,'Guide','Hướng dẫn')).setEmoji('❓').setStyle(ButtonStyle.Secondary))];}
function view(p,lang,msg=''){const now=Date.now();const plots=p.plots.map(x=>{if(!x.crop)return`▫️ #${x.slot} Empty`;const c=CROPS[x.crop],left=Math.max(0,Math.ceil((new Date(x.readyAt)-now)/1000));return`${left?`🌱`:`✅`} #${x.slot} ${c.emoji} ${mtx(lang,c.en,c.vi)} ${left?`${left}s`:mtx(lang,'Ready','Sẵn sàng')}`;}).join('\n');const e=new EmbedBuilder().setColor(0x7CB342).setTitle('🌾 Corgi Farm').setDescription(`${mtx(lang,'Build a living farm: seed → grow → harvest → process → order → expand.','Xây nông trại sống động: giống → trồng → thu hoạch → chế biến → đơn hàng → mở rộng.')}${msg?`\n\n${msg}`:''}`).addFields({name:'🎯 '+mtx(lang,'Next Objective','Mục tiêu tiếp theo'),value:objective(p,lang)},{name:'🚜 '+mtx(lang,'Farm','Nông trại'),value:`Lv. **${p.level}** • XP ${p.xp}/${need(p.level)} • 🪙 **${p.coins}**\n${plots}`},{name:'🌱 '+mtx(lang,'Seeds / Silo','Giống / Silo'),value:`🌾 ${num(p.seeds,'wheat')} • 🌽 ${num(p.seeds,'corn')} • 🥕 ${num(p.seeds,'carrot')} • 🫘 ${num(p.seeds,'soy')}\n${mtx(lang,'Crops','Nông sản')}: ${used(p.crops)}/${cap(p,'silo')}`},{name:'🏚️ '+mtx(lang,'Storage','Kho'),value:`Barn ${used(p.goods)}/${cap(p,'barn')} • Feed ${p.feed}\n🐔 ${p.animals.find(x=>x.type==='chicken')?.count||0} • 🥚 ${num(p.goods,'egg')} • 🍞 ${num(p.goods,'bread')}`}).setFooter({text:mtx(lang,'Farm progress is permanent • No seasonal reset','Tiến trình nông trại vĩnh viễn • Không reset mùa')});return{embeds:[e],components:rows(p.userId,p,lang)};}
async function home(uid,lang){return view(await profile(uid),lang);}async function level(p,x){p.xp+=x;while(p.xp>=need(p.level)){p.xp-=need(p.level);p.level++;}}
async function plantMenu(i,p,lang){const free=p.plots.filter(x=>!x.crop).length;if(!free)return i.reply({content:mtx(lang,'All plots are occupied.','Tất cả ô đất đang được sử dụng.'),flags:64});const opts=Object.entries(CROPS).filter(([id])=>cropUnlocked(p,id)&&num(p.seeds,id)>0).map(([id,c])=>({label:mtx(lang,c.en,c.vi),value:id,emoji:c.emoji,description:`${num(p.seeds,id)} seeds • ${c.sec}s`}));if(!opts.length)return i.reply({content:mtx(lang,'No usable seeds. Visit Seed Shop.','Không còn giống có thể gieo. Hãy vào Cửa hàng giống.'),flags:64});return i.reply({content:mtx(lang,'Choose a crop for the next empty plot.','Chọn cây cho ô đất trống tiếp theo.'),components:[new ActionRowBuilder().addComponents(new StringSelectMenuBuilder().setCustomId(`farmcrop:${p.userId}`).setPlaceholder(mtx(lang,'Choose seed','Chọn giống')).addOptions(opts))],flags:64});}
async function selectCrop(i,lang){const owner=i.customId.split(':')[1];if(i.user.id!==owner)return i.reply({content:'❌',flags:64});const p=await profile(owner),id=i.values[0],c=CROPS[id],plot=p.plots.find(x=>!x.crop);if(!plot||!c||num(p.seeds,id)<1)return i.update({content:mtx(lang,'Planting conditions changed. Reopen Farm.','Điều kiện gieo trồng đã thay đổi. Hãy mở lại Farm.'),components:[]});add(p.seeds,id,-1);plot.crop=id;plot.plantedAt=new Date();plot.readyAt=new Date(Date.now()+c.sec*1000);if(p.tutorialStep===0)p.tutorialStep=1;await p.save();return i.update({content:`${c.emoji} ${mtx(lang,'Planted','Đã gieo')} **${mtx(lang,c.en,c.vi)}** #${plot.slot}.`,components:[]});}
async function harvest(p,lang){let q=0,xp=0;for(const plot of p.plots){if(plot.crop&&new Date(plot.readyAt)<=new Date()){const c=CROPS[plot.crop],gain=2+Math.floor(Math.random()*2);if(used(p.crops)+gain<=cap(p,'silo')){add(p.crops,plot.crop,gain);add(p.seeds,plot.crop,1);q+=gain;xp+=c.xp;plot.crop=null;plot.plantedAt=null;plot.readyAt=null;}}}if(!q)return view(p,lang,'⏳ '+mtx(lang,'No crop is ready, or your Silo is full.','Chưa có cây sẵn sàng, hoặc Silo đã đầy.'));p.harvested+=q;if(p.tutorialStep===1)p.tutorialStep=2;await level(p,xp);await p.save();return view(p,lang,`🌾 ${mtx(lang,'Harvested','Đã thu hoạch')} **${q}** • +${xp} XP`);}
async function animals(p,lang){const a=p.animals.find(x=>x.type==='chicken');if(!a?.count)return view(p,lang,'🐔 '+mtx(lang,'No chickens yet.','Chưa có gà.'));if(p.feed<1)return view(p,lang,'🌾 '+mtx(lang,'Need animal feed. Process crops first.','Cần thức ăn chăn nuôi. Hãy chế biến nông sản trước.'));const cd=5*60*1000;if(a.lastCollectedAt&&Date.now()-new Date(a.lastCollectedAt)<cd)return view(p,lang,'🐔 '+mtx(lang,'The chickens are not ready yet.','Đàn gà chưa sẵn sàng.'));if(used(p.goods)+a.count>cap(p,'barn'))return view(p,lang,'🏚️ '+mtx(lang,'Barn is full.','Barn đã đầy.'));p.feed--;add(p.goods,'egg',a.count);a.lastCollectedAt=new Date();if(p.tutorialStep===3)p.tutorialStep=4;await level(p,8);await p.save();return view(p,lang,`🥚 +**${a.count} ${mtx(lang,'Eggs','Trứng')}**`);}
async function process(p,lang){if(num(p.crops,'wheat')>=3){add(p.crops,'wheat',-3);p.feed+=2;if(p.tutorialStep===2)p.tutorialStep=3;await level(p,6);await p.save();return view(p,lang,'⚙️ 🌾 ×3 → **Feed ×2**');}if(num(p.goods,'egg')>=2&&num(p.crops,'wheat')>=2){add(p.goods,'egg',-2);add(p.crops,'wheat',-2);add(p.goods,'bread',1);await level(p,12);await p.save();return view(p,lang,'⚙️ 🥚 ×2 + 🌾 ×2 → **Farm Bread ×1**');}return view(p,lang,'⚙️ '+mtx(lang,'Need 3 Wheat for Feed, or ingredients for a processed good.','Cần 3 Lúa mì để làm thức ăn, hoặc đủ nguyên liệu cho sản phẩm chế biến.'));}
async function orders(p,lang){const needW=6+Math.min(10,p.level),needE=2+Math.floor(p.level/4),reward=45+needW*4+needE*10;if(num(p.crops,'wheat')<needW||num(p.goods,'egg')<needE)return view(p,lang,`📦 ${mtx(lang,'Current order','Đơn hiện tại')}: 🌾 ${needW} + 🥚 ${needE} → 🪙 ${reward}\n${mtx(lang,'Collect the required goods first.','Hãy thu thập đủ hàng trước.')}`);add(p.crops,'wheat',-needW);add(p.goods,'egg',-needE);p.coins+=reward;p.ordersCompleted++;await level(p,25);await p.save();return view(p,lang,`📦 ${mtx(lang,'Order delivered','Đã giao đơn')} • 🪙 +${reward} • +25 XP`);}
async function shop(p,lang){const choices=Object.entries(CROPS).filter(([id])=>cropUnlocked(p,id));const id=choices.find(([id,c])=>p.coins>=c.seed)?.[0];if(!id)return view(p,lang,'🛒 '+mtx(lang,'Not enough Farm Coins for seeds.','Không đủ Farm Coin mua giống.'));const c=CROPS[id];p.coins-=c.seed;add(p.seeds,id,3);await p.save();return view(p,lang,`🛒 ${c.emoji} +3 ${mtx(lang,c.en,c.vi)} ${mtx(lang,'seeds','giống')} • -${c.seed} 🪙`);}
async function expand(p,lang){const cost=250*p.landLevel;if(p.coins<cost)return view(p,lang,`🏡 ${mtx(lang,'Next expansion costs','Mở rộng tiếp theo cần')} **${cost} 🪙**.`);p.coins-=cost;p.landLevel++;p.barnLevel++;p.siloLevel++;const start=p.plots.length;for(let i=1;i<=2;i++)p.plots.push({slot:start+i,crop:null});await p.save();return view(p,lang,`🏡 ${mtx(lang,'Farm expanded','Nông trại đã mở rộng')} → Lv.${p.landLevel} • +2 ${mtx(lang,'plots','ô đất')}`);}
async function handle(i,lang){const[,a,owner]=i.customId.split(':');if(i.user.id!==owner)return i.reply({content:mtx(lang,'❌ This farm belongs to another player.','❌ Nông trại này thuộc người chơi khác.'),flags:64});const p=await profile(owner);if(a==='plant')return plantMenu(i,p,lang);if(a==='harvest')return i.update(await harvest(p,lang));if(a==='animals')return i.update(await animals(p,lang));if(a==='process')return i.update(await process(p,lang));if(a==='orders')return i.update(await orders(p,lang));if(a==='shop')return i.update(await shop(p,lang));if(a==='expand')return i.update(await expand(p,lang));if(a==='guide')return i.reply({content:`🌾 **Corgi Farm Guide**\n1. ${mtx(lang,'Buy/keep seeds and plant empty plots.','Mua/giữ giống và gieo vào ô trống.')}\n2. ${mtx(lang,'Harvest when ready; harvest returns crops and some seed.','Thu hoạch khi chín; bạn nhận nông sản và một phần giống.')}\n3. ${mtx(lang,'Process crops into feed/goods, collect animal products.','Chế biến nông sản thành thức ăn/sản phẩm rồi thu sản phẩm vật nuôi.')}\n4. ${mtx(lang,'Complete orders for Farm Coins and XP.','Hoàn thành đơn để nhận Farm Coin và XP.')}\n5. ${mtx(lang,'Expand Barn, Silo and land as your farm grows.','Mở rộng Barn, Silo và đất khi nông trại phát triển.')}`,flags:64});return i.update(view(p,lang));}
module.exports={home,handle,selectCrop,CROPS};
