const {EmbedBuilder,ActionRowBuilder,ButtonBuilder,ButtonStyle}=require('discord.js');
const FrontierProfile=require('../models/FrontierProfile');
const {mtx}=require('../services/i18n');

const REGIONS=[
 {id:'origin-plains',emoji:'🌱',en:'Origin Plains',vi:'Đồng Bằng Khởi Nguyên',rank:1,world:1,resource:'wood',rare:'sunstone',discoveries:['ancient-oak','crystal-stream','old-camp','windmill-ruin'],creatures:['mossling','swiftail','dewbug'],fish:['silver-minnow','grass-carp']},
 {id:'whispering-forest',emoji:'🌲',en:'Whispering Forest',vi:'Rừng Thì Thầm',rank:5,world:1,resource:'herb',rare:'moonleaf',discoveries:['sealed-grove','moon-pond','root-cavern','forgotten-shrine'],creatures:['emberfox','nightwing','thornback'],fish:['moon-koi','root-eel']},
 {id:'frozen-frontier',emoji:'❄️',en:'Frozen Frontier',vi:'Bắc Địa Băng Giá',rank:12,world:2,resource:'ice_crystal',rare:'frost_core',discoveries:['ice-arch','frost-cave','silent-lake','white-observatory'],creatures:['frostpaw','snowhorn','glacier-moth'],fish:['icefin','glass-trout']},
 {id:'lost-ocean',emoji:'🌊',en:'Lost Ocean',vi:'Đại Dương Thất Lạc',rank:22,world:3,resource:'coral',rare:'abyss_pearl',discoveries:['sunken-temple','blue-trench','forgotten-isle','leviathan-bones'],creatures:['tidefin','abyssray','shellkin'],fish:['royal-tuna','abyss-eel']},
 {id:'sky-archipelago',emoji:'☁️',en:'Sky Archipelago',vi:'Quần Đảo Trên Mây',rank:35,world:4,resource:'sky_shard',rare:'storm_core',discoveries:['wind-shrine','cloud-garden','storm-eye','fallen-airship'],creatures:['cloudtail','stormwing','zephyr-hare'],fish:['cloudfish','storm-koi']},
 {id:'ember-continent',emoji:'🌋',en:'Ember Continent',vi:'Lục Địa Dung Nham',rank:50,world:5,resource:'ember_ore',rare:'phoenix_ash',discoveries:['magma-vault','ash-city','fire-heart','obsidian-throne'],creatures:['cindermaw','flarewyrm','ashcrawler'],fish:['lava-eel','emberfin']},
 {id:'the-abyss',emoji:'🌑',en:'The Abyss',vi:'Vực Sâu',rank:70,world:6,resource:'void_fragment',rare:'void_heart',discoveries:['black-gate','void-rift','nameless-ruin','silent-star'],creatures:['voidling','dreadfin','echo-beast'],fish:['voidfish','blind-ray']},
 {id:'ancient-civilization',emoji:'🏛️',en:'Ancient Civilization',vi:'Nền Văn Minh Cổ Đại',rank:95,world:7,resource:'ancient_core',rare:'aether_core',discoveries:['first-library','eternal-engine','crown-sanctum','origin-vault'],creatures:['relicborn','aetherion','chronowl'],fish:['relic-koi','timefin']},
 {id:'starfall-reaches',emoji:'🌌',en:'Starfall Reaches',vi:'Miền Sao Rơi',rank:125,world:8,resource:'star_dust',rare:'astral_core',discoveries:['star-crater','astral-garden','silent-orbit','celestial-door'],creatures:['starling','nova-wyrm','orbitail'],fish:['starfin','nebula-ray']},
 {id:'eternal-frontier',emoji:'♾️',en:'Eternal Frontier',vi:'Biên Giới Vĩnh Hằng',rank:160,world:9,resource:'eternal_shard',rare:'genesis_core',discoveries:['endless-road','genesis-well','mirror-world','unknown-horizon'],creatures:['everling','genesis-beast','paradox-fox'],fish:['eternal-koi','paradox-eel']}
];
const RARITIES=[['Common',.54],['Rare',.25],['Epic',.12],['Legendary',.06],['Mythic',.025],['Secret',.005]];
const TRAITS=['Swift','Hardy','Curious','Lucky','Ancient Blood','Resonant','Explorer'];
const VARIANTS=[['normal',.965],['shiny',.025],['ancient',.008],['aurora',.002]];
const BUILDINGS={hall:{emoji:'🏰',name:'Hall'},workshop:{emoji:'🔨',name:'Workshop'},habitat:{emoji:'🐾',name:'Habitat'},museum:{emoji:'🏛️',name:'Museum'},research:{emoji:'🔬',name:'Research'}};
const rankNeed=r=>Math.floor(140*Math.pow(1+r/8,1.48));
const getRegion=id=>REGIONS.find(x=>x.id===id)||REGIONS[0];
const n=(p,k)=>Number(p.resources.get(k)||0); const add=(p,k,v)=>p.resources.set(k,n(p,k)+v);
const choose=a=>a[Math.floor(Math.random()*a.length)];
function weighted(a){let x=Math.random(),s=0;for(const [v,w] of a){s+=w;if(x<=s)return v;}return a[a.length-1][0];}
async function profile(uid){return FrontierProfile.findOneAndUpdate({userId:String(uid)},{$setOnInsert:{userId:String(uid),legacy:[`Pioneer • ${new Date().getUTCFullYear()}`]}},{upsert:true,returnDocument:'after',setDefaultsOnInsert:true});}
function bar(v,max,z=12){const x=Math.max(0,Math.min(z,Math.round(v/Math.max(1,max)*z)));return'█'.repeat(x)+'░'.repeat(z-x);}
function progress(p,r){return Math.min(100,Number(p.regionProgress.get(r.id)||0));}
function worldState(){const h=new Date().getUTCHours(),day=h>=6&&h<18;const slot=Math.floor(Date.now()/3600000)%6;return{day,weather:['Clear','Rain','Wind','Fog','Storm','Aurora'][slot],emoji:day?'☀️':'🌙'};}
async function gainXp(p,x){p.explorerXp+=x;let u=0;while(p.explorerXp>=rankNeed(p.explorerRank)){p.explorerXp-=rankNeed(p.explorerRank);p.explorerRank++;u++;}return u;}
function rows(uid,p){return[
 new ActionRowBuilder().addComponents(
  new ButtonBuilder().setCustomId(`fr:explore:${uid}`).setLabel('Explore').setEmoji('🧭').setStyle(ButtonStyle.Primary).setDisabled(p.energy<8),
  new ButtonBuilder().setCustomId(`fr:gather:${uid}`).setLabel('Gather').setEmoji('🎒').setStyle(ButtonStyle.Success).setDisabled(p.energy<5),
  new ButtonBuilder().setCustomId(`fr:fish:${uid}`).setLabel('Fish').setEmoji('🎣').setStyle(ButtonStyle.Primary).setDisabled(p.energy<6),
  new ButtonBuilder().setCustomId(`fr:camp:${uid}`).setLabel('Camp').setEmoji('⛺').setStyle(ButtonStyle.Secondary)),
 new ActionRowBuilder().addComponents(
  new ButtonBuilder().setCustomId(`fr:travel:${uid}`).setLabel('Travel').setEmoji('🗺️').setStyle(ButtonStyle.Secondary),
  new ButtonBuilder().setCustomId(`fr:craft:${uid}`).setLabel('Craft').setEmoji('🔨').setStyle(ButtonStyle.Success),
  new ButtonBuilder().setCustomId(`fr:base:${uid}`).setLabel('Build').setEmoji('🏕️').setStyle(ButtonStyle.Primary),
  new ButtonBuilder().setCustomId(`fr:creature:${uid}`).setLabel('Creature').setEmoji('🐾').setStyle(ButtonStyle.Secondary)),
 new ActionRowBuilder().addComponents(
  new ButtonBuilder().setCustomId(`fr:expedition:${uid}`).setLabel('Expedition').setEmoji('🧳').setStyle(ButtonStyle.Primary),
  new ButtonBuilder().setCustomId(`fr:research:${uid}`).setLabel('Research').setEmoji('🔬').setStyle(ButtonStyle.Secondary),
  new ButtonBuilder().setCustomId(`fr:world:${uid}`).setLabel('World').setEmoji('🌎').setStyle(ButtonStyle.Success),
  new ButtonBuilder().setCustomId(`fr:codex:${uid}`).setLabel('Codex').setEmoji('📖').setStyle(ButtonStyle.Secondary))];}
function view(p,lang,msg=''){const r=getRegion(p.currentRegion),w=worldState(),need=rankNeed(p.explorerRank),pc=progress(p,r);const e=new EmbedBuilder().setColor(0x4CAF78).setTitle('🌍 Corgi Frontier • '+mtx(lang,'Endless Frontier','Hành Trình Vô Tận')).setDescription(`${r.emoji} **${mtx(lang,r.en,r.vi)}** • World ${r.world}\n${w.emoji} ${w.day?'Day':'Night'} • ${w.weather}\n${msg?`\n${msg}\n`:''}\n${mtx(lang,'One click = one real action. Permanent progression, no seasonal reset.','Một lần bấm = một hành động thật. Tiến trình vĩnh viễn, không reset mùa.')}`).addFields(
{name:'🧭 Explorer',value:`Rank **${p.explorerRank}** • Prestige **${p.prestige}**\n${bar(p.explorerXp,need)} ${p.explorerXp}/${need}`,inline:false},
{name:'❤️ Journey',value:`Energy **${p.energy}/100** • Supplies **${p.supplies}**\nRegion ${bar(pc,100,10)} **${pc.toFixed(1)}%**`,inline:false},
{name:'🏕️ Legacy',value:`Base **Lv.${p.baseLevel}** • Expeditions **${p.expeditions}** • Distance **${p.distance}**\nFrontier Marks **${p.frontierMarks}**`,inline:false},
{name:'📖 Collection',value:`🗺️ ${p.discoveries.length} • 🐾 ${p.creatures.length} • 🎣 ${p.fish.length} • 🏺 ${p.artifacts.length} • ✨ ${p.secrets.length}/???`,inline:false}
).setFooter({text:'Corgi Frontier • Persistent World • Direct Action UI'});return{embeds:[e],components:rows(p.userId,p)};}
async function home(uid,lang){const p=await profile(uid);return view(p,lang);}
async function explore(uid,lang){const p=await profile(uid),r=getRegion(p.currentRegion);if(p.energy<8)return view(p,lang,'⚠️ '+mtx(lang,'Not enough energy.','Không đủ năng lượng.'));p.energy-=8;p.expeditions++;p.distance+=2+Math.floor(Math.random()*7);p.mastery.exploration++;p.regionProgress.set(r.id,Math.min(100,progress(p,r)+(.6+Math.random()*1.8)));let msg='',xp=24,roll=Math.random();
 if(roll<.30){const pool=r.discoveries.filter(x=>!p.discoveries.includes(x));if(pool.length){const x=choose(pool);p.discoveries.push(x);msg=`✨ ${mtx(lang,'New location','Địa điểm mới')}: **${x.replaceAll('-',' ')}**`;xp=55;}}
 if(!msg&&roll<.58){const species=choose(r.creatures),rarity=weighted(RARITIES),variant=weighted(VARIANTS),potential=45+Math.floor(Math.random()*55);p.creatures.push({species,rarity,variant,potential,trait:choose(TRAITS)});msg=`🐾 ${mtx(lang,'Encounter recorded','Ghi nhận sinh vật')}: **${variant!=='normal'?variant+' ':''}${species}** • ${rarity} • Potential ${potential}`;xp=45;}
 if(!msg&&roll<.72){const id=`${r.id}-relic-${1+Math.floor(Math.random()*12)}`;if(!p.artifacts.includes(id))p.artifacts.push(id);msg=`🏺 ${mtx(lang,'Artifact recovered','Thu hồi cổ vật')}: **${id.replaceAll('-',' ')}**`;xp=60;}
 if(!msg&&roll<.78&&progress(p,r)>60){const s=`secret-${r.id}-${1+Math.floor(Math.random()*5)}`;if(!p.secrets.includes(s)){p.secrets.push(s);msg=`✨ **${mtx(lang,'SECRET DISCOVERY','KHÁM PHÁ BÍ MẬT')}** • ???`;xp=120;}}
 if(!msg){const q=1+Math.floor(Math.random()*3);add(p,r.resource,q);msg=`🧭 ${mtx(lang,'You advanced deeper and recovered','Bạn tiến sâu hơn và thu được')} **${q} ${r.resource.replaceAll('_',' ')}**.`;}
 const u=await gainXp(p,xp);if(u)msg+=`\n⬆️ ${mtx(lang,'Explorer Rank','Hạng Khai Phá')} → **${p.explorerRank}**`;await achievements(p);p.lastActionAt=new Date();await p.save();return view(p,lang,msg);}
async function gather(uid,lang){const p=await profile(uid),r=getRegion(p.currentRegion);if(p.energy<5)return view(p,lang,'⚠️ '+mtx(lang,'Not enough energy.','Không đủ năng lượng.'));p.energy-=5;p.mastery.gathering++;const q=3+Math.floor(Math.random()*7)+Math.floor(p.mastery.gathering/100);add(p,r.resource,q);let msg=`🎒 +**${q} ${r.resource.replaceAll('_',' ')}**`;if(Math.random()<.08){add(p,r.rare,1);msg+=`\n💎 +**1 ${r.rare.replaceAll('_',' ')}**`;}if(Math.random()<.18)p.supplies=Math.min(99,p.supplies+1);await gainXp(p,10);await p.save();return view(p,lang,msg);}
async function fish(uid,lang){const p=await profile(uid),r=getRegion(p.currentRegion);if(p.energy<6)return view(p,lang,'⚠️ '+mtx(lang,'Not enough energy.','Không đủ năng lượng.'));p.energy-=6;p.mastery.fishing++;const f=choose(r.fish),rare=Math.random()<.09,tag=rare?`✨ ${f}`:f;if(!p.fish.includes(tag))p.fish.push(tag);add(p,'fish_meat',rare?4:2);await gainXp(p,rare?30:12);await p.save();return view(p,lang,`🎣 ${mtx(lang,'Caught','Bắt được')} **${tag.replaceAll('-',' ')}**${rare?' • RARE VARIANT':''}`);}
async function camp(uid,lang){const p=await profile(uid),use=Math.min(3,p.supplies);if(!use)return view(p,lang,'🥫 '+mtx(lang,'No supplies left.','Đã hết tiếp tế.'));p.supplies-=use;p.energy=Math.min(100,p.energy+use*24);await p.save();return view(p,lang,`⛺ +**${use*24} Energy** • -${use} Supplies`);}
async function travel(uid,lang){const p=await profile(uid),u=REGIONS.filter(x=>p.explorerRank>=x.rank),i=u.findIndex(x=>x.id===p.currentRegion),next=u[(i+1)%u.length];p.currentRegion=next.id;await p.save();return view(p,lang,`🗺️ ${mtx(lang,'Travelled to','Đã tới')} **${mtx(lang,next.en,next.vi)}**`);}
async function craft(uid,lang){const p=await profile(uid),r=getRegion(p.currentRegion),cost=6+Math.floor(p.mastery.crafting/80);if(n(p,r.resource)<cost)return view(p,lang,`🔨 ${mtx(lang,'Need','Cần')} **${cost} ${r.resource.replaceAll('_',' ')}**.`);add(p,r.resource,-cost);p.supplies=Math.min(99,p.supplies+4);p.mastery.crafting++;p.crafted.set('expedition-kit',Number(p.crafted.get('expedition-kit')||0)+1);await gainXp(p,16);await p.save();return view(p,lang,`🔨 ${mtx(lang,'Crafted Expedition Kit','Đã chế tạo Bộ Viễn Chinh')} • +4 Supplies`);}
async function build(uid,lang){const p=await profile(uid),r=getRegion(p.currentRegion),b=p.buildings.sort((a,b)=>a.level-b.level)[0],cost=10+b.level*6;if(n(p,r.resource)<cost)return view(p,lang,`🏕️ ${BUILDINGS[b.id]?.name||b.id} Lv.${b.level+1} ${mtx(lang,'needs','cần')} **${cost} ${r.resource.replaceAll('_',' ')}**.`);add(p,r.resource,-cost);b.level++;p.baseLevel=Math.floor(p.buildings.reduce((s,x)=>s+x.level,0)/p.buildings.length);await gainXp(p,25);await p.save();return view(p,lang,`${BUILDINGS[b.id]?.emoji||'🏕️'} **${BUILDINGS[b.id]?.name||b.id} → Lv.${b.level}**\n🏰 Base Lv.${p.baseLevel}`);}
async function creature(uid,lang){const p=await profile(uid);if(!p.creatures.length)return view(p,lang,'🐾 '+mtx(lang,'No creature recorded yet. Explore first.','Chưa có sinh vật. Hãy khám phá trước.'));const c=p.creatures.slice().sort((a,b)=>b.potential-a.potential)[0];const cost=3+c.evolution*2;if(n(p,'fish_meat')>=cost){add(p,'fish_meat',-cost);c.bond+=5;c.xp+=20;c.level+=c.xp>=100?1:0;if(c.xp>=100)c.xp-=100;if(c.bond>=50*(c.evolution+1)&&c.evolution<3){c.evolution++;c.bond=0;}p.mastery.creatures++;await p.save();return view(p,lang,`🐾 **${c.variant!=='normal'?c.variant+' ':''}${c.species}** • Lv.${c.level} • Evo ${c.evolution}\n❤️ Bond ${c.bond} • ${c.trait} • Potential ${c.potential}`);}return view(p,lang,`🐾 **${c.species}** ${mtx(lang,'needs','cần')} ${cost} fish meat ${mtx(lang,'to train','để huấn luyện')}.`);}
async function expedition(uid,lang){const p=await profile(uid),r=getRegion(p.currentRegion),now=Date.now();if(p.activeExpedition?.status==='active'){if(new Date(p.activeExpedition.endsAt).getTime()>now){const m=Math.ceil((new Date(p.activeExpedition.endsAt)-now)/60000);return view(p,lang,`🧳 ${mtx(lang,'Expedition in progress','Viễn chinh đang diễn ra')} • **${m}m**`);}const risk=p.activeExpedition.risk,mult=risk==='high'?3:risk==='medium'?2:1,q=(4+Math.floor(Math.random()*7))*mult;add(p,r.resource,q);if(Math.random()<.12*mult)add(p,r.rare,1);p.frontierMarks+=2*mult;p.activeExpedition=null;p.expeditions++;await gainXp(p,30*mult);await p.save();return view(p,lang,`🧳 ${mtx(lang,'Expedition completed','Viễn chinh hoàn tất')} • +${q} ${r.resource.replaceAll('_',' ')} • +${2*mult} Marks`);}if(p.supplies<4)return view(p,lang,'🧳 '+mtx(lang,'Need at least 4 supplies.','Cần ít nhất 4 tiếp tế.'));p.supplies-=4;const risk=p.explorerRank>=r.rank+15?'high':p.explorerRank>=r.rank+5?'medium':'low',mins=risk==='high'?90:risk==='medium'?45:20;p.activeExpedition={region:r.id,startedAt:new Date(),endsAt:new Date(now+mins*60000),risk,status:'active'};await p.save();return view(p,lang,`🧳 ${mtx(lang,'Expedition launched','Đã khởi hành viễn chinh')} • ${risk.toUpperCase()} • ${mins}m`);}
async function research(uid,lang){const p=await profile(uid),r=getRegion(p.currentRegion);if(!p.artifacts.length)return view(p,lang,'🔬 '+mtx(lang,'Find an artifact first.','Hãy tìm cổ vật trước.'));const id=`lore-${r.id}-${1+Math.floor(Math.random()*8)}`;if(!p.lore.includes(id))p.lore.push(id);p.frontierMarks++;await gainXp(p,18);await p.save();return view(p,lang,`🔬 ${mtx(lang,'Research decoded','Nghiên cứu giải mã')} **${id.replaceAll('-',' ')}** • +1 Mark`);}
async function world(uid,lang){const p=await profile(uid),r=getRegion(p.currentRegion),cost=5;if(n(p,r.resource)<cost)return view(p,lang,`🌎 ${mtx(lang,'World Project needs','Dự án thế giới cần')} ${cost} ${r.resource.replaceAll('_',' ')}.`);add(p,r.resource,-cost);p.worldContributions+=cost;p.frontierMarks++;await p.save();return view(p,lang,`🌎 ${mtx(lang,'Contributed to the permanent World Project','Đã đóng góp vào Dự Án Thế Giới vĩnh viễn')} • Total **${p.worldContributions}** • +1 Mark`);}
async function codex(uid,lang){const p=await profile(uid),top=p.creatures.slice().sort((a,b)=>b.potential-a.potential).slice(0,3).map(c=>`${c.rarity} ${c.variant!=='normal'?c.variant+' ':''}${c.species} P${c.potential}`).join('\n')||'—';const b=p.buildings.map(x=>`${BUILDINGS[x.id]?.emoji||'🏕️'} ${BUILDINGS[x.id]?.name||x.id} ${x.level}`).join(' • ');return view(p,lang,`📖 **FRONTIER CODEX**\n🗺️ Locations ${p.discoveries.length} • ✨ Secrets ${p.secrets.length}/??? • 🏺 Artifacts ${p.artifacts.length} • 📜 Lore ${p.lore.length}\n🐾 Creatures ${p.creatures.length} • 🎣 Fish ${p.fish.length}\n\n**Top Creatures**\n${top}\n\n**Base**\n${b}\n\n🏆 Achievements ${p.achievements.length} • 📜 Legacy ${p.legacy.length}`);}
async function achievements(p){const checks=[[p.expeditions>=100,'expedition-100'],[p.discoveries.length>=20,'discoverer-20'],[p.creatures.length>=25,'naturalist-25'],[p.secrets.length>=3,'secret-seeker'],[p.baseLevel>=10,'frontier-builder'],[p.explorerRank>=50,'veteran-explorer'],[p.explorerRank>=100,'legend-explorer']];for(const[c,id]of checks)if(c&&!p.achievements.includes(id)){p.achievements.push(id);p.frontierMarks+=5;}}
async function handle(i,lang){const[,a,owner]=i.customId.split(':');if(String(i.user.id)!==String(owner))return i.reply({content:mtx(lang,'❌ This journey belongs to another explorer.','❌ Hành trình này thuộc người chơi khác.'),flags:64});const fn={explore,gather,fish,camp,travel,craft,base:build,creature,expedition,research,world,codex}[a];if(!fn)return i.update(await home(owner,lang));return i.update(await fn(owner,lang));}
module.exports={home,handle,REGIONS};
