const {EmbedBuilder,ActionRowBuilder,ButtonBuilder,ButtonStyle,StringSelectMenuBuilder,ModalBuilder,TextInputBuilder,TextInputStyle}=require('discord.js');
const {mtx}=require('../services/i18n');
const GameHubProfile=require('../models/GameHubProfile');
const CompanyProfile=require('../models/CompanyProfile');

// Curated V6.3 Game Hub: 15 core games + CEO Empire. Removed games are intentionally not routable.
const GAMES=[
 ['fishing','🎣','Fishing 2.0','Câu Cá 2.0',true,'adventure'],
 ['pet-hunt','🐾','Pet Hunt','Săn Pet',true,'adventure'],
 ['pet-arena','⚔️','Pet Arena','Đấu Trường Pet',true,'arena'],
 ['expedition','🗺️','Expedition','Thám Hiểm',true,'adventure'],
 ['dungeon','🏰','Dungeon','Hầm Ngục',true,'adventure'],
 ['mining','⛏️','Mining','Đào Khoáng',true,'career'],
 ['raid','🛡️','Raid Boss','Raid Boss',true,'arena'],
 ['ghost','👻','Ghost Hunt','Săn Ma',true,'adventure'],
 ['deep-sea','🌊','Deep Sea','Biển Sâu',true,'adventure'],
 ['alchemy','🧪','Alchemy Lab','Phòng Giả Kim',true,'career'],
 ['zombie','🧟','Zombie Survival','Sinh Tồn Zombie',true,'arena'],
 ['racing','🏎️','Racing','Đua Xe',true,'arena'],
 ['cooking','🍳','Cooking Challenge','Thử Thách Nấu Ăn',true,'career'],
 ['cafe','☕','Café Rush','Quán Cà Phê',true,'career'],
 ['farm','🌾','Farm Life','Nông Trại',true,'career'],
 ['ceo','🏢','CEO Empire','Đế Chế Doanh Nghiệp',true,'career']
].map(x=>({id:x[0],emoji:x[1],en:x[2],vi:x[3],tournament:x[4],category:x[5]}));
const get=id=>GAMES.find(g=>g.id===id);
const categories=[['adventure','🗺️','Adventure','Phiêu lưu'],['arena','🏆','Competitive','Đối kháng'],['career','💼','Career & Sim','Nghề nghiệp & Giả lập']];

const RULES={
 'pet-hunt':{stats:['Tracks','Baits','Bond'],start:[0,3,0],actions:[['track','🔎','Track','Theo dấu',[18,-1,4]],['bait','🦴','Set Bait','Đặt mồi',[10,-1,12]],['catch','🪤','Catch','Bắt Pet',[30,-1,8]]],goal:100},
 'pet-arena':{stats:['Pet HP','Enemy HP','Focus'],start:[100,100,30],actions:[['attack','⚔️','Attack','Tấn công',[-8,-22,4]],['guard','🛡️','Guard','Phòng thủ',[-3,-10,12]],['special','✨','Pet Skill','Kỹ năng Pet',[-12,-32,-10]]],goal:0,target:1},
 expedition:{stats:['Distance','Supplies','Discovery'],start:[0,100,0],actions:[['travel','🥾','Travel','Di chuyển',[18,-12,5]],['scout','🔭','Scout','Trinh sát',[8,-6,16]],['camp','⛺','Camp','Dựng trại',[4,18,3]]],goal:100},
 dungeon:{stats:['Floor','HP','Loot'],start:[1,100,0],actions:[['fight','🗡️','Fight','Chiến đấu',[1,-16,18]],['search','🔎','Search Room','Tìm phòng',[0,-7,25]],['rest','🧪','Use Potion','Dùng bình',[0,22,-4]]],goal:8},
 mining:{stats:['Depth','Pickaxe','Ore'],start:[0,100,0],actions:[['dig','⛏️','Dig','Đào',[12,-8,15]],['scan','📡','Scan Vein','Dò mạch',[5,-3,24]],['reinforce','🔧','Repair Gear','Sửa dụng cụ',[2,20,-5]]],goal:100},
 raid:{stats:['Boss HP','Your HP','Rage'],start:[250,100,0],actions:[['strike','⚔️','Strike','Đánh',[-28,-10,10]],['block','🛡️','Block','Đỡ',[-10,-3,16]],['ultimate','💥','Ultimate','Tuyệt kỹ',[-48,-18,-20]]],goal:0,target:0},
 ghost:{stats:['Evidence','Sanity','Seal'],start:[0,100,0],actions:[['inspect','🔦','Investigate','Điều tra',[18,-7,5]],['listen','🎙️','EVP Scan','Quét EVP',[12,-10,15]],['seal','🧿','Seal Spirit','Phong ấn',[8,-12,22]]],goal:100},
 'deep-sea':{stats:['Depth','Oxygen','Samples'],start:[0,100,0],actions:[['dive','🤿','Dive Deeper','Lặn sâu',[15,-14,8]],['sample','🪸','Collect Sample','Lấy mẫu',[5,-8,22]],['surface','🫧','Stabilize','Ổn định',[2,20,2]]],goal:100},
 alchemy:{stats:['Purity','Heat','Essence'],start:[0,40,10],actions:[['grind','🌿','Prepare Herbs','Sơ chế dược',[16,-2,12]],['heat','🔥','Control Heat','Điều nhiệt',[12,14,8]],['distill','⚗️','Distill','Chưng cất',[22,-10,-6]]],goal:100},
 zombie:{stats:['Wave','HP','Ammo'],start:[1,100,40],actions:[['shoot','🔫','Shoot','Bắn',[1,-6,-8]],['melee','🪓','Melee','Cận chiến',[1,-14,2]],['loot','🎒','Loot','Nhặt đồ',[0,-7,15]]],goal:10},
 racing:{stats:['Distance','Car HP','Boost'],start:[0,100,30],actions:[['race','🏎️','Accelerate','Tăng tốc',[20,-6,-5]],['boost','🔥','Nitro','Nitro',[32,-12,-18]],['pit','🔧','Pit Stop','Pit Stop',[5,24,12]]],goal:100},
 cooking:{stats:['Dish','Time','Quality'],start:[0,100,0],actions:[['prep','🔪','Prep','Sơ chế',[20,-12,10]],['cook','🔥','Cook','Nấu',[25,-18,18]],['plate','🍽️','Plate','Trình bày',[15,-8,24]]],goal:100},
 cafe:{stats:['Orders','Patience','Tips'],start:[0,100,0],actions:[['take','📝','Take Order','Nhận đơn',[1,-5,5]],['brew','☕','Brew','Pha chế',[2,-12,12]],['serve','🛎️','Serve','Phục vụ',[2,-8,18]]],goal:12},
 farm:{stats:['Growth','Water','Harvest'],start:[0,70,0],actions:[['plant','🌱','Plant','Gieo hạt',[15,-5,3]],['water','💧','Water','Tưới nước',[12,18,2]],['tend','🧺','Tend Crops','Chăm cây',[20,-10,12]]],goal:100}
};
function L(lang,en,vi){return mtx(lang,en,vi)}
function home(uid,lang){const e=new EmbedBuilder().setColor(0x5865F2).setTitle('🎮 Corgi-Bot • Game Hub').setDescription(L(lang,'16 curated games with real, distinct gameplay. Fishing keeps its full system; CEO Empire is a persistent company simulator.','16 game được tuyển chọn với gameplay riêng thật sự. Fishing giữ nguyên hệ thống đầy đủ; CEO Empire là game giả lập công ty dài hạn.')).addFields({name:'⭐ '+L(lang,'Core games','Game chính'),value:L(lang,'Fishing • Pet • Adventure • Combat • Career simulations','Câu cá • Pet • Phiêu lưu • Chiến đấu • Giả lập nghề nghiệp')},{name:'🏢 CEO Empire',value:L(lang,'Register a company, recruit staff, build products, raise capital and work toward IPO.','Đăng ký công ty, tuyển nhân viên, làm sản phẩm, gọi vốn và tiến tới IPO.')});const menu=new StringSelectMenuBuilder().setCustomId(`gh:cat:${uid}`).setPlaceholder(L(lang,'Choose a category…','Chọn thể loại…')).addOptions(categories.map(c=>({value:c[0],emoji:c[1],label:L(lang,c[2],c[3])})));const row=new ActionRowBuilder().addComponents(new ButtonBuilder().setCustomId(`gh:tour:${uid}`).setLabel(L(lang,'Tournaments','Giải đấu')).setEmoji('🏆').setStyle(ButtonStyle.Success),new ButtonBuilder().setCustomId(`gh:stats:${uid}`).setLabel(L(lang,'My Stats','Thống kê')).setEmoji('📊').setStyle(ButtonStyle.Secondary),new ButtonBuilder().setCustomId(`gh:market:${uid}`).setLabel('Market').setEmoji('📈').setStyle(ButtonStyle.Primary),new ButtonBuilder().setCustomId(`gh:season:${uid}`).setLabel('Seasonal').setEmoji('🎊').setStyle(ButtonStyle.Secondary));return{embeds:[e],components:[new ActionRowBuilder().addComponents(menu),row]};}
function category(uid,cat,lang){const list=GAMES.filter(g=>g.category===cat);const meta=categories.find(c=>c[0]===cat);const e=new EmbedBuilder().setTitle(`${meta?.[1]||'🎮'} ${L(lang,meta?.[2]||'Games',meta?.[3]||'Game')}`).setDescription(list.map(g=>`${g.emoji} **${L(lang,g.en,g.vi)}**${g.tournament?' • 🏆':''}`).join('\n'));const menu=new StringSelectMenuBuilder().setCustomId(`gh:pick:${uid}`).setPlaceholder(L(lang,'Choose a game…','Chọn game…')).addOptions(list.map(g=>({value:g.id,emoji:g.emoji,label:L(lang,g.en,g.vi).slice(0,100)})));return{embeds:[e],components:[new ActionRowBuilder().addComponents(menu),new ActionRowBuilder().addComponents(new ButtonBuilder().setCustomId(`gh:home:${uid}`).setLabel('Game Hub').setEmoji('◀️').setStyle(ButtonStyle.Secondary))]};}
async function profile(uid){return GameHubProfile.findOneAndUpdate({userId:String(uid)},{$setOnInsert:{userId:String(uid)}},{upsert:true,returnDocument:'after'});}
async function play(uid,id,lang){if(id==='fishing')return require('./fishing').home(uid,lang);if(id==='ceo')return ceoHome(uid,lang);const g=get(id),rule=RULES[id];if(!g||!rule)return home(uid,lang);const p=await profile(uid);const state={v:[...rule.start],turn:0,score:0};p.gameStates.set(id,state);p.currentGame=id;p.sessionStartedAt=new Date();await p.save();return gameScene(uid,g,rule,state,lang);}
function gameScene(uid,g,r,s,lang,msg=''){const fields=r.stats.map((x,i)=>({name:x,value:`**${Math.round(s.v[i])}**`,inline:true}));fields.push({name:L(lang,'Score','Điểm'),value:`**${Math.round(s.score)}**`,inline:true});const e=new EmbedBuilder().setColor(0x57F287).setTitle(`${g.emoji} ${L(lang,g.en,g.vi)}`).setDescription(msg||L(lang,'Make a decision. This game has its own resources, objective and risk.','Hãy đưa ra quyết định. Game này có tài nguyên, mục tiêu và rủi ro riêng.')).addFields(fields).setFooter({text:L(lang,`Objective: ${r.stats[r.target??0]} → ${r.goal}`,`Mục tiêu: ${r.stats[r.target??0]} → ${r.goal}`)});const buttons=r.actions.map(a=>new ButtonBuilder().setCustomId(`gh:act:${uid}:${g.id}:${a[0]}`).setLabel(L(lang,a[2],a[3])).setEmoji(a[1]).setStyle(a[0]==='special'||a[0]==='ultimate'||a[0]==='boost'?ButtonStyle.Success:ButtonStyle.Primary));buttons.push(new ButtonBuilder().setCustomId(`gh:finish:${uid}:${g.id}`).setLabel(L(lang,'Finish','Kết thúc')).setStyle(ButtonStyle.Danger));return{embeds:[e],components:[new ActionRowBuilder().addComponents(buttons)]};}
async function action(uid,id,a,lang){const g=get(id),r=RULES[id],p=await profile(uid);if(!g||!r)return home(uid,lang);let s=p.gameStates.get(id);if(!s||p.currentGame!==id)return play(uid,id,lang);s=JSON.parse(JSON.stringify(s));const act=r.actions.find(x=>x[0]===a);if(!act)return gameScene(uid,g,r,s,lang);const risk=Math.random()<Math.min(.30,.06+s.turn*.02);s.turn++;act[4].forEach((d,i)=>s.v[i]=Math.max(0,s.v[i]+d+(risk&&d>0?-Math.ceil(d*.55):0)));s.score+=Math.max(5,act[4].reduce((n,x)=>n+Math.max(0,x),0))*(risk?.5:1);const target=r.target??0;const won=r.goal===0?s.v[target]<=0:s.v[target]>=r.goal;const lost=s.turn>=12||((id==='pet-arena'||id==='raid'||id==='zombie')&&s.v[1]<=0)||((id==='deep-sea')&&s.v[1]<=0);if(won||lost)return finishRun(uid,id,lang,s,won);p.gameStates.set(id,s);await p.save();await seasonal(uid,id);return gameScene(uid,g,r,s,lang,risk?L(lang,'⚠️ Risk event! The action was less effective.','⚠️ Biến cố! Hành động kém hiệu quả hơn.'):L(lang,'✅ Action completed. Choose the next move.','✅ Hành động hoàn tất. Chọn bước tiếp theo.'));}
async function seasonal(uid,id){return require('../services/seasonalService').rollDrop(uid,id).catch(()=>[])}
async function finishRun(uid,id,lang,s,won=true){const p=await profile(uid),g=get(id);p.gamesPlayed=(p.gamesPlayed||0)+1;p.bestScores.set(id,Math.max(Number(p.bestScores.get(id)||0),Math.round(s.score)));p.currentGame='';p.gameStates.delete(id);await p.save();await require('../services/tournamentService').submitScore(uid,id,Math.round(s.score)).catch(()=>{});await seasonal(uid,id);return{embeds:[new EmbedBuilder().setTitle(`${won?'🏆':'🏁'} ${g.emoji} ${L(lang,g.en,g.vi)}`).setDescription(L(lang,`${won?'Objective completed':'Run ended'} • **${Math.round(s.score)} pts**`,`${won?'Hoàn thành mục tiêu':'Phiên kết thúc'} • **${Math.round(s.score)} điểm**`))],components:[new ActionRowBuilder().addComponents(new ButtonBuilder().setCustomId(`gh:play:${uid}:${id}`).setLabel(L(lang,'Play Again','Chơi lại')).setStyle(ButtonStyle.Primary),new ButtonBuilder().setCustomId(`gh:home:${uid}`).setLabel('Game Hub').setStyle(ButtonStyle.Secondary))]};}

// CEO Empire — persistent simulator, independent from short-session games.
async function company(uid){return CompanyProfile.findOne({userId:String(uid)});}
function money(n){return '$'+Math.round(Number(n)||0).toLocaleString('en-US')}
async function ceoHome(uid,lang){const c=await company(uid);if(!c){const e=new EmbedBuilder().setColor(0xF1C40F).setTitle('🏢 '+L(lang,'CEO Empire • Start a Company','Đế Chế Doanh Nghiệp • Khởi nghiệp')).setDescription(L(lang,'You are the founder. Start from zero: register the business, choose an industry, open the company account, then recruit your first employees.','Bạn là nhà sáng lập. Bắt đầu từ số 0: đăng ký doanh nghiệp, chọn ngành, mở tài khoản công ty rồi tuyển những nhân viên đầu tiên.'));return{embeds:[e],components:[new ActionRowBuilder().addComponents(new ButtonBuilder().setCustomId(`gh:ceocreate:${uid}`).setLabel(L(lang,'Register Company','Đăng ký công ty')).setEmoji('📝').setStyle(ButtonStyle.Success),new ButtonBuilder().setCustomId(`gh:home:${uid}`).setLabel('Game Hub').setStyle(ButtonStyle.Secondary))]};}return ceoPanel(c,lang);}
function ceoPanel(c,lang,msg=''){const profit=c.revenue-c.monthlyCosts,runway=c.monthlyCosts>c.revenue?c.cash/Math.max(1,c.monthlyCosts-c.revenue):999;const stage=c.stage==='PUBLIC'?'PUBLIC / IPO':c.stage;const e=new EmbedBuilder().setColor(c.cash<0?0xED4245:0xF1C40F).setTitle(`🏢 ${c.companyName} • ${stage}`).setDescription(msg||L(lang,'Run the company month by month. Cash, hiring, product quality and ownership all matter.','Điều hành công ty theo từng tháng. Tiền mặt, tuyển dụng, chất lượng sản phẩm và tỷ lệ sở hữu đều quan trọng.')).addFields({name:L(lang,'Cash','Tiền mặt'),value:money(c.cash),inline:true},{name:L(lang,'Revenue / month','Doanh thu / tháng'),value:money(c.revenue),inline:true},{name:L(lang,'Profit / month','Lợi nhuận / tháng'),value:money(profit),inline:true},{name:L(lang,'Valuation','Định giá'),value:money(c.valuation),inline:true},{name:L(lang,'Founder ownership','Sở hữu Founder'),value:`${c.founderOwnership.toFixed(1)}%`,inline:true},{name:L(lang,'Employees','Nhân viên'),value:String(c.employees.length),inline:true},{name:L(lang,'Product','Sản phẩm'),value:`${Math.round(c.product)}/100`,inline:true},{name:L(lang,'Customers','Khách hàng'),value:c.customers.toLocaleString(),inline:true},{name:L(lang,'Runway','Thời gian sống'),value:runway===999?'∞':`${runway.toFixed(1)} mo`,inline:true});if(c.stage==='PUBLIC')e.addFields({name:'📈 '+L(lang,'Stock','Cổ phiếu'),value:`${money(c.stockPrice)} / share • ${L(lang,'Market cap','Vốn hóa')} ${money(c.valuation)}`});const row1=new ActionRowBuilder().addComponents(new ButtonBuilder().setCustomId(`gh:ceo:${c.userId}:recruit`).setLabel(L(lang,'Recruit','Tuyển dụng')).setEmoji('👥').setStyle(ButtonStyle.Primary),new ButtonBuilder().setCustomId(`gh:ceo:${c.userId}:product`).setLabel(L(lang,'Build Product','Phát triển SP')).setEmoji('🛠️').setStyle(ButtonStyle.Primary),new ButtonBuilder().setCustomId(`gh:ceo:${c.userId}:market`).setLabel('Marketing').setEmoji('📣').setStyle(ButtonStyle.Primary),new ButtonBuilder().setCustomId(`gh:ceo:${c.userId}:finance`).setLabel(L(lang,'Funding','Gọi vốn')).setEmoji('💰').setStyle(ButtonStyle.Success),new ButtonBuilder().setCustomId(`gh:ceo:${c.userId}:month`).setLabel(L(lang,'Next Month','Qua tháng')).setEmoji('📅').setStyle(ButtonStyle.Secondary));const row2=new ActionRowBuilder().addComponents(new ButtonBuilder().setCustomId(`gh:ceo:${c.userId}:ipo`).setLabel('IPO').setEmoji('🏦').setStyle(ButtonStyle.Success),new ButtonBuilder().setCustomId(`gh:home:${c.userId}`).setLabel('Game Hub').setStyle(ButtonStyle.Secondary));return{embeds:[e],components:[row1,row2]};}
async function ceoCreateModal(i,lang){const uid=i.user.id;const modal=new ModalBuilder().setCustomId(`gh:ceosubmit:${uid}`).setTitle(L(lang,'Register Your Company','Đăng ký công ty'));const name=new TextInputBuilder().setCustomId('name').setLabel(L(lang,'Company name','Tên công ty')).setStyle(TextInputStyle.Short).setMinLength(2).setMaxLength(40).setRequired(true);const industry=new TextInputBuilder().setCustomId('industry').setLabel(L(lang,'Industry (e.g. Technology)','Ngành (VD: Công nghệ)')).setStyle(TextInputStyle.Short).setMinLength(2).setMaxLength(40).setRequired(true);return i.showModal(modal.addComponents(new ActionRowBuilder().addComponents(name),new ActionRowBuilder().addComponents(industry)));}
async function ceoSubmit(i,lang){const uid=i.user.id;if(await company(uid))return i.reply({content:L(lang,'You already own a company.','Bạn đã có công ty.'),flags:64});const name=i.fields.getTextInputValue('name').trim(),industry=i.fields.getTextInputValue('industry').trim();const c=await CompanyProfile.create({userId:uid,companyName:name,industry,registered:true,bankOpened:true,stage:'BOOTSTRAP'});return i.reply(await ceoPanel(c,lang,L(lang,`✅ ${name} is registered. You own 100%. Next: recruit a small founding team and build the first product.`,`✅ ${name} đã đăng ký. Bạn sở hữu 100%. Tiếp theo: tuyển đội ngũ sáng lập nhỏ và làm sản phẩm đầu tiên.`)));}
function candidate(c){const roles=['Software Engineer','Product Designer','Sales Executive','Marketing Specialist','Operations Manager','Finance Analyst'];const names=['Alex Morgan','Jamie Lee','Taylor Kim','Jordan Smith','Casey Nguyen','Sam Rivera','Avery Chen'];const role=roles[Math.floor(Math.random()*roles.length)],skill=45+Math.floor(Math.random()*51),salary=Math.round((2800+skill*55)/100)*100;return{name:names[Math.floor(Math.random()*names.length)],role,skill,salary,morale:70};}
async function ceoAction(uid,a,lang){const c=await company(uid);if(!c)return ceoHome(uid,lang);if(a==='recruit'){const cand=candidate(c);c.lastCandidate=cand;await c.save();const e=new EmbedBuilder().setTitle('📄 '+L(lang,'Candidate CV','CV Ứng viên')).setDescription(`**${cand.name}**\n${cand.role}\n${L(lang,'Skill','Kỹ năng')}: **${cand.skill}/100**\n${L(lang,'Expected salary','Lương kỳ vọng')}: **${money(cand.salary)}/mo**`);return{embeds:[e],components:[new ActionRowBuilder().addComponents(new ButtonBuilder().setCustomId(`gh:ceo:${uid}:hire`).setLabel(L(lang,'Send Offer','Gửi Offer')).setStyle(ButtonStyle.Success),new ButtonBuilder().setCustomId(`gh:ceo:${uid}:skip`).setLabel(L(lang,'Reject','Từ chối')).setStyle(ButtonStyle.Secondary))]};}
 if(a==='hire'){const x=c.lastCandidate;if(!x)return ceoPanel(c,lang,L(lang,'No active candidate.','Không có ứng viên đang chờ.'));const accept=Math.random()<Math.min(.92,.55+(x.salary/8000));if(accept){c.employees.push(x);c.monthlyCosts+=x.salary;c.reputation=Math.min(100,c.reputation+1);}c.lastCandidate=null;await c.save();return ceoPanel(c,lang,accept?L(lang,`✅ ${x.name} accepted the offer and joined as ${x.role}.`,`✅ ${x.name} đã nhận offer và gia nhập vị trí ${x.role}.`):L(lang,'❌ Candidate declined the offer.','❌ Ứng viên đã từ chối offer.'));}
 if(a==='skip'){c.lastCandidate=null;await c.save();return ceoPanel(c,lang,L(lang,'Candidate rejected. Search continues.','Đã từ chối ứng viên. Tiếp tục tìm người phù hợp.'));}
 if(a==='product'){const staff=Math.max(1,c.employees.length),cost=5000+staff*750;if(c.cash<cost)return ceoPanel(c,lang,L(lang,'Not enough cash for a product sprint.','Không đủ tiền cho sprint sản phẩm.'));c.cash-=cost;c.product=Math.min(100,c.product+5+staff*2);c.monthlyCosts=Math.max(c.monthlyCosts,1500+c.employees.reduce((n,x)=>n+x.salary,0));if(c.product>=25)c.stage=c.fundingRound?'GROWTH':'MVP';await c.save();return ceoPanel(c,lang,L(lang,`🛠️ Product sprint completed for ${money(cost)}.`,`🛠️ Hoàn thành sprint sản phẩm, chi phí ${money(cost)}.`));}
 if(a==='market'){const cost=10000;if(c.product<15)return ceoPanel(c,lang,L(lang,'Build a usable product first.','Hãy làm sản phẩm dùng được trước.'));if(c.cash<cost)return ceoPanel(c,lang,L(lang,'Not enough cash for a campaign.','Không đủ tiền chạy chiến dịch.'));c.cash-=cost;const gained=Math.floor((c.product/10)*(20+Math.random()*80));c.customers+=gained;c.revenue+=gained*(20+Math.floor(Math.random()*30));c.reputation=Math.min(100,c.reputation+2);await recalc(c);return ceoPanel(c,lang,L(lang,`📣 Campaign acquired ${gained} new customers.`,`📣 Chiến dịch mang về ${gained} khách hàng mới.`));}
 if(a==='finance'){if(c.product<20||c.customers<20)return ceoPanel(c,lang,L(lang,'Investors want an MVP and early traction first.','Nhà đầu tư muốn thấy MVP và traction ban đầu trước.'));const raise=Math.max(150000,Math.round(c.valuation*.25)),dilution=Math.min(18,8+c.fundingRound*2);c.cash+=raise;c.founderOwnership=Math.max(10,c.founderOwnership*(1-dilution/100));c.fundingRound++;c.stage=['SEED','SERIES A','SERIES B','SERIES C'][Math.min(3,c.fundingRound-1)];await recalc(c);return ceoPanel(c,lang,L(lang,`💰 Funding closed: ${money(raise)} raised for ${dilution}% dilution.`,`💰 Gọi vốn thành công: ${money(raise)}, pha loãng ${dilution}%.`));}
 if(a==='month'){c.months++;const payroll=c.monthlyCosts;c.cash+=c.revenue-payroll;const churn=Math.floor(c.customers*(Math.random()*.08));c.customers=Math.max(0,c.customers-churn);c.revenue=Math.max(0,c.revenue-Math.round(c.revenue*(churn/Math.max(1,c.customers+churn))));if(c.cash<0){c.reputation=Math.max(0,c.reputation-10);if(c.cash < -Math.max(50000,c.monthlyCosts*2)){c.stage='DISTRESSED';}}await recalc(c);return ceoPanel(c,lang,L(lang,`📅 Month ${c.months} closed. Payroll and operating results posted.`,`📅 Đã chốt tháng ${c.months}. Lương và kết quả kinh doanh đã được ghi nhận.`));}
 if(a==='ipo'){if(c.stage==='PUBLIC')return ceoPanel(c,lang,L(lang,'Company is already public.','Công ty đã niêm yết.'));const ok=c.revenue>=250000&&c.employees.length>=12&&c.product>=80&&c.valuation>=5000000&&c.months>=12;if(!ok)return ceoPanel(c,lang,L(lang,'IPO requirements: $250k+/mo revenue, 12+ employees, product 80+, $5M valuation and 12 months of operating history.','Điều kiện IPO: doanh thu $250k+/tháng, 12+ nhân viên, sản phẩm 80+, định giá $5M và ít nhất 12 tháng hoạt động.'));c.stage='PUBLIC';c.publicShares=1000000;c.stockPrice=Math.max(5,c.valuation/c.publicShares);c.founderOwnership*=.9;c.cash+=c.valuation*.1;await recalc(c);return ceoPanel(c,lang,L(lang,'🏦 IPO completed! The company is now publicly listed. The game continues with market capitalization and growth.','🏦 IPO thành công! Công ty đã niêm yết. Game tiếp tục với vốn hóa và tăng trưởng sau IPO.'));}
 return ceoPanel(c,lang);}
async function recalc(c){c.monthlyCosts=Math.max(c.monthlyCosts,c.employees.reduce((n,x)=>n+x.salary,0)+1500);const profit=c.revenue-c.monthlyCosts;c.valuation=Math.max(50000,Math.round(c.revenue*18+Math.max(0,profit)*24+c.product*15000+c.customers*250+c.reputation*5000));if(c.stage==='PUBLIC'&&c.publicShares)c.stockPrice=Math.max(.5,c.valuation/c.publicShares);await c.save();}
async function stats(uid,lang){const p=await GameHubProfile.findOne({userId:String(uid)}).lean();const best=p?.bestScores?Object.entries(p.bestScores).filter(([id])=>get(id)).sort((a,b)=>b[1]-a[1]).slice(0,10):[];return{embeds:[new EmbedBuilder().setTitle(L(lang,'📊 My Game Hub Stats','📊 Thống kê Game Hub')).setDescription(`${L(lang,'Games played','Lượt chơi')}: **${p?.gamesPlayed||0}**\n\n${best.map(([id,v],i)=>`${i+1}. ${get(id)?.emoji||'🎮'} ${L(lang,get(id)?.en||id,get(id)?.vi||id)} • **${v}**`).join('\n')||L(lang,'No scores yet.','Chưa có điểm.')}`)],components:[new ActionRowBuilder().addComponents(new ButtonBuilder().setCustomId(`gh:home:${uid}`).setLabel('Game Hub').setStyle(ButtonStyle.Secondary))]};}
async function handle(i,lang){const p=i.customId.split(':'),type=p[1],owner=p[2];if(String(i.user.id)!==String(owner))return i.reply({content:L(lang,'❌ This Game Hub belongs to another player.','❌ Game Hub này thuộc người chơi khác.'),flags:64});if(type==='ceocreate')return ceoCreateModal(i,lang);if(type==='ceosubmit')return ceoSubmit(i,lang);let r;if(type==='home')r=home(owner,lang);else if(type==='cat')r=category(owner,i.values[0],lang);else if(type==='pick')r=await play(owner,i.values[0],lang);else if(type==='play')r=await play(owner,p[3],lang);else if(type==='act')r=await action(owner,p[3],p[4],lang);else if(type==='finish'){const prof=await profile(owner),s=prof.gameStates.get(p[3]);r=s?await finishRun(owner,p[3],lang,s,false):await play(owner,p[3],lang);}else if(type==='stats')r=await stats(owner,lang);else if(type==='tour')r=await require('../services/tournamentService').playerPanel(owner,lang);else if(type==='market')r=await require('./market').home(owner,lang);else if(type==='season')r=await require('./seasonal').home(owner,lang);else if(type==='ceo')r=await ceoAction(owner,p[3],lang);if(r){if(i.isModalSubmit())return i.reply(r);return i.update(r);}}
module.exports={GAMES,get,home,category,play,action,stats,handle};
