const {
  EmbedBuilder,ActionRowBuilder,ButtonBuilder,ButtonStyle,ModalBuilder,TextInputBuilder,TextInputStyle,
  RoleSelectMenuBuilder,StringSelectMenuBuilder,ChannelSelectMenuBuilder,ChannelType,
  FileUploadBuilder,LabelBuilder
}=require('discord.js');
const CommunityPanel=require('../models/CommunityPanel');
const {premiumPanelVisual}=require('../services/premiumVisual');
const AMBER=0xF59E0B;
function L(s,en,vi){return s?.language==='vi'?vi:en;}
async function cfg(gid){return CommunityPanel.findOneAndUpdate({guildId:gid},{$setOnInsert:{guildId:gid}},{upsert:true,returnDocument:'after',setDefaultsOnInsert:true});}
async function home(guildId,s){const e=new EmbedBuilder().setColor(AMBER).setTitle('ðŸ§¡ Community Panel Center').setDescription(L(s,'Design and publish professional Welcome/Leave, Ticket and Reaction Role panels.','Thiáº¿t káº¿ vÃ  xuáº¥t báº£n Welcome/Leave, Ticket vÃ  Reaction Role chuyÃªn nghiá»‡p.'));const v=await premiumPanelVisual(guildId,e);return {embeds:[v.embed],files:v.files,components:[new ActionRowBuilder().addComponents(new ButtonBuilder().setCustomId('community:welcome').setLabel('Welcome / Leave').setEmoji('ðŸ‘‹').setStyle(ButtonStyle.Primary),new ButtonBuilder().setCustomId('community:ticket').setLabel('Ticket Center').setEmoji('ðŸŽ«').setStyle(ButtonStyle.Primary),new ButtonBuilder().setCustomId('community:reaction').setLabel('Reaction Role').setEmoji('ðŸŽ­').setStyle(ButtonStyle.Primary)),new ActionRowBuilder().addComponents(new ButtonBuilder().setCustomId('setup:home').setLabel(L(s,'Back','Quay láº¡i')).setEmoji('â¬…ï¸').setStyle(ButtonStyle.Secondary))]};}
function reactionMapText(c,s){const maps=c?.reaction?.mappings||[];if(!maps.length)return L(s,'No Emoji â†’ Role mappings configured.','ChÆ°a cáº¥u hÃ¬nh Emoji â†’ Role.');return maps.map((x,n)=>`${n+1}. ${x.emoji} â†’ <@&${x.roleId}>`).join('\n').slice(0,1024);}
async function page(guildId,kind,s,c={}){const names={welcome:'ðŸ‘‹ Welcome / Leave Builder',ticket:'ðŸŽ« Ticket Builder',reaction:'ðŸŽ­ Reaction Role Builder'};const e=new EmbedBuilder().setColor(AMBER).setTitle(names[kind]).setDescription(L(s,'Edit content â†’ preview â†’ publish. Supports corner thumbnail or large image.','Chá»‰nh ná»™i dung â†’ xem trÆ°á»›c â†’ xuáº¥t báº£n. Há»— trá»£ thumbnail gÃ³c pháº£i hoáº·c áº£nh lá»›n.'));
if(kind==='ticket')e.addFields({name:L(s,'Staff Role','Role Staff'),value:c?.ticket?.staffRoleId?`<@&${c.ticket.staffRoleId}>`:L(s,'Not configured','ChÆ°a cáº¥u hÃ¬nh'),inline:true},{name:L(s,'Staff notification','ThÃ´ng bÃ¡o Staff'),value:L(s,'Members can open tickets freely. The selected Staff Role is added to the private ticket channel and mentioned when a ticket opens. For push notifications, make the role mentionable.','Member má»Ÿ Ticket tá»± do. Role Staff Ä‘Æ°á»£c thÃªm vÃ o kÃªnh Ticket riÃªng tÆ° vÃ  Ä‘Æ°á»£c tag khi Ticket má»Ÿ. Muá»‘n Staff nháº­n thÃ´ng bÃ¡o, hÃ£y báº­t cho phÃ©p mention Role.'),inline:false});
if(kind==='reaction')e.addFields({name:L(s,'Target Channel','KÃªnh xuáº¥t báº£n'),value:c?.reaction?.panelChannelId?`<#${c.reaction.panelChannelId}>`:L(s,'Current channel when publishing','KÃªnh hiá»‡n táº¡i khi Publish'),inline:true},{name:L(s,'Mappings','LiÃªn káº¿t Emoji â†’ Role'),value:reactionMapText(c,s)});
const first=new ActionRowBuilder().addComponents(new ButtonBuilder().setCustomId(`community:${kind}:edit`).setLabel(L(s,'Edit Content','Chá»‰nh ná»™i dung')).setStyle(ButtonStyle.Primary),...(kind==='welcome'?[new ButtonBuilder().setCustomId('community:leave:edit').setLabel(L(s,'Edit Leave','Chá»‰nh Leave')).setStyle(ButtonStyle.Primary)]:[]),new ButtonBuilder().setCustomId(`community:${kind}:preview`).setLabel(L(s,'Preview','Xem trÆ°á»›c')).setStyle(ButtonStyle.Secondary),new ButtonBuilder().setCustomId(`community:${kind}:publish`).setLabel(L(s,'Publish','Xuáº¥t báº£n')).setStyle(ButtonStyle.Success));
const rows=[first];
if(kind==='ticket')rows.push(new ActionRowBuilder().addComponents(new ButtonBuilder().setCustomId('community:ticket:staff').setLabel(L(s,'Set Staff Role','Chá»n Role Staff')).setEmoji('ðŸ›¡ï¸').setStyle(ButtonStyle.Secondary)));
if(kind==='reaction')rows.push(new ActionRowBuilder().addComponents(new ButtonBuilder().setCustomId('community:reaction:add').setLabel(L(s,'Add Emoji â†’ Role','ThÃªm Emoji â†’ Role')).setEmoji('âž•').setStyle(ButtonStyle.Primary),new ButtonBuilder().setCustomId('community:reaction:remove').setLabel(L(s,'Remove Mapping','XÃ³a liÃªn káº¿t')).setEmoji('âž–').setStyle(ButtonStyle.Secondary),new ButtonBuilder().setCustomId('community:reaction:channel').setLabel(L(s,'Set Channel','Chá»n kÃªnh')).setEmoji('ðŸ“¡').setStyle(ButtonStyle.Secondary)));
rows.push(new ActionRowBuilder().addComponents(new ButtonBuilder().setCustomId('community:home').setLabel(L(s,'Back','Quay láº¡i')).setStyle(ButtonStyle.Secondary)));
const v=await premiumPanelVisual(guildId,e);return {embeds:[v.embed],components:rows,files:v.files};}
function modal(kind,c,s={language:'en'}){
  const m=new ModalBuilder().setCustomId(`community:modal:${kind}`).setTitle(`${kind} Builder - UPLOAD-V2`);
  const vals=kind==='welcome'?c.welcome:kind==='leave'?c.leave:c[kind]||{};
  for(const [id,en,vi,style,max] of [['title','Title','TiÃªu Ä‘á»',TextInputStyle.Short,100],['description','Description / message','MÃ´ táº£ / ná»™i dung',TextInputStyle.Paragraph,1000],['footer','Footer (optional)','Footer (tÃ¹y chá»n)',TextInputStyle.Short,200]]){
    const x=new TextInputBuilder().setCustomId(id).setLabel(L(s,en,vi)).setStyle(style).setRequired(id==='title'||id==='description').setMaxLength(max);
    if(vals?.[id])x.setValue(vals[id]);
    m.addComponents(new ActionRowBuilder().addComponents(x));
  }
  m.addComponents(
    new LabelBuilder().setLabel(L(s,'Thumbnail image (optional)','áº¢nh thumbnail (tÃ¹y chá»n)')).setDescription(L(s,'Upload a replacement image. Leave empty to keep the current one.','ÄÃ­nh kÃ¨m áº£nh má»›i Ä‘á»ƒ thay tháº¿. Äá»ƒ trá»‘ng Ä‘á»ƒ giá»¯ áº£nh hiá»‡n táº¡i.')).setFileUploadComponent(new FileUploadBuilder().setCustomId('thumbnailFile').setRequired(false).setMinValues(0).setMaxValues(1)),
    new LabelBuilder().setLabel(L(s,'Large image (optional)','áº¢nh lá»›n (tÃ¹y chá»n)')).setDescription(L(s,'Upload a replacement image. Leave empty to keep the current one.','ÄÃ­nh kÃ¨m áº£nh má»›i Ä‘á»ƒ thay tháº¿. Äá»ƒ trá»‘ng Ä‘á»ƒ giá»¯ áº£nh hiá»‡n táº¡i.')).setFileUploadComponent(new FileUploadBuilder().setCustomId('imageFile').setRequired(false).setMinValues(0).setMaxValues(1))
  );
  return m;
}
function ticketStaffRolePicker(s){return new ActionRowBuilder().addComponents(new RoleSelectMenuBuilder().setCustomId('community:ticket:staffpick').setPlaceholder(L(s,'Choose the Staff Role','Chá»n Role Staff')).setMinValues(1).setMaxValues(1));}
function reactionRolePicker(s){return new ActionRowBuilder().addComponents(new RoleSelectMenuBuilder().setCustomId('community:reaction:rolepick').setPlaceholder(L(s,'Choose the role to grant','Chá»n Role sáº½ Ä‘Æ°á»£c cáº¥p')).setMinValues(1).setMaxValues(1));}
function reactionEmojiModal(roleId,s){const input=new TextInputBuilder().setCustomId('emoji').setLabel(L(s,'Emoji (Unicode or custom emoji)','Emoji (Unicode hoáº·c custom emoji)')).setPlaceholder('ðŸŽ®  or  <:corgi:123456789012345678>').setStyle(TextInputStyle.Short).setRequired(true).setMaxLength(100);return new ModalBuilder().setCustomId(`community:reaction:emoji:${roleId}`).setTitle(L(s,'Add Reaction Role','ThÃªm Reaction Role')).addComponents(new ActionRowBuilder().addComponents(input));}
function reactionRemoveMenu(c,s){const maps=c?.reaction?.mappings||[];if(!maps.length)return null;return new ActionRowBuilder().addComponents(new StringSelectMenuBuilder().setCustomId('community:reaction:removeSelect').setPlaceholder(L(s,'Choose a mapping to remove','Chá»n liÃªn káº¿t cáº§n xÃ³a')).setMinValues(1).setMaxValues(1).addOptions(maps.slice(0,20).map((x,n)=>({label:`${n+1}. ${x.emoji}`.slice(0,100),value:String(n),description:`Role ${x.roleId}`}))));}
function reactionChannelPicker(s){return new ActionRowBuilder().addComponents(new ChannelSelectMenuBuilder().setCustomId('community:reaction:channelpick').setPlaceholder(L(s,'Choose panel channel','Chá»n kÃªnh Ä‘Äƒng panel')).setChannelTypes(ChannelType.GuildText,ChannelType.GuildAnnouncement).setMinValues(1).setMaxValues(1));}
module.exports={cfg,home,page,modal,ticketStaffRolePicker,reactionRolePicker,reactionEmojiModal,reactionRemoveMenu,reactionChannelPicker,reactionMapText};

