const {
  EmbedBuilder,ActionRowBuilder,ButtonBuilder,ButtonStyle,ModalBuilder,TextInputBuilder,TextInputStyle,
  RoleSelectMenuBuilder,StringSelectMenuBuilder,ChannelSelectMenuBuilder,ChannelType
}=require('discord.js');
const CommunityPanel=require('../models/CommunityPanel');
const {premiumPanelVisual}=require('../services/premiumVisual');
const AMBER=0xF59E0B;
function L(s,en,vi){return s?.language==='vi'?vi:en;}
async function cfg(gid){return CommunityPanel.findOneAndUpdate({guildId:gid},{$setOnInsert:{guildId:gid}},{upsert:true,returnDocument:'after',setDefaultsOnInsert:true});}
async function home(guildId,s){const e=new EmbedBuilder().setColor(AMBER).setTitle('🧡 Community Panel Center').setDescription(L(s,'Design and publish professional Welcome/Leave, Ticket and Reaction Role panels.','Thiết kế và xuất bản Welcome/Leave, Ticket và Reaction Role chuyên nghiệp.'));const v=await premiumPanelVisual(guildId,e);return {embeds:[v.embed],files:v.files,components:[new ActionRowBuilder().addComponents(new ButtonBuilder().setCustomId('community:welcome').setLabel('Welcome / Leave').setEmoji('👋').setStyle(ButtonStyle.Primary),new ButtonBuilder().setCustomId('community:ticket').setLabel('Ticket Center').setEmoji('🎫').setStyle(ButtonStyle.Primary),new ButtonBuilder().setCustomId('community:reaction').setLabel('Reaction Role').setEmoji('🎭').setStyle(ButtonStyle.Primary)),new ActionRowBuilder().addComponents(new ButtonBuilder().setCustomId('setup:home').setLabel(L(s,'Back','Quay lại')).setEmoji('⬅️').setStyle(ButtonStyle.Secondary))]};}
function reactionMapText(c,s){const maps=c?.reaction?.mappings||[];if(!maps.length)return L(s,'No Emoji → Role mappings configured.','Chưa cấu hình Emoji → Role.');return maps.map((x,n)=>`${n+1}. ${x.emoji} → <@&${x.roleId}>`).join('\n').slice(0,1024);}
async function page(guildId,kind,s,c={}){const names={welcome:'👋 Welcome / Leave Builder',ticket:'🎫 Ticket Builder',reaction:'🎭 Reaction Role Builder'};const e=new EmbedBuilder().setColor(AMBER).setTitle(names[kind]).setDescription(L(s,'Edit content → preview → publish. Supports corner thumbnail or large image.','Chỉnh nội dung → xem trước → xuất bản. Hỗ trợ thumbnail góc phải hoặc ảnh lớn.'));
if(kind==='reaction')e.addFields({name:L(s,'Target Channel','Kênh xuất bản'),value:c?.reaction?.panelChannelId?`<#${c.reaction.panelChannelId}>`:L(s,'Current channel when publishing','Kênh hiện tại khi Publish'),inline:true},{name:L(s,'Mappings','Liên kết Emoji → Role'),value:reactionMapText(c,s)});
const first=new ActionRowBuilder().addComponents(new ButtonBuilder().setCustomId(`community:${kind}:edit`).setLabel(L(s,'Edit Content','Chỉnh nội dung')).setStyle(ButtonStyle.Primary),...(kind==='welcome'?[new ButtonBuilder().setCustomId('community:leave:edit').setLabel(L(s,'Edit Leave','Chỉnh Leave')).setStyle(ButtonStyle.Primary)]:[]),new ButtonBuilder().setCustomId(`community:${kind}:preview`).setLabel(L(s,'Preview','Xem trước')).setStyle(ButtonStyle.Secondary),new ButtonBuilder().setCustomId(`community:${kind}:publish`).setLabel(L(s,'Publish','Xuất bản')).setStyle(ButtonStyle.Success));
const rows=[first];
if(kind==='reaction')rows.push(new ActionRowBuilder().addComponents(new ButtonBuilder().setCustomId('community:reaction:add').setLabel(L(s,'Add Emoji → Role','Thêm Emoji → Role')).setEmoji('➕').setStyle(ButtonStyle.Primary),new ButtonBuilder().setCustomId('community:reaction:remove').setLabel(L(s,'Remove Mapping','Xóa liên kết')).setEmoji('➖').setStyle(ButtonStyle.Secondary),new ButtonBuilder().setCustomId('community:reaction:channel').setLabel(L(s,'Set Channel','Chọn kênh')).setEmoji('📡').setStyle(ButtonStyle.Secondary)));
rows.push(new ActionRowBuilder().addComponents(new ButtonBuilder().setCustomId('community:home').setLabel(L(s,'Back','Quay lại')).setStyle(ButtonStyle.Secondary)));
const v=await premiumPanelVisual(guildId,e);return {embeds:[v.embed],components:rows,files:v.files};}
function modal(kind,c,s={language:'en'}){const m=new ModalBuilder().setCustomId(`community:modal:${kind}`).setTitle(kind==='reaction'?L(s,'Reaction Role Builder','Reaction Role Builder'):`${kind} Builder`);const vals=kind==='welcome'?c.welcome:kind==='leave'?c.leave:c[kind]||{};for(const [id,en,vi,style,max] of [['title','Title','Tiêu đề',TextInputStyle.Short,100],['description','Description / message','Mô tả / nội dung',TextInputStyle.Paragraph,1000],['thumbnailUrl','Thumbnail URL (optional)','URL Thumbnail (tùy chọn)',TextInputStyle.Short,500],['imageUrl','Large image URL (optional)','URL ảnh lớn (tùy chọn)',TextInputStyle.Short,500],['footer','Footer (optional)','Footer (tùy chọn)',TextInputStyle.Short,200]]){const x=new TextInputBuilder().setCustomId(id).setLabel(L(s,en,vi)).setStyle(style).setRequired(id==='title'||id==='description').setMaxLength(max);if(vals?.[id])x.setValue(vals[id]);m.addComponents(new ActionRowBuilder().addComponents(x));}return m;}
function reactionRolePicker(s){return new ActionRowBuilder().addComponents(new RoleSelectMenuBuilder().setCustomId('community:reaction:rolepick').setPlaceholder(L(s,'Choose the role to grant','Chọn Role sẽ được cấp')).setMinValues(1).setMaxValues(1));}
function reactionEmojiModal(roleId,s){const input=new TextInputBuilder().setCustomId('emoji').setLabel(L(s,'Emoji (Unicode or custom emoji)','Emoji (Unicode hoặc custom emoji)')).setPlaceholder('🎮  or  <:corgi:123456789012345678>').setStyle(TextInputStyle.Short).setRequired(true).setMaxLength(100);return new ModalBuilder().setCustomId(`community:reaction:emoji:${roleId}`).setTitle(L(s,'Add Reaction Role','Thêm Reaction Role')).addComponents(new ActionRowBuilder().addComponents(input));}
function reactionRemoveMenu(c,s){const maps=c?.reaction?.mappings||[];if(!maps.length)return null;return new ActionRowBuilder().addComponents(new StringSelectMenuBuilder().setCustomId('community:reaction:removeSelect').setPlaceholder(L(s,'Choose a mapping to remove','Chọn liên kết cần xóa')).setMinValues(1).setMaxValues(1).addOptions(maps.slice(0,20).map((x,n)=>({label:`${n+1}. ${x.emoji}`.slice(0,100),value:String(n),description:`Role ${x.roleId}`}))));}
function reactionChannelPicker(s){return new ActionRowBuilder().addComponents(new ChannelSelectMenuBuilder().setCustomId('community:reaction:channelpick').setPlaceholder(L(s,'Choose panel channel','Chọn kênh đăng panel')).setChannelTypes(ChannelType.GuildText,ChannelType.GuildAnnouncement).setMinValues(1).setMaxValues(1));}
module.exports={cfg,home,page,modal,reactionRolePicker,reactionEmojiModal,reactionRemoveMenu,reactionChannelPicker,reactionMapText};
