const {EmbedBuilder,ActionRowBuilder,ButtonBuilder,ButtonStyle,ModalBuilder,TextInputBuilder,TextInputStyle}=require('discord.js');const Reward=require('../models/GuildReward');const Mission=require('../models/GuildMission');const Event=require('../models/GuildEvent');const Econ=require('../models/GuildEconomy');const {t}=require('../services/i18n');
function inp(id,label,placeholder,style=TextInputStyle.Short){return new ActionRowBuilder().addComponents(new TextInputBuilder().setCustomId(id).setLabel(label).setPlaceholder(placeholder).setStyle(style).setRequired(true));}
async function shop(gid,lang){const rows=await Reward.find({guildId:gid,enabled:true}).sort({price:1}).limit(20).lean();return{embeds:[new EmbedBuilder().setColor(0xf6c65b).setTitle(t(lang,'v6.guildShop.title')).setDescription(rows.length?rows.map(x=>`**${x.name}** • ${x.price.toLocaleString()} 🌟 • ${x.type} • ${x.stock<0?'∞':x.stock}\n\`${x._id}\``).join('\n'):t(lang,'v6.guildShop.empty'))],components:[new ActionRowBuilder().addComponents(new ButtonBuilder().setCustomId('guild:redeem').setLabel(t(lang,'v6.guildShop.redeem')).setEmoji('🎁').setStyle(ButtonStyle.Success),new ButtonBuilder().setCustomId('guild:home').setLabel(t(lang,'v6.common.back')).setStyle(ButtonStyle.Secondary))]};}
async function missions(gid,lang){const rows=await Mission.find({guildId:gid,enabled:true,endsAt:{$gt:new Date()}}).sort({endsAt:1}).limit(15).lean();return{embeds:[new EmbedBuilder().setColor(0x7c5cff).setTitle(t(lang,'v6.guildMissions.title')).setDescription(rows.length?rows.map(x=>`**${x.name}** • ${x.target} ${x.metric} • +${x.rewardPoints} 🌟 • <t:${Math.floor(x.endsAt.getTime()/1000)}:R>`).join('\n'):t(lang,'v6.guildMissions.empty'))],components:[new ActionRowBuilder().addComponents(new ButtonBuilder().setCustomId('guild:home').setLabel(t(lang,'v6.common.back')).setStyle(ButtonStyle.Secondary))]};}
async function ranking(gid,lang){const rows=await Econ.find({guildId:gid}).sort({points:-1}).limit(10).lean();return{embeds:[new EmbedBuilder().setColor(0xf6c65b).setTitle(t(lang,'v6.guildRanking.title')).setDescription(rows.length?rows.map((x,n)=>`**#${n+1}** <@${x.userId}> • ${x.points.toLocaleString()} 🌟`).join('\n'):t(lang,'v6.guildRanking.empty'))],components:[new ActionRowBuilder().addComponents(new ButtonBuilder().setCustomId('guild:home').setLabel(t(lang,'v6.common.back')).setStyle(ButtonStyle.Secondary))]};}
function admin(lang){return{embeds:[new EmbedBuilder().setColor(0xffa64d).setTitle(t(lang,'v6.guildAdmin.title')).setDescription(t(lang,'v6.guildAdmin.desc'))],components:[new ActionRowBuilder().addComponents(new ButtonBuilder().setCustomId('guild:admin:reward').setLabel(t(lang,'v6.guildAdmin.createReward')).setEmoji('🎁').setStyle(ButtonStyle.Primary),new ButtonBuilder().setCustomId('guild:admin:mission').setLabel(t(lang,'v6.guildAdmin.createMission')).setEmoji('🎯').setStyle(ButtonStyle.Primary),new ButtonBuilder().setCustomId('guild:admin:event').setLabel(t(lang,'v6.guildAdmin.scheduleEvent')).setEmoji('📅').setStyle(ButtonStyle.Secondary),new ButtonBuilder().setCustomId('guild:admin:points').setLabel(t(lang,'v6.guildAdmin.adjust')).setStyle(ButtonStyle.Secondary)),new ActionRowBuilder().addComponents(new ButtonBuilder().setCustomId('guild:home').setLabel(t(lang,'v6.common.back')).setStyle(ButtonStyle.Secondary))]};}
function rewardModal(){return new ModalBuilder().setCustomId('guild:modal:reward').setTitle('Create Guild Reward').addComponents(inp('name','Reward name','Mystery Box'),inp('type','Type','ROLE / TITLE / DIGITAL / PHYSICAL / MYSTERY'),inp('price','Price in Guild Points','5000'),inp('stock','Stock (-1 = unlimited)','10'),inp('roleId','Role ID (ROLE only, otherwise -)','-'));}
function redeemModal(){return new ModalBuilder().setCustomId('guild:modal:redeem').setTitle('Redeem Guild Reward').addComponents(inp('rewardId','Reward ID','Paste ID from Guild Shop'));}
function missionModal(){return new ModalBuilder().setCustomId('guild:modal:mission').setTitle('Create Guild Mission').addComponents(inp('name','Mission name','Weekend Activity'),inp('metric','Metric','MESSAGES / GAMES / WINS / MARKET / FISHING'),inp('target','Target','50'),inp('reward','Reward Guild Points','1000'),inp('hours','Duration hours','168'));}
function eventModal(){return new ModalBuilder().setCustomId('guild:modal:event').setTitle('Schedule Guild Event').addComponents(inp('name','Event name','Weekend Game Night'),inp('description','Description','Play together this weekend',TextInputStyle.Paragraph),inp('start','Starts at ISO','2026-10-01T18:00:00-04:00'),inp('end','Ends at ISO','2026-10-02T18:00:00-04:00'),inp('reward','Participation reward 🌟','500'));}
function pointsModal(){return new ModalBuilder().setCustomId('guild:modal:points').setTitle('Adjust Guild Points').addComponents(inp('userId','Discord User ID','123456789012345678'),inp('amount','Amount (+ or -)','1000'));}
module.exports={shop,missions,ranking,admin,rewardModal,redeemModal,missionModal,eventModal,pointsModal};
