const {EmbedBuilder,ActionRowBuilder,ButtonBuilder,ButtonStyle,StringSelectMenuBuilder,ChannelSelectMenuBuilder,ChannelType,ModalBuilder,TextInputBuilder,TextInputStyle}=require('discord.js');
const {getActivePremium}=require('../services/premium');
const MODULES={giveaway:['🎉 Giveaway','🎉 Giveaway'],reactionRole:['🎭 Reaction Role','🎭 Reaction Role'],stats:['📊 Server Stats','📊 Thống kê Server'],welcome:['👋 Welcome / Leave','👋 Chào mừng / Rời server'],ticket:['🎫 Ticket','🎫 Hỗ trợ Ticket'],moderation:['🛡️ Moderation','🛡️ Kiểm duyệt'],poll:['📊 Poll','📊 Bình chọn'],logs:['📜 Server Logs','📜 Nhật ký Server'],contest:['🏆 Contest / Event','🏆 Cuộc thi / Sự kiện'],economy:['⭐ Economy','⭐ Kinh tế 🌟Cstar'],premium:['💎 Premium','💎 Premium'],pet:['🐾 Pet Game — Coming Soon','🐾 Pet Game — Sắp ra mắt'],ai:['🤖 AI (Free)','🤖 AI (Miễn phí)'],games:['🎮 Economy Games','🎮 Trò chơi 🌟Cstar']};
function L(s,en,vi){return s.language==='vi'?vi:en}
function moduleName(s,k){const v=MODULES[k]||[k,k];return L(s,v[0],v[1]);}
function back(s){return new ActionRowBuilder().addComponents(new ButtonBuilder().setCustomId('setup:home').setLabel(L(s,'Back to Control Center','Quay lại Trung tâm điều khiển')).setEmoji('⬅️').setStyle(ButtonStyle.Secondary));}
async function buildSetupHome(guild,s){const p=await getActivePremium(guild.id);const available=Object.keys(MODULES).filter(k=>k!=='pet');const on=available.filter(k=>s.modules[k]).length;const e=new EmbedBuilder().setTitle(L(s,'🎮 CORGI-BOT • CONTROL CENTER','🎮 CORGI-BOT • TRUNG TÂM ĐIỀU KHIỂN')).setDescription(L(s,'Configure the entire server from one interactive gaming control center.','Cấu hình toàn bộ server trong một trung tâm điều khiển gaming tương tác.')).addFields(
{name:L(s,'🌐 Language','🌐 Ngôn ngữ'),value:s.language==='vi'?'🇻🇳 Tiếng Việt':'🇺🇸 English',inline:true},
{name:L(s,'⚡ Modules','⚡ Tính năng'),value:L(s,`${on}/${available.length} enabled • Pet Coming Soon`,`${on}/${available.length} đang bật • Pet sắp ra mắt`),inline:true},
{name:'💎 Premium',value:p?L(s,`ACTIVE • <t:${Math.floor(p.expiresAt/1000)}:R>`,`ĐANG HOẠT ĐỘNG • <t:${Math.floor(p.expiresAt/1000)}:R>`):L(s,'FREE','MIỄN PHÍ'),inline:true},
{name:L(s,'🧩 Quick status','🧩 Trạng thái nhanh'),value:Object.keys(MODULES).map(k=>k==='pet'?`🔒 ${moduleName(s,k)}`:`${s.modules[k]?'🟢':'⚫'} ${moduleName(s,k)}`).join('\n').slice(0,1024)}
).setFooter({text:L(s,'Corgi Studio • Server Configuration 4.0','Corgi Studio • Cấu hình Server 4.0')}).setTimestamp();
const menu=new StringSelectMenuBuilder().setCustomId('setup:page').setPlaceholder(L(s,'Choose configuration category','Chọn danh mục cấu hình')).addOptions([
{label:L(s,'Modules','Tính năng'),value:'modules',emoji:'🧩',description:L(s,'Enable or disable bot systems','Bật hoặc tắt các hệ thống của bot')},
{label:L(s,'Channels','Kênh'),value:'channels',emoji:'📡',description:L(s,'Welcome, logs, stats and ticket channels','Kênh chào mừng, log, thống kê và ticket')},
{label:L(s,'Premium & Branding','Premium & Thương hiệu'),value:'premium',emoji:'💎',description:L(s,'Premium status and customization','Trạng thái Premium và tùy chỉnh')},
{label:L(s,'Language','Ngôn ngữ'),value:'language',emoji:'🌐',description:'English / Tiếng Việt'}]);
return {embeds:[e],components:[new ActionRowBuilder().addComponents(menu),new ActionRowBuilder().addComponents(new ButtonBuilder().setCustomId('setup:refresh').setLabel(L(s,'Refresh','Làm mới')).setEmoji('🔄').setStyle(ButtonStyle.Secondary),new ButtonBuilder().setCustomId('setup:close').setLabel(L(s,'Close','Đóng')).setEmoji('✖️').setStyle(ButtonStyle.Danger))]};}
function buildModules(s){const e=new EmbedBuilder().setTitle(L(s,'🧩 Module Manager','🧩 Quản lý tính năng')).setDescription(L(s,'Select an available module below to toggle it immediately. Pet Game is locked as Coming Soon.','Chọn tính năng bên dưới để bật/tắt ngay. Pet Game đang khóa ở trạng thái Sắp ra mắt.')).addFields({name:L(s,'Current state','Trạng thái hiện tại'),value:Object.keys(MODULES).map(k=>k==='pet'?`🔒 ${L(s,'LOCKED','ĐÃ KHÓA')} • ${moduleName(s,k)}`:`${s.modules[k]?L(s,'🟢 ON','🟢 BẬT'):L(s,'⚫ OFF','⚫ TẮT')} • ${moduleName(s,k)}`).join('\n')});const menu=new StringSelectMenuBuilder().setCustomId('setup:toggle').setPlaceholder(L(s,'Toggle an available module','Bật/tắt một tính năng')).addOptions(Object.keys(MODULES).filter(k=>k!=='pet').map(k=>({label:moduleName(s,k).replace(/^.. /,''),value:k,description:s.modules[k]?L(s,'Currently enabled','Hiện đang bật'):L(s,'Currently disabled','Hiện đang tắt')})));return {embeds:[e],components:[new ActionRowBuilder().addComponents(menu),back(s)]};}
function buildChannels(s){const not=L(s,'Not set','Chưa đặt');const e=new EmbedBuilder().setTitle(L(s,'📡 Channel Configuration','📡 Cấu hình kênh')).setDescription(L(s,'Choose the destination used by each system.','Chọn kênh đích cho từng hệ thống.')).addFields({name:L(s,'Welcome','Chào mừng'),value:s.channels?.welcome?`<#${s.channels.welcome}>`:not,inline:true},{name:L(s,'Leave','Rời server'),value:s.channels?.leave?`<#${s.channels.leave}>`:not,inline:true},{name:L(s,'Server Logs','Nhật ký Server'),value:s.channels?.logs?`<#${s.channels.logs}>`:not,inline:true},{name:L(s,'Stats Category','Danh mục thống kê'),value:s.channels?.stats?`<#${s.channels.stats}>`:L(s,'Auto-create with /stats','Tự tạo bằng /stats'),inline:true},{name:L(s,'Ticket Category','Danh mục Ticket'),value:s.channels?.ticketCategory?`<#${s.channels.ticketCategory}>`:not,inline:true});const which=new StringSelectMenuBuilder().setCustomId('setup:channelkey').setPlaceholder(L(s,'1. Select what you want to configure','1. Chọn mục muốn cấu hình')).addOptions([{label:L(s,'Welcome channel','Kênh chào mừng'),value:'welcome',emoji:'👋'},{label:L(s,'Leave channel','Kênh rời server'),value:'leave',emoji:'🚪'},{label:L(s,'Server log channel','Kênh nhật ký server'),value:'logs',emoji:'📜'},{label:L(s,'Stats category','Danh mục thống kê'),value:'stats',emoji:'📊'},{label:L(s,'Ticket category','Danh mục Ticket'),value:'ticketCategory',emoji:'🎫'}]);return {embeds:[e],components:[new ActionRowBuilder().addComponents(which),back(s)]};}
function channelPicker(key,s={language:'en'}){const category=key==='ticketCategory'||key==='stats';const picker=new ChannelSelectMenuBuilder().setCustomId(`setup:setchannel:${key}`).setPlaceholder(key==='stats'?L(s,'2. Choose stats category','2. Chọn danh mục thống kê'):category?L(s,'2. Choose ticket category','2. Chọn danh mục Ticket'):L(s,'2. Choose channel','2. Chọn kênh')).setMinValues(1).setMaxValues(1).setChannelTypes(category?[ChannelType.GuildCategory]:[ChannelType.GuildText,ChannelType.GuildAnnouncement]);return new ActionRowBuilder().addComponents(picker);}
async function buildPremium(guild,s){const p=await getActivePremium(guild.id);const e=new EmbedBuilder().setTitle(L(s,'💎 Premium & Branding','💎 Premium & Thương hiệu')).setDescription(p?L(s,'Premium customization is unlocked for this server.','Tùy chỉnh Premium đã được mở khóa cho server này.'):L(s,'This server is on Free. Redeem a Premium CD Key to unlock branding controls.','Server đang ở gói Miễn phí. Hãy nhập CD Key Premium để mở khóa tùy chỉnh thương hiệu.')).addFields({name:L(s,'Status','Trạng thái'),value:p?`💎 ${L(s,'ACTIVE','ĐANG HOẠT ĐỘNG')}\n${L(s,'Expires','Hết hạn')}: <t:${Math.floor(p.expiresAt/1000)}:F>`:`🆓 ${L(s,'FREE','MIỄN PHÍ')}`},{name:L(s,'Premium customization','Tùy chỉnh Premium'),value:L(s,`• Custom bot nickname\n• Custom bot avatar URL\n• Bot emoji theme\n• Corgi Studio exclusive emoji: **${s.premiumBranding?.useCorgiStudioEmoji?'ON':'OFF'}**\n• Corgi Studio exclusive emoji access`,`• Tên hiển thị bot tùy chỉnh\n• URL avatar bot tùy chỉnh\n• Chủ đề emoji bot\n• Emoji độc quyền Corgi Studio: **${s.premiumBranding?.useCorgiStudioEmoji?'BẬT':'TẮT'}**\n• Quyền sử dụng emoji độc quyền Corgi Studio`)});const row=new ActionRowBuilder().addComponents(new ButtonBuilder().setCustomId('setup:premium:name').setLabel(L(s,'Bot Name','Tên Bot')).setEmoji('✏️').setStyle(ButtonStyle.Primary).setDisabled(!p),new ButtonBuilder().setCustomId('setup:premium:avatar').setLabel('Avatar').setEmoji('🖼️').setStyle(ButtonStyle.Primary).setDisabled(!p),new ButtonBuilder().setCustomId('setup:premium:emoji').setLabel(L(s,'Emoji Theme','Chủ đề Emoji')).setEmoji('✨').setStyle(ButtonStyle.Secondary).setDisabled(!p),new ButtonBuilder().setCustomId('setup:premium:corgiEmoji').setLabel('Corgi Emoji').setEmoji('🐶').setStyle(ButtonStyle.Success).setDisabled(!p));return {embeds:[e],components:[row,back(s)]};}
function buildLanguage(s){const e=new EmbedBuilder().setTitle(L(s,'🌐 Language','🌐 Ngôn ngữ')).setDescription(L(s,'Select the server interface language. Bot responses, menus and supported feature messages will follow this setting.','Chọn ngôn ngữ giao diện server. Phản hồi bot, menu và thông báo tính năng được hỗ trợ sẽ đồng bộ theo cài đặt này.'));const menu=new StringSelectMenuBuilder().setCustomId('setup:setlanguage').setPlaceholder(L(s,'Choose language','Chọn ngôn ngữ')).addOptions([{label:'English',value:'en',emoji:'🇺🇸',default:s.language==='en'},{label:'Tiếng Việt',value:'vi',emoji:'🇻🇳',default:s.language==='vi'}]);return {embeds:[e],components:[new ActionRowBuilder().addComponents(menu),back(s)]};}
function premiumModal(kind,current='',s={language:'en'}){const modal=new ModalBuilder().setCustomId(`setup:premiumModal:${kind}`).setTitle(kind==='name'?L(s,'Premium • Bot Name','Premium • Tên Bot'):kind==='avatar'?L(s,'Premium • Bot Avatar','Premium • Avatar Bot'):L(s,'Premium • Emoji Theme','Premium • Chủ đề Emoji'));const input=new TextInputBuilder().setCustomId('value').setLabel(kind==='name'?L(s,'New bot nickname','Tên hiển thị bot mới'):kind==='avatar'?'HTTPS image URL':L(s,'Emoji theme name','Tên chủ đề emoji')).setStyle(TextInputStyle.Short).setRequired(true).setMaxLength(kind==='avatar'?500:kind==='name'?32:50);if(current)input.setValue(current);return modal.addComponents(new ActionRowBuilder().addComponents(input));}
module.exports={MODULES,buildSetupHome,buildModules,buildChannels,buildPremium,buildLanguage,channelPicker,premiumModal};
