const {EmbedBuilder,ActionRowBuilder,ButtonBuilder,ButtonStyle,StringSelectMenuBuilder,ChannelSelectMenuBuilder,ChannelType,ModalBuilder,TextInputBuilder,TextInputStyle}=require('discord.js');
const {getActivePremium}=require('../services/premium');
const MODULES={giveaway:'🎉 Giveaway',reactionRole:'🎭 Reaction Role',stats:'📊 Stats Server',welcome:'👋 Welcome / Leave',ticket:'🎫 Ticket',moderation:'🛡️ Moderation',poll:'📊 Poll',logs:'📜 Server Logs',contest:'🏆 Contest / Event',economy:'⭐ Economy',premium:'💎 Premium',pet:'🐾 Pet Game — Coming Soon',ai:'🤖 AI (Free)',games:'🎮 Economy Games'};
function lang(s,en,vi){return s.language==='vi'?vi:en}
async function buildSetupHome(guild,s){const p=await getActivePremium(guild.id); const available=Object.keys(MODULES).filter(k=>k!=='pet'); const on=available.filter(k=>s.modules[k]).length; const e=new EmbedBuilder().setTitle('🎮 CORGI-BOT • CONTROL CENTER').setDescription(lang(s,'Configure the server from one interactive gaming control center.','Cấu hình toàn bộ server trong một trung tâm điều khiển gaming tương tác.')).addFields({name:'🌐 Language',value:s.language==='vi'?'🇻🇳 Tiếng Việt':'🇺🇸 English',inline:true},{name:'⚡ Modules',value:`${on}/${available.length} enabled • Pet Coming Soon`,inline:true},{name:'💎 Premium',value:p?`ACTIVE • <t:${Math.floor(p.expiresAt/1000)}:R>`:'FREE',inline:true},{name:'🧩 Quick status',value:Object.entries(MODULES).map(([k,n])=>k==='pet'?`🔒 ${n}`:`${s.modules[k]?'🟢':'⚫'} ${n}`).join('\n').slice(0,1024)}).setFooter({text:'Corgi Studio • Server Configuration 4.0'}).setTimestamp();
const menu=new StringSelectMenuBuilder().setCustomId('setup:page').setPlaceholder(lang(s,'Choose configuration category','Chọn danh mục cấu hình')).addOptions([{label:'Modules',value:'modules',emoji:'🧩',description:'Enable or disable bot systems'},{label:'Channels',value:'channels',emoji:'📡',description:'Welcome, logs, stats and ticket channels'},{label:'Premium & Branding',value:'premium',emoji:'💎',description:'Premium status and customization'},{label:'Language',value:'language',emoji:'🌐',description:'English / Tiếng Việt'}]);
return {embeds:[e],components:[new ActionRowBuilder().addComponents(menu),new ActionRowBuilder().addComponents(new ButtonBuilder().setCustomId('setup:refresh').setLabel('Refresh').setEmoji('🔄').setStyle(ButtonStyle.Secondary),new ButtonBuilder().setCustomId('setup:close').setLabel('Close').setEmoji('✖️').setStyle(ButtonStyle.Danger))]};}
function buildModules(s){const e=new EmbedBuilder().setTitle('🧩 Module Manager').setDescription('Select an available module below to toggle it immediately. Pet Game is locked as Coming Soon and cannot be enabled yet.').addFields({name:'Current state',value:Object.entries(MODULES).map(([k,n])=>k==='pet'?`🔒 LOCKED • ${n}`:`${s.modules[k]?'🟢 ON ':'⚫ OFF'} • ${n}`).join('\n')}); const menu=new StringSelectMenuBuilder().setCustomId('setup:toggle').setPlaceholder('Toggle an available module').addOptions(Object.entries(MODULES).filter(([k])=>k!=='pet').map(([k,n])=>({label:n.replace(/^.. /,''),value:k,description:s.modules[k]?'Currently enabled':'Currently disabled'})));return {embeds:[e],components:[new ActionRowBuilder().addComponents(menu),back()]};}
function buildChannels(s){const e=new EmbedBuilder().setTitle('📡 Channel Configuration').setDescription('Choose the destination used by each system.').addFields({name:'Welcome',value:s.channels?.welcome?`<#${s.channels.welcome}>`:'Not set',inline:true},{name:'Leave',value:s.channels?.leave?`<#${s.channels.leave}>`:'Not set',inline:true},{name:'Server Logs',value:s.channels?.logs?`<#${s.channels.logs}>`:'Not set',inline:true},{name:'Stats Category',value:s.channels?.stats?`<#${s.channels.stats}>`:'Auto-create with /stats',inline:true},{name:'Ticket Category',value:s.channels?.ticketCategory?`<#${s.channels.ticketCategory}>`:'Not set',inline:true});const which=new StringSelectMenuBuilder().setCustomId('setup:channelkey').setPlaceholder('1. Select what you want to configure').addOptions([{label:'Welcome channel',value:'welcome',emoji:'👋'},{label:'Leave channel',value:'leave',emoji:'🚪'},{label:'Server log channel',value:'logs',emoji:'📜'},{label:'Stats category',value:'stats',emoji:'📊'},{label:'Ticket category',value:'ticketCategory',emoji:'🎫'}]);return {embeds:[e],components:[new ActionRowBuilder().addComponents(which),back()]};}
function channelPicker(key){const category=key==='ticketCategory'||key==='stats';const picker=new ChannelSelectMenuBuilder().setCustomId(`setup:setchannel:${key}`).setPlaceholder(key==='stats'?'2. Choose stats category':category?'2. Choose ticket category':'2. Choose channel').setMinValues(1).setMaxValues(1).setChannelTypes(category?[ChannelType.GuildCategory]:[ChannelType.GuildText,ChannelType.GuildAnnouncement]);return new ActionRowBuilder().addComponents(picker);}
async function buildPremium(guild,s){const p=await getActivePremium(guild.id);const e=new EmbedBuilder().setTitle('💎 Premium & Branding').setDescription(p?'Premium customization is unlocked for this server.':'This server is on Free. Redeem a Premium CD Key to unlock branding controls.').addFields({name:'Status',value:p?`💎 ACTIVE\nExpires: <t:${Math.floor(p.expiresAt/1000)}:F>`:'🆓 FREE'},{name:'Premium customization',value:`• Custom bot nickname\n• Custom bot avatar URL\n• Bot emoji theme\n• Corgi Studio exclusive emoji: **${s.premiumBranding?.useCorgiStudioEmoji?'ON':'OFF'}**\n• Corgi Studio exclusive emoji access`});const row=new ActionRowBuilder().addComponents(new ButtonBuilder().setCustomId('setup:premium:name').setLabel('Bot Name').setEmoji('✏️').setStyle(ButtonStyle.Primary).setDisabled(!p),new ButtonBuilder().setCustomId('setup:premium:avatar').setLabel('Avatar').setEmoji('🖼️').setStyle(ButtonStyle.Primary).setDisabled(!p),new ButtonBuilder().setCustomId('setup:premium:emoji').setLabel('Emoji Theme').setEmoji('✨').setStyle(ButtonStyle.Secondary).setDisabled(!p),new ButtonBuilder().setCustomId('setup:premium:corgiEmoji').setLabel('Corgi Emoji').setEmoji('🐶').setStyle(ButtonStyle.Success).setDisabled(!p));return {embeds:[e],components:[row,back()]};}
function buildLanguage(s){const e=new EmbedBuilder().setTitle('🌐 Language').setDescription('Select the server interface language.');const menu=new StringSelectMenuBuilder().setCustomId('setup:setlanguage').setPlaceholder('Choose language').addOptions([{label:'English',value:'en',emoji:'🇺🇸',default:s.language==='en'},{label:'Tiếng Việt',value:'vi',emoji:'🇻🇳',default:s.language==='vi'}]);return {embeds:[e],components:[new ActionRowBuilder().addComponents(menu),back()]};}
function back(){return new ActionRowBuilder().addComponents(new ButtonBuilder().setCustomId('setup:home').setLabel('Back to Control Center').setEmoji('⬅️').setStyle(ButtonStyle.Secondary));}
function premiumModal(kind,current=''){const modal=new ModalBuilder().setCustomId(`setup:premiumModal:${kind}`).setTitle(kind==='name'?'Premium • Bot Name':kind==='avatar'?'Premium • Bot Avatar':'Premium • Emoji Theme');const input=new TextInputBuilder().setCustomId('value').setLabel(kind==='name'?'New bot nickname':kind==='avatar'?'HTTPS image URL':'Emoji theme name').setStyle(TextInputStyle.Short).setRequired(true).setMaxLength(kind==='avatar'?500:kind==='name'?32:50);if(current)input.setValue(current);return modal.addComponents(new ActionRowBuilder().addComponents(input));}
module.exports={MODULES,buildSetupHome,buildModules,buildChannels,buildPremium,buildLanguage,channelPicker,premiumModal};