const { SlashCommandBuilder, EmbedBuilder } = require('discord.js');
const { guildLang, pick } = require('../../services/i18n');
function body(lang,category){const vi=lang==='vi';const data={
all:vi?['**Bắt đầu**','• `/setup` — cấu hình server','• `/help category:<mục>` — hướng dẫn chi tiết','• Prefix mặc định: `?`','','**Member / Kinh tế**','`/balance` • `/daily` • `/inventory` • `/leaderboard` • `/transfer` • `/redeem` • `/premium` • `/ai`','','**Game Cstar**','`/taixiu` • `/poker` • `/roullette` • `/spin` • `/lottery`','Prefix tương ứng: `?taixiu` • `?poker` • `?roullette` • `?spin` • `?lottery`','','**Community / Admin**','`/giveaway` • `/contest` • `/poll` • `/reactionrole` • `/ticket` • `/stats`','','**Kiểm duyệt**','`/warn` • `/kick` • `/mute` • `/unmute` • `/ban` • `/unban` • `/warnings` • `/clear`','','🐾 Pet Game — **Sắp ra mắt**']:['**Getting started**','• `/setup` — server configuration','• `/help category:<name>` — detailed help','• Default prefix: `?`','','**Member / Economy**','`/balance` • `/daily` • `/inventory` • `/leaderboard` • `/transfer` • `/redeem` • `/premium` • `/ai`','','**Cstar Games**','`/taixiu` • `/poker` • `/roullette` • `/spin` • `/lottery`','Matching prefixes: `?taixiu` • `?poker` • `?roullette` • `?spin` • `?lottery`','','**Community / Admin**','`/giveaway` • `/contest` • `/poll` • `/reactionrole` • `/ticket` • `/stats`','','**Moderation**','`/warn` • `/kick` • `/mute` • `/unmute` • `/ban` • `/unban` • `/warnings` • `/clear`','','🐾 Pet Game — **Coming Soon**'],
moderation:vi?['`/warn user:@member reason:text`','`/kick user:@member reason:text`','`/mute user:@member minutes:10 reason:text`','`/unmute user:@member reason:text`','`/ban user:@member reason:text`','`/unban user_id:ID reason:text`','`/warnings user:@member`','`/clear amount:1-100`','','Prefix tương ứng: `?warn`, `?kick`, `?mute`, `?unmute`, `?ban`, `?unban`, `?warnings`, `?clear`.','Lệnh cũ `/moderation ...` đã được loại bỏ để tránh trùng lặp.']:['`/warn user:@member reason:text`','`/kick user:@member reason:text`','`/mute user:@member minutes:10 reason:text`','`/unmute user:@member reason:text`','`/ban user:@member reason:text`','`/unban user_id:ID reason:text`','`/warnings user:@member`','`/clear amount:1-100`','','Matching prefixes are available.','The old `/moderation ...` suite was removed to avoid duplicate commands.'],
games:vi?['`/taixiu pick:tai|xiu bet:Cstar` — Tài Xỉu 3 xúc xắc.','`/poker bet:Cstar` — Poker 5 lá đấu dealer với xếp hạng bài thật.','`/roullette pick:red|black|green|0-36 bet:Cstar` — Roulette màu hoặc số.','`/spin bet:Cstar` — vòng quay hệ số có trọng số.','`/lottery number:1-99 bet:Cstar` — xổ số 1-99, có giải số đảo/gần.','','Tất cả chỉ dùng Cstar trong bot, không có giá trị tiền thật.']:['`/taixiu pick:tai|xiu bet:Cstar` — three-dice Tài Xỉu.','`/poker bet:Cstar` — five-card Poker vs dealer with real hand ranking.','`/roullette pick:red|black|green|0-36 bet:Cstar` — color or number roulette.','`/spin bet:Cstar` — weighted multiplier wheel.','`/lottery number:1-99 bet:Cstar` — 1-99 lottery with near/reverse prizes.','','All games use in-bot Cstar only and have no real-money value.'],
ai:vi?['`/ai question:<nội dung>` • `?ai <nội dung>`','','Corgi AI là trợ lý AI tổng quát miễn phí, không chỉ hỗ trợ bot. Có thể hỏi kiến thức, code, viết nội dung, gaming, Discord, ý tưởng và câu hỏi thường ngày.','Cách diễn đạt được biến đổi tự nhiên để tránh phản hồi máy móc/lặp lại.']:['`/ai question:<text>` • `?ai <text>`','','Corgi AI is a free general-purpose assistant, not only bot support. Ask about knowledge, coding, writing, gaming, Discord, ideas, and everyday topics.','Response style varies naturally to avoid repetitive canned replies.']};return (data[category]||data.all).join('\n');}
function title(lang,category){const vi=lang==='vi';const m={all:vi?'🐶 Corgi-Bot • Trung tâm lệnh':'🐶 Corgi-Bot • Command Center',moderation:vi?'🛡️ Lệnh kiểm duyệt':'🛡️ Moderation Commands',games:vi?'🎮 Trò chơi Cstar':'🎮 Cstar Games',ai:'🤖 Corgi AI • FREE'};return m[category]||m.all;}
function embedFor(lang,category='all'){return new EmbedBuilder().setTitle(title(lang,category)).setDescription(body(lang,category)).setFooter({text:pick(lang,'Corgi Studio • Default prefix: ?','Corgi Studio • Prefix mặc định: ?')}).setTimestamp();}
module.exports={data:new SlashCommandBuilder().setName('help').setDescription('Corgi-Bot command guide').setDescriptionLocalizations({vi:'Hướng dẫn lệnh Corgi-Bot'}).addStringOption(o=>o.setName('category').setDescription('Help category').setDescriptionLocalizations({vi:'Danh mục trợ giúp'}).addChoices({name:'All commands',name_localizations:{vi:'Tất cả lệnh'},value:'all'},{name:'Moderation',name_localizations:{vi:'Kiểm duyệt'},value:'moderation'},{name:'Games',name_localizations:{vi:'Trò chơi'},value:'games'},{name:'AI',value:'ai'})),prefix:['help'],async execute(i){const lang=await guildLang(i.guildId),category=i.options.getString('category')||'all';return i.reply({embeds:[embedFor(lang,category)],flags:64});},async executePrefix(m,args){const lang=await guildLang(m.guildId),category=String(args[0]||'all').toLowerCase();return m.reply({embeds:[embedFor(lang,category)]});}};
