const {Events,EmbedBuilder,ActionRowBuilder,StringSelectMenuBuilder,PermissionFlagsBits,ChannelType,ButtonBuilder,ButtonStyle}=require('discord.js');
const CUI=require('../ui/community');const CommunityPanel=require('../models/CommunityPanel');const Ticket=require('../models/Ticket');const ReactionRole=require('../models/ReactionRole');const {getGuildSettings}=require('../services/guildSettings');
function vars(t,m){return String(t||'').replaceAll('{user}',m?`<@${m.id}>`:'@user').replaceAll('{username}',m?.user?.username||'username').replaceAll('{server}',m?.guild?.name||'Server').replaceAll('{count}',String(m?.guild?.memberCount||0));}
function embedFrom(o,m){const e=new EmbedBuilder().setColor(0xF59E0B).setTitle(vars(o?.title||'Corgi Studio',m)).setDescription(vars(o?.description||'Configure this panel.',m));if(o?.footer)e.setFooter({text:vars(o.footer,m)});if(o?.thumbnailUrl)e.setThumbnail(o.thumbnailUrl);if(o?.imageUrl)e.setImage(o.imageUrl);return e;}
module.exports={name:Events.InteractionCreate,async execute(i){if(!i.customId?.startsWith('community:'))return;const s=await getGuildSettings(i.guildId);const c=await CUI.cfg(i.guildId),p=i.customId.split(':');
if(i.isStringSelectMenu()&&i.customId==='community:ticket:create'){const type=c.ticket.types.find(x=>x.key===i.values[0]&&x.enabled);if(!type)return i.reply({content:'❌ Ticket type unavailable.',flags:64});const existing=await Ticket.findOne({guildId:i.guildId,ownerId:i.user.id,status:{$in:['open','reopened']}}).lean();if(existing){const x=await i.guild.channels.fetch(existing.channelId).catch(()=>null);if(x)return i.reply({content:`You already have an open ticket: ${x}`,flags:64});}const last=await Ticket.findOne({guildId:i.guildId}).sort({ticketNo:-1}).lean(),no=(last?.ticketNo||0)+1;const perms=[{id:i.guild.roles.everyone.id,deny:[PermissionFlagsBits.ViewChannel]},{id:i.user.id,allow:[PermissionFlagsBits.ViewChannel,PermissionFlagsBits.SendMessages,PermissionFlagsBits.ReadMessageHistory,PermissionFlagsBits.AttachFiles]},{id:i.guild.members.me.id,allow:[PermissionFlagsBits.ViewChannel,PermissionFlagsBits.SendMessages,PermissionFlagsBits.ManageChannels,PermissionFlagsBits.ReadMessageHistory]}];if(type.staffRoleId)perms.push({id:type.staffRoleId,allow:[PermissionFlagsBits.ViewChannel,PermissionFlagsBits.SendMessages,PermissionFlagsBits.ReadMessageHistory]});const ch=await i.guild.channels.create({name:`${type.prefix||'TKT'}-${String(no).padStart(6,'0')}`,type:ChannelType.GuildText,parent:type.categoryId||s.channels?.ticketCategory||null,permissionOverwrites:perms});await Ticket.create({guildId:i.guildId,channelId:ch.id,ownerId:i.user.id,ticketNo:no,typeKey:type.key,typeName:type.name});const e=new EmbedBuilder().setColor(0xF59E0B).setTitle(`${type.emoji||'🎫'} ${type.name} • #${String(no).padStart(6,'0')}`).setDescription(`Owner: ${i.user}\nType: **${type.name}**\n\nPlease describe your request clearly.`).setTimestamp();const row=new ActionRowBuilder().addComponents(new ButtonBuilder().setCustomId('ticket:close').setLabel('Close').setEmoji('🔒').setStyle(ButtonStyle.Danger));await ch.send({content:`${i.user}${type.staffRoleId?` <@&${type.staffRoleId}>`:''}`,embeds:[e],components:[row]});return i.reply({content:`✅ Ticket created: ${ch}`,flags:64});}
if(!i.member?.permissions?.has(PermissionFlagsBits.ManageGuild))return i.reply({content:'❌ Manage Server required.',flags:64});
if(i.isButton()&&p[1]==='home')return i.update(CUI.home(s));if(i.isButton()&&['welcome','ticket','reaction'].includes(p[1])&&!p[2])return i.update(CUI.page(p[1],s));
if(i.isButton()&&p[2]==='edit'){if(p[1]==='welcome')return i.showModal(CUI.modal('welcome',c));return i.showModal(CUI.modal(p[1],c));}
if(i.isModalSubmit()&&p[1]==='modal'){const kind=p[2],patch={};for(const k of ['title','description','thumbnailUrl','imageUrl','footer'])patch[k]=i.fields.getTextInputValue(k).trim();await CommunityPanel.updateOne({guildId:i.guildId},{$set:Object.fromEntries(Object.entries(patch).map(([k,v])=>[`${kind}.${k}`,v]))});return i.reply({content:'✅ Saved. Use Preview / Publish.',flags:64});}
if(i.isButton()&&p[2]==='preview'){const o=c[p[1]];if(p[1]==='ticket'){const menu=new StringSelectMenuBuilder().setCustomId('community:ticket:create').setPlaceholder('Choose ticket type').addOptions(c.ticket.types.filter(x=>x.enabled).slice(0,25).map(x=>({label:x.name,value:x.key,emoji:x.emoji,description:x.description?.slice(0,100)})));return i.reply({embeds:[embedFrom(o,i.member)],components:[new ActionRowBuilder().addComponents(menu)],flags:64});}return i.reply({embeds:[embedFrom(o,i.member)],flags:64});}
if(i.isButton()&&p[2]==='publish'){const o=c[p[1]],ch=i.channel;if(p[1]==='ticket'){const menu=new StringSelectMenuBuilder().setCustomId('community:ticket:create').setPlaceholder('Choose ticket type').addOptions(c.ticket.types.filter(x=>x.enabled).slice(0,25).map(x=>({label:x.name,value:x.key,emoji:x.emoji,description:x.description?.slice(0,100)})));await ch.send({embeds:[embedFrom(o,i.member)],components:[new ActionRowBuilder().addComponents(menu)]});}else await ch.send({embeds:[embedFrom(o,i.member)]});return i.reply({content:'✅ Panel published in this channel.',flags:64});}
}};
