const { Events }=require('discord.js');
const { getGuildSettings }=require('../services/guildSettings');
const { checkAccess }=require('../services/accessControl');
const { isPremiumGuild }=require('../services/premium');
const { pick }=require('../services/i18n');
const Progression=require('../services/progression');
module.exports={name:Events.MessageCreate,async execute(message,client){if(message.author.bot||!message.guild)return;const s=await getGuildSettings(message.guildId);if(s.modules?.leveling!==false){Progression.awardMessageXp(message.author.id).catch(e=>console.warn('Progression XP failed:',e.message));}const p=s.prefix||'?';if(!message.content.startsWith(p))return;const parts=message.content.slice(p.length).trim().split(/\s+/);const name=(parts.shift()||'').toLowerCase();const c=client.prefixCommands.get(name);if(!c?.executePrefix)return;const access=await checkAccess({userId:message.author.id,guildId:message.guildId});if(!access.allowed)return message.reply(access.message).catch(()=>{});
const required=c.data?.toJSON?.().default_member_permissions;
if(required&&!message.member?.permissions?.has(BigInt(required)))return message.reply(pick(s.language,'❌ You do not have the required Discord permission for this command.','❌ Bạn không có quyền Discord cần thiết để dùng lệnh này.')).catch(()=>{});
if(c.premiumOnly&&!(await isPremiumGuild(message.guildId)))return message.reply(pick(s.language,'💎 This command requires active Corgi Premium for this server.','💎 Lệnh này yêu cầu Corgi Premium đang hoạt động cho server.'));try{await c.executePrefix(message,parts,client);}catch(e){console.error(e);await message.reply(pick(s.language,'Command error.','Lệnh gặp lỗi.'));}}};
