const {EmbedBuilder,ActionRowBuilder,ButtonBuilder,ButtonStyle,StringSelectMenuBuilder}=require('discord.js');
const FishingProfile=require('../../models/FishingProfile');
const UserEconomy=require('../../models/UserEconomy');
const {ensureWallet,walletFilter}=require('../../services/economyWallet');
const {RARITIES,FISH,RODS,BAITS}=require('./config');
const {pick}=require('../../services/i18n');
const COOLDOWN=8000,MAX_BAG=250;
const rarityIndex=id=>RARITIES.findIndex(x=>x.id===id); const rarity=id=>RARITIES.find(x=>x.id===id)||RARITIES[0];
async function profile(uid){return FishingProfile.findOneAndUpdate({userId:String(uid)},{$setOnInsert:{userId:String(uid)}},{upsert:true,returnDocument:'after',setDefaultsOnInsert:true});}
function rollRarity(luck=0){let weights=RARITIES.map((r,i)=>r.chance*Math.pow(1+luck,i));const total=weights.reduce((a,b)=>a+b,0);let x=Math.random()*total;for(let i=0;i<weights.length;i++){x-=weights[i];if(x<=0)return RARITIES[i];}return RARITIES[0];}
function nav(uid,lang){return [new ActionRowBuilder().addComponents(
 new ButtonBuilder().setCustomId(`fish:cast:${uid}`).setLabel(pick(lang,'Fish','Câu cá')).setEmoji('🎣').setStyle(ButtonStyle.Primary),
 new ButtonBuilder().setCustomId(`fish:bag:${uid}`).setLabel(pick(lang,'Bag','Túi cá')).setEmoji('🎒').setStyle(ButtonStyle.Secondary),
 new ButtonBuilder().setCustomId(`fish:dex:${uid}`).setLabel('Fishdex').setEmoji('📖').setStyle(ButtonStyle.Secondary),
 new ButtonBuilder().setCustomId(`fish:shop:${uid}`).setLabel(pick(lang,'Shop','Cửa hàng')).setEmoji('🛒').setStyle(ButtonStyle.Success),
 new ButtonBuilder().setCustomId(`fish:rank:${uid}`).setLabel(pick(lang,'Ranking','Xếp hạng')).setEmoji('🏆').setStyle(ButtonStyle.Secondary)
 )];}
async function home(uid,lang){const p=await profile(uid),w=await ensureWallet(uid),rod=RODS[p.rodLevel]||RODS[0];const e=new EmbedBuilder().setColor(0x3498DB).setTitle('🎣 Corgi Fishing').setDescription(pick(lang,'Catch, collect, sell and chase the global fishing crown.','Câu cá, sưu tầm, bán cá và tranh ngôi đầu bảng câu cá toàn cầu.')).addFields(
 {name:pick(lang,'🎣 Rod','🎣 Cần câu'),value:pick(lang,rod.nameEn,rod.nameVi),inline:true},{name:'🌟 Cstar',value:Number(w.cstar).toLocaleString(),inline:true},{name:'📖 Fishdex',value:`${p.fishdex.length}/${FISH.length}`,inline:true},
 {name:pick(lang,'🐟 Lifetime catch','🐟 Tổng cá đã câu'),value:Number(p.totalCaught).toLocaleString(),inline:true},{name:pick(lang,'⚖️ Lifetime weight','⚖️ Tổng cân nặng'),value:`${p.totalWeight.toFixed(2)} kg`,inline:true},{name:pick(lang,'💎 Best rarity','💎 Độ hiếm cao nhất'),value:p.bestRarity,inline:true}
 ).setFooter({text:pick(lang,'/fishing = cast instantly • All fishing progress is global','/fishing = câu ngay • Toàn bộ tiến độ câu cá được tính toàn cầu')});return{embeds:[e],components:nav(uid,lang)};}
async function cast(uid,lang){const p=await profile(uid),now=Date.now();if(p.lastFishedAt&&now-p.lastFishedAt.getTime()<COOLDOWN)return{error:pick(lang,`⏳ Fish are still settling. Try again in ${Math.ceil((COOLDOWN-(now-p.lastFishedAt.getTime()))/1000)}s.`,`⏳ Cá đang động nước. Thử lại sau ${Math.ceil((COOLDOWN-(now-p.lastFishedAt.getTime()))/1000)} giây.`)};
 const rod=RODS[p.rodLevel]||RODS[0],baitId=p.selectedBait||'basic',bait=BAITS[baitId]||BAITS.basic;let usedBait='basic';if(baitId!=='basic'&&(Number(p.bait.get?.(baitId)||0)>0)){p.bait.set(baitId,Number(p.bait.get(baitId))-1);usedBait=baitId;}const b=BAITS[usedBait];const rr=rollRarity(rod.luck+b.luck),pool=FISH.filter(f=>f.rarity===rr.id),f=pool[Math.floor(Math.random()*pool.length)];const weight=Number((f.min+Math.random()*(f.max-f.min)*(rod.weight+b.weight)).toFixed(2));const value=Math.max(1,Math.round(f.base*weight*(1+rarityIndex(rr.id)*.18)));const catchId=`${Date.now().toString(36)}${Math.random().toString(36).slice(2,6)}`;const c={catchId,speciesId:f.id,nameEn:f.en,nameVi:f.vi,rarity:rr.id,weight,value,locked:false,caughtAt:new Date()};p.totalCaught++;p.totalWeight+=weight;p.bestWeight=Math.max(p.bestWeight||0,weight);if(rarityIndex(rr.id)>rarityIndex(p.bestRarity))p.bestRarity=rr.id;p.bestSpeciesId=rarityIndex(rr.id)>=rarityIndex(p.bestRarity)?f.id:p.bestSpeciesId;if(!p.fishdex.includes(f.id))p.fishdex.push(f.id);p.rarityCaught.set(rr.id,Number(p.rarityCaught.get(rr.id)||0)+1);p.lastFishedAt=new Date();p.bag.push(c);if(p.bag.length>MAX_BAG){const idx=p.bag.findIndex(x=>!x.locked);if(idx>=0)p.bag.splice(idx,1);else p.bag.shift();}await p.save();
 const name=rr.id==='??'?'???':pick(lang,f.en,f.vi);const displayColor=rr.id==='??'?[0xFF3DCE,0x00D9FF,0xFFD700,0x9B59FF,0x43D17A][Math.floor(Math.random()*5)]:rr.color;const e=new EmbedBuilder().setColor(displayColor).setTitle(`${rr.id==='??'?'✨':'🐟'} ${pick(lang,'Catch!','Cắn câu!')} • ${rr.id} ${pick(lang,rr.en,rr.vi)}`).setDescription(`**${name}**`).addFields({name:'⚖️',value:`**${weight.toFixed(2)} kg**`,inline:true},{name:'🌟',value:`**${value.toLocaleString()} Cstar**`,inline:true},{name:pick(lang,'🪱 Bait','🪱 Mồi'),value:pick(lang,b.en,b.vi),inline:true}).setFooter({text:pick(lang,'Keep it, sell it, or lock it. Fishdex and lifetime records remain even after selling.','Giữ, bán hoặc khóa cá. Fishdex và kỷ lục tích lũy vẫn được giữ sau khi bán.')});
 const row=new ActionRowBuilder().addComponents(new ButtonBuilder().setCustomId(`fish:keep:${uid}:${catchId}`).setLabel(pick(lang,'Keep','Giữ')).setEmoji('🎒').setStyle(ButtonStyle.Secondary),new ButtonBuilder().setCustomId(`fish:sell:${uid}:${catchId}`).setLabel(pick(lang,'Sell','Bán')).setEmoji('💰').setStyle(ButtonStyle.Success),new ButtonBuilder().setCustomId(`fish:lock:${uid}:${catchId}`).setLabel(pick(lang,'Lock','Khóa')).setEmoji('🔒').setStyle(ButtonStyle.Secondary),new ButtonBuilder().setCustomId(`fish:cast:${uid}`).setLabel(pick(lang,'Fish Again','Câu tiếp')).setEmoji('🎣').setStyle(ButtonStyle.Primary));return{embeds:[e],components:[row]};}
async function bag(uid,lang){const p=await profile(uid),rows=[...p.bag].sort((a,b)=>rarityIndex(b.rarity)-rarityIndex(a.rarity)||b.weight-a.weight).slice(0,15);const text=rows.length?rows.map((c,i)=>`${i+1}. ${c.locked?'🔒 ':''}**[${c.rarity}] ${c.rarity==='??'?'???':pick(lang,c.nameEn,c.nameVi)}** • ${c.weight.toFixed(2)} kg • ${c.value.toLocaleString()} 🌟`).join('\n'):pick(lang,'Your Fishing Bag is empty.','Túi cá đang trống.');return{embeds:[new EmbedBuilder().setColor(0x5865F2).setTitle(pick(lang,'🎒 Fishing Bag','🎒 Túi Cá')).setDescription(text).setFooter({text:pick(lang,`Showing up to 15 • Stored ${p.bag.length}/${MAX_BAG}`,`Hiển thị tối đa 15 • Đang giữ ${p.bag.length}/${MAX_BAG}`)})],components:nav(uid,lang)};}
async function dex(uid,lang){const p=await profile(uid);const by={};for(const r of RARITIES)by[r.id]=FISH.filter(f=>f.rarity===r.id).map(f=>p.fishdex.includes(f.id)?(r.id==='??'?pick(lang,'✨ Discovered Infiniti Rare','✨ Đã khám phá Hiếm Vô Cực'):pick(lang,f.en,f.vi)):'???');const desc=RARITIES.map(r=>`**${r.id} • ${pick(lang,r.en,r.vi)}** — ${by[r.id].join(', ')}`).join('\n');return{embeds:[new EmbedBuilder().setColor(0x9B59FF).setTitle(`📖 Fishdex • ${p.fishdex.length}/${FISH.length}`).setDescription(desc.slice(0,4000))],components:nav(uid,lang)};}
async function shop(uid,lang){const p=await profile(uid),w=await ensureWallet(uid),cur=RODS[p.rodLevel],next=RODS[p.rodLevel+1];let rodText=pick(lang,`Current: **${cur.nameEn}**`,`Hiện tại: **${cur.nameVi}**`);if(next)rodText+=pick(lang,`\nNext: **${next.nameEn}**\n🐟 ${p.totalCaught.toLocaleString()}/${next.fish.toLocaleString()} • ⚖️ ${p.totalWeight.toFixed(0)}/${next.kg.toLocaleString()} kg • 🌟 ${w.cstar.toLocaleString()}/${next.cost.toLocaleString()}`,`\nTiếp theo: **${next.nameVi}**\n🐟 ${p.totalCaught.toLocaleString()}/${next.fish.toLocaleString()} • ⚖️ ${p.totalWeight.toFixed(0)}/${next.kg.toLocaleString()} kg • 🌟 ${w.cstar.toLocaleString()}/${next.cost.toLocaleString()}`);else rodText+=pick(lang,'\n👑 Maximum rod reached.','\n👑 Đã đạt cấp cần tối đa.');const baitText=Object.entries(BAITS).filter(([k])=>k!=='basic').map(([k,b])=>`${pick(lang,b.en,b.vi)} • ${b.qty}x = ${b.cost.toLocaleString()} 🌟 • 🎒 ${Number(p.bait.get?.(k)||0)}`).join('\n');const rows=[];if(next)rows.push(new ActionRowBuilder().addComponents(new ButtonBuilder().setCustomId(`fish:upgrade:${uid}`).setLabel(pick(lang,'Upgrade Rod','Nâng Cần')).setEmoji('🎣').setStyle(ButtonStyle.Success)));rows.push(new ActionRowBuilder().addComponents(new StringSelectMenuBuilder().setCustomId(`fish:buybait:${uid}`).setPlaceholder(pick(lang,'Buy bait','Mua mồi')).addOptions(Object.entries(BAITS).filter(([k])=>k!=='basic').map(([k,b])=>({label:pick(lang,b.en,b.vi),description:`${b.qty}x • ${b.cost.toLocaleString()} Cstar`,value:k})))));rows.push(...nav(uid,lang));return{embeds:[new EmbedBuilder().setColor(0xF1C40F).setTitle(pick(lang,'🛒 Fishing Shop','🛒 Cửa Hàng Câu Cá')).addFields({name:pick(lang,'🎣 Rod Upgrade','🎣 Nâng cấp cần'),value:rodText},{name:pick(lang,'🪱 Bait','🪱 Mồi câu'),value:baitText},{name:'🌟 Cstar',value:w.cstar.toLocaleString()})],components:rows.slice(0,5)};}
async function upgrade(uid,lang){const p=await profile(uid),next=RODS[p.rodLevel+1];if(!next)return{error:pick(lang,'👑 Your rod is already maxed.','👑 Cần câu đã đạt cấp tối đa.')};if(p.totalCaught<next.fish||p.totalWeight<next.kg)return{error:pick(lang,`🔒 Need ${next.fish.toLocaleString()} lifetime fish and ${next.kg.toLocaleString()} kg lifetime weight.`,`🔒 Cần tích lũy ${next.fish.toLocaleString()} cá đã câu và ${next.kg.toLocaleString()} kg tổng cân nặng.`)};await ensureWallet(uid);const wallet=await UserEconomy.findOneAndUpdate({...walletFilter(uid),cstar:{$gte:next.cost}},{$inc:{cstar:-next.cost}},{returnDocument:'after'});if(!wallet)return{error:pick(lang,`❌ Need ${next.cost.toLocaleString()} 🌟Cstar.`,`❌ Cần ${next.cost.toLocaleString()} 🌟Cstar.`)};p.rodLevel++;await p.save();return shop(uid,lang);}
async function buyBait(uid,key,lang){const b=BAITS[key];if(!b||key==='basic')return{error:pick(lang,'❌ Invalid bait.','❌ Mồi câu không hợp lệ.')};await ensureWallet(uid);const wallet=await UserEconomy.findOneAndUpdate({...walletFilter(uid),cstar:{$gte:b.cost}},{$inc:{cstar:-b.cost}},{returnDocument:'after'});if(!wallet)return{error:pick(lang,'❌ Not enough 🌟Cstar.','❌ Không đủ 🌟Cstar.')};const p=await profile(uid);p.bait.set(key,Number(p.bait.get(key)||0)+b.qty);p.selectedBait=key;await p.save();return shop(uid,lang);}
async function sell(uid,cid,lang){const p=await profile(uid),idx=p.bag.findIndex(x=>x.catchId===cid);if(idx<0)return{error:pick(lang,'This fish is no longer in your bag.','Cá này không còn trong túi.')};const c=p.bag[idx];if(c.locked)return{error:pick(lang,'🔒 Unlock this fish before selling it.','🔒 Hãy mở khóa cá trước khi bán.')};p.bag.splice(idx,1);p.totalSold++;p.totalEarned+=c.value;await p.save();await ensureWallet(uid);const w=await UserEconomy.findOneAndUpdate(walletFilter(uid),{$inc:{cstar:c.value}},{returnDocument:'after'});return{content:pick(lang,`💰 Sold **[${c.rarity}] ${c.rarity==='??'?'???':c.nameEn}** for **${c.value.toLocaleString()} 🌟Cstar**. Balance: **${w.cstar.toLocaleString()}**.`,`💰 Đã bán **[${c.rarity}] ${c.rarity==='??'?'???':c.nameVi}** nhận **${c.value.toLocaleString()} 🌟Cstar**. Số dư: **${w.cstar.toLocaleString()}**.`),components:nav(uid,lang)};}
async function lock(uid,cid,lang){const p=await profile(uid),c=p.bag.find(x=>x.catchId===cid);if(!c)return{error:pick(lang,'Fish not found.','Không tìm thấy cá.')};c.locked=!c.locked;await p.save();return{content:pick(lang,`${c.locked?'🔒 Locked':'🔓 Unlocked'} **[${c.rarity}] ${c.rarity==='??'?'???':c.nameEn}**.`,`${c.locked?'🔒 Đã khóa':'🔓 Đã mở khóa'} **[${c.rarity}] ${c.rarity==='??'?'???':c.nameVi}**.`),components:nav(uid,lang)};}
function score(p){const rare=[...RARITIES].reduce((s,r)=>s+Number(p.rarityCaught?.get?.(r.id)||p.rarityCaught?.[r.id]||0)*r.score,0);return Math.round((p.totalCaught||0)*2+(p.totalWeight||0)*.4+(p.fishdex?.length||0)*250+(p.bestWeight||0)*2+rare);}
async function ranking(uid,lang){const ps=await FishingProfile.find({totalCaught:{$gt:0}}).lean();const top=ps.map(p=>({...p,fishingScore:score(p)})).sort((a,b)=>b.fishingScore-a.fishingScore||b.totalWeight-a.totalWeight).slice(0,10);const lines=top.map((p,i)=>`${['🥇','🥈','🥉'][i]||`**#${i+1}**`} <@${p.userId}> — **${p.fishingScore.toLocaleString()} ${pick(lang,'pts','điểm')}**\n🐟 ${p.totalCaught.toLocaleString()} • ⚖️ ${p.totalWeight.toFixed(1)} kg • 💎 ${p.bestRarity} • 📖 ${p.fishdex.length}/${FISH.length}`);const me=ps.find(x=>x.userId===String(uid));return{embeds:[new EmbedBuilder().setColor(0xFFD700).setTitle(pick(lang,'🏆 Global Fishing Ranking','🏆 Xếp Hạng Câu Cá Toàn Cầu')).setDescription(lines.join('\n\n')||pick(lang,'No catches yet.','Chưa có dữ liệu câu cá.')).setFooter({text:me?pick(lang,`Your Fishing Score: ${score(me).toLocaleString()} pts`,`Điểm Câu Cá của bạn: ${score(me).toLocaleString()} điểm`):'Corgi Fishing'})],components:nav(uid,lang)};}
async function handle(i,lang){const [,action,owner,arg]=i.customId.split(':');if(String(i.user.id)!==String(owner))return i.reply({content:pick(lang,'❌ This Fishing panel belongs to another player.','❌ Bảng Câu Cá này thuộc về người chơi khác.'),flags:64});let r;if(action==='cast')r=await cast(owner,lang);else if(action==='bag')r=await bag(owner,lang);else if(action==='dex')r=await dex(owner,lang);else if(action==='shop')r=await shop(owner,lang);else if(action==='rank')r=await ranking(owner,lang);else if(action==='upgrade')r=await upgrade(owner,lang);else if(action==='sell')r=await sell(owner,arg,lang);else if(action==='lock')r=await lock(owner,arg,lang);else if(action==='keep')r={content:pick(lang,'🎒 Fish kept in your bag.','🎒 Đã giữ cá trong túi.'),components:nav(owner,lang)};else if(action==='buybait')r=await buyBait(owner,i.values[0],lang);if(!r)return;if(r.error)return i.reply({content:r.error,flags:64});return i.update(r);}
module.exports={home,cast,bag,dex,shop,ranking,handle,score};
