const {EmbedBuilder,ActionRowBuilder,ButtonBuilder,ButtonStyle,StringSelectMenuBuilder}=require('discord.js');
const FishingProfile=require('../../models/FishingProfile');
const UserEconomy=require('../../models/UserEconomy');
const {ensureWallet,walletFilter}=require('../../services/economyWallet');
const {RARITIES,FISH,RODS,BAITS}=require('./config');
const {mtx}=require('../../services/i18n');
const FishingSettings=require('../../services/fishingSettings');
const COOLDOWN=8000,MAX_BAG=250;
const rarityIndex=id=>RARITIES.findIndex(x=>x.id===id); const rarity=id=>RARITIES.find(x=>x.id===id)||RARITIES[0];
async function profile(uid){const cfg=await FishingSettings.get();const p=await FishingProfile.findOneAndUpdate({userId:String(uid)},{$setOnInsert:{userId:String(uid),bait:{basic:cfg.starterBait},starterBaitGranted:true}},{upsert:true,returnDocument:'after',setDefaultsOnInsert:true});if(!p.starterBaitGranted){p.bait.set('basic',Number(p.bait.get('basic')||0)+cfg.starterBait);p.starterBaitGranted=true;await p.save();}return p;}
function rollRarity(luck=0,chances=null){let weights=RARITIES.map((r,i)=>Number(chances?.[r.id]??r.chance)*Math.pow(1+luck,i));const total=weights.reduce((a,b)=>a+b,0);let x=Math.random()*total;for(let i=0;i<weights.length;i++){x-=weights[i];if(x<=0)return RARITIES[i];}return RARITIES[0];}
function nav(uid,lang){return [new ActionRowBuilder().addComponents(
 new ButtonBuilder().setCustomId(`fish:cast:${uid}`).setLabel(mtx(lang,'Fish','Câu cá')).setEmoji('🎣').setStyle(ButtonStyle.Primary),
 new ButtonBuilder().setCustomId(`fish:bag:${uid}`).setLabel(mtx(lang,'Bag','Túi cá')).setEmoji('🎒').setStyle(ButtonStyle.Secondary),
 new ButtonBuilder().setCustomId(`fish:dex:${uid}`).setLabel('Fishdex').setEmoji('📖').setStyle(ButtonStyle.Secondary),
 new ButtonBuilder().setCustomId(`fish:shop:${uid}`).setLabel(mtx(lang,'Shop','Cửa hàng')).setEmoji('🛒').setStyle(ButtonStyle.Success),
 new ButtonBuilder().setCustomId(`fish:rank:${uid}`).setLabel(mtx(lang,'Ranking','Xếp hạng')).setEmoji('🏆').setStyle(ButtonStyle.Secondary)
 ),new ActionRowBuilder().addComponents(
 new ButtonBuilder().setCustomId(`fish:sellcenter:${uid}`).setLabel(mtx(lang,'Sell Fish','Bán cá')).setEmoji('💰').setStyle(ButtonStyle.Success)
 )];}
async function home(uid,lang){const cfg=await FishingSettings.get();if(!cfg.enabled)return{content:mtx(lang,'🎣 Fishing is temporarily disabled by the Developer.','🎣 Câu cá hiện đang được Developer tạm tắt.'),components:[]};const p=await profile(uid),w=await ensureWallet(uid),rod=cfg.rods[p.rodLevel]||cfg.rods[0];const e=new EmbedBuilder().setColor(0x3498DB).setTitle('🎣 Corgi Fishing').setDescription(mtx(lang,'Catch, collect, sell and chase the global fishing crown.','Câu cá, sưu tầm, bán cá và tranh ngôi đầu bảng câu cá toàn cầu.')).addFields(
 {name:mtx(lang,'🎣 Rod','🎣 Cần câu'),value:mtx(lang,rod.nameEn,rod.nameVi),inline:true},{name:mtx(lang,'🪱 Active bait','🪱 Mồi đang dùng'),value:`${mtx(lang,(cfg.baits[p.selectedBait]||cfg.baits.basic).en,(cfg.baits[p.selectedBait]||cfg.baits.basic).vi)} • ${Number(p.bait.get?.(p.selectedBait)||0)}${Number(p.bait.get?.(p.selectedBait)||0)<=5?' ⚠️':''}`,inline:true},{name:'🌟 CXu',value:Number(w.cstar).toLocaleString(),inline:true},{name:'📖 Fishdex',value:`${p.fishdex.length}/${FISH.length}`,inline:true},
 {name:mtx(lang,'🐟 Lifetime catch','🐟 Tổng cá đã câu'),value:Number(p.totalCaught).toLocaleString(),inline:true},{name:mtx(lang,'⚖️ Lifetime weight','⚖️ Tổng cân nặng'),value:`${p.totalWeight.toFixed(2)} kg`,inline:true},{name:mtx(lang,'💎 Best rarity','💎 Độ hiếm cao nhất'),value:p.bestRarity,inline:true}
 ).setFooter({text:mtx(lang,'/fishing = cast instantly • All fishing progress is global','/fishing = câu ngay • Toàn bộ tiến độ câu cá được tính toàn cầu')});return{embeds:[e],components:nav(uid,lang)};}
const activeCasts=new Map();
async function cast(uid,lang){
 const cfg=await FishingSettings.get();if(!cfg.enabled)return{error:mtx(lang,'🎣 Fishing is temporarily disabled by the Developer.','🎣 Câu cá hiện đang được Developer tạm tắt.')};
 const p=await profile(uid),now=Date.now(),cooldown=cfg.cooldownMs;if(p.lastFishedAt&&now-p.lastFishedAt.getTime()<cooldown)return{error:mtx(lang,`⏳ Fish are still settling. Try again in ${Math.ceil((cooldown-(now-p.lastFishedAt.getTime()))/1000)}s.`,`⏳ Cá đang động nước. Thử lại sau ${Math.ceil((cooldown-(now-p.lastFishedAt.getTime()))/1000)} giây.`)};
 const bait=p.selectedBait||'basic';if(Number(p.bait.get?.(bait)||0)<=0&&Number(p.bait.get?.('basic')||0)<=0)return{error:mtx(lang,'🪱 You’re out of bait! Visit the 🛒 Shop.','🪱 Bạn đã hết mồi! Hãy vào 🛒 Cửa hàng.')};
 activeCasts.set(String(uid),{stage:'waiting',tension:45,progress:0,started:Date.now()});
 return{embeds:[new EmbedBuilder().setColor(0x3498DB).setTitle(mtx(lang,'🎣 Line Cast!','🎣 Đã Thả Câu!')).setDescription(mtx(lang,'🌊 The float is moving... wait for the right moment, then **HOOK!**','🌊 Phao đang chuyển động... chờ đúng nhịp rồi **GIẬT CẦN!**')).addFields({name:mtx(lang,'Line','Dây câu'),value:'〰️〰️〰️🎣🌊',inline:false})],components:[new ActionRowBuilder().addComponents(new ButtonBuilder().setCustomId(`fish:hook:${uid}`).setLabel(mtx(lang,'HOOK!','GIẬT CẦN!')).setEmoji('❗').setStyle(ButtonStyle.Primary))]};
}
async function fishingFight(uid,action,lang){const st=activeCasts.get(String(uid));if(!st)return{error:mtx(lang,'This fishing session expired. Cast again.','Phiên câu đã hết. Hãy thả câu lại.')};if(st.stage==='waiting'){st.stage='fight';st.progress=12+Math.floor(Math.random()*15);st.tension=35+Math.floor(Math.random()*25);}else{const fishPull=Math.floor(Math.random()*21)-10;if(action==='reel'){st.progress+=18;st.tension+=15+fishPull;}else if(action==='hold'){st.progress+=8;st.tension+=fishPull;}else if(action==='release'){st.progress+=4;st.tension-=18;}}
 st.tension=Math.max(0,Math.min(110,st.tension));if(st.tension>=100){activeCasts.delete(String(uid));return{embeds:[new EmbedBuilder().setTitle('💥 '+mtx(lang,'Line Snapped!','Đứt Dây!')).setDescription(mtx(lang,'You pulled too hard and the fish escaped.','Bạn kéo quá mạnh và cá đã thoát.'))],components:nav(uid,lang)};}if(st.tension<=3){activeCasts.delete(String(uid));return{embeds:[new EmbedBuilder().setTitle('🐟 '+mtx(lang,'Fish Escaped!','Cá Thoát!')).setDescription(mtx(lang,'The line went too loose.','Dây câu quá chùng.'))],components:nav(uid,lang)};}if(st.progress>=100){activeCasts.delete(String(uid));const r=await landCatch(uid,lang);if(!r.error&&r.embeds?.[0])r.embeds[0].setDescription(`${r.embeds[0].data.description||''}\n\n✨ **${mtx(lang,'Perfect reel completed!','Kéo cá thành công!')}**`);return r;}const bars=Math.max(0,Math.min(10,Math.round(st.tension/10))),prog=Math.max(0,Math.min(10,Math.round(st.progress/10)));return{embeds:[new EmbedBuilder().setColor(st.tension>80?0xED4245:0xFEE75C).setTitle(mtx(lang,'🎣 Fish On! Control the line','🎣 Cá Cắn Câu! Điều Khiển Dây')).setDescription(`${mtx(lang,'Tension','Độ căng')}: ${'🟥'.repeat(bars)}${'⬜'.repeat(10-bars)} **${st.tension}%**\n${mtx(lang,'Reel progress','Tiến độ kéo')}: ${'🟩'.repeat(prog)}${'⬜'.repeat(10-prog)} **${Math.min(100,st.progress)}%**`).setFooter({text:mtx(lang,'Reel gains ground but raises tension • Release protects the line','Kéo tăng tiến độ nhưng căng dây • Nhả giúp bảo vệ dây')})],components:[new ActionRowBuilder().addComponents(new ButtonBuilder().setCustomId(`fish:fight:${uid}:hold`).setLabel(mtx(lang,'Hold','Giữ')).setEmoji('✋').setStyle(ButtonStyle.Secondary),new ButtonBuilder().setCustomId(`fish:fight:${uid}:reel`).setLabel(mtx(lang,'Reel','Kéo')).setEmoji('🎣').setStyle(ButtonStyle.Primary),new ButtonBuilder().setCustomId(`fish:fight:${uid}:release`).setLabel(mtx(lang,'Release','Nhả')).setEmoji('〰️').setStyle(ButtonStyle.Success))]};}
async function landCatch(uid,lang){const cfg=await FishingSettings.get();if(!cfg.enabled)return{error:mtx(lang,'🎣 Fishing is temporarily disabled by the Developer.','🎣 Câu cá hiện đang được Developer tạm tắt.')};const p=await profile(uid),now=Date.now(),cooldown=cfg.cooldownMs;if(p.lastFishedAt&&now-p.lastFishedAt.getTime()<cooldown)return{error:mtx(lang,`⏳ Fish are still settling. Try again in ${Math.ceil((cooldown-(now-p.lastFishedAt.getTime()))/1000)}s.`,`⏳ Cá đang động nước. Thử lại sau ${Math.ceil((cooldown-(now-p.lastFishedAt.getTime()))/1000)} giây.`)};
 const rod=cfg.rods[p.rodLevel]||cfg.rods[0],baitId=p.selectedBait||'basic';let usedBait=baitId;if(Number(p.bait.get?.(usedBait)||0)<=0&&usedBait!=='basic'&&Number(p.bait.get?.('basic')||0)>0){usedBait='basic';p.selectedBait='basic';}if(Number(p.bait.get?.(usedBait)||0)<=0)return{error:mtx(lang,'🪱 You’re out of bait! Visit the 🛒 Shop to buy more.','🪱 Bạn đã hết mồi câu! Hãy vào 🛒 Cửa hàng để mua thêm.')};p.bait.set(usedBait,Number(p.bait.get(usedBait)||0)-1);const b=cfg.baits[usedBait];const rr=rollRarity(rod.luck+b.luck,cfg.rarityChances),pool=FISH.filter(f=>f.rarity===rr.id),f=pool[Math.floor(Math.random()*pool.length)];const weight=Number((f.min+Math.random()*(f.max-f.min)*(rod.weight+b.weight)).toFixed(2));const value=Math.max(1,Math.round(f.base*weight*(1+rarityIndex(rr.id)*.18)));const catchId=`${Date.now().toString(36)}${Math.random().toString(36).slice(2,6)}`;const c={catchId,speciesId:f.id,nameEn:f.en,nameVi:f.vi,rarity:rr.id,weight,value,locked:false,caughtAt:new Date()};p.totalCaught++;p.totalWeight+=weight;p.bestWeight=Math.max(p.bestWeight||0,weight);if(rarityIndex(rr.id)>rarityIndex(p.bestRarity))p.bestRarity=rr.id;p.bestSpeciesId=rarityIndex(rr.id)>=rarityIndex(p.bestRarity)?f.id:p.bestSpeciesId;if(!p.fishdex.includes(f.id))p.fishdex.push(f.id);p.rarityCaught.set(rr.id,Number(p.rarityCaught.get(rr.id)||0)+1);p.lastFishedAt=new Date();p.bag.push(c);if(p.bag.length>cfg.maxBag){const idx=p.bag.findIndex(x=>!x.locked);if(idx>=0)p.bag.splice(idx,1);else p.bag.shift();}await p.save();
 const name=rr.id==='??'?'???':mtx(lang,f.en,f.vi);const displayColor=rr.id==='??'?[0xFF3DCE,0x00D9FF,0xFFD700,0x9B59FF,0x43D17A][Math.floor(Math.random()*5)]:rr.color;const e=new EmbedBuilder().setColor(displayColor).setTitle(`${rr.id==='??'?'✨':'🐟'} ${mtx(lang,'Catch!','Cắn câu!')} • ${rr.id} ${mtx(lang,rr.en,rr.vi)}`).setDescription(`**${name}**`).addFields({name:'⚖️',value:`**${weight.toFixed(2)} kg**`,inline:true},{name:'🌟',value:`**${value.toLocaleString()} CXu**`,inline:true},{name:mtx(lang,'🪱 Bait','🪱 Mồi'),value:`${mtx(lang,b.en,b.vi)} • ${Number(p.bait.get(usedBait)||0)} ${mtx(lang,'left','còn lại')}${Number(p.bait.get(usedBait)||0)<=5?' ⚠️':''}`,inline:true}).setFooter({text:mtx(lang,'Keep it, sell it, or lock it. Fishdex and lifetime records remain even after selling.','Giữ, bán hoặc khóa cá. Fishdex và kỷ lục tích lũy vẫn được giữ sau khi bán.')});
 const drops=await require('../../services/seasonalService').rollDrop(uid,'fishing').catch(()=>[]);if(drops.length)e.addFields({name:'🎊 EVENT BONUS!',value:drops.map(d=>d.cstar?`${d.emoji} +${d.cstar} CXu`:`${d.emoji} ×${d.qty}`).join(' • ')});
 const row=new ActionRowBuilder().addComponents(new ButtonBuilder().setCustomId(`fish:keep:${uid}:${catchId}`).setLabel(mtx(lang,'Keep','Giữ')).setEmoji('🎒').setStyle(ButtonStyle.Secondary),new ButtonBuilder().setCustomId(`fish:sell:${uid}:${catchId}`).setLabel(mtx(lang,'Sell','Bán')).setEmoji('💰').setStyle(ButtonStyle.Success),new ButtonBuilder().setCustomId(`fish:lock:${uid}:${catchId}`).setLabel(mtx(lang,'Lock','Khóa')).setEmoji('🔒').setStyle(ButtonStyle.Secondary),new ButtonBuilder().setCustomId(`fish:cast:${uid}`).setLabel(mtx(lang,'Fish Again','Câu tiếp')).setEmoji('🎣').setStyle(ButtonStyle.Primary));return{embeds:[e],components:[row]};}
async function bag(uid,lang){const cfg=await FishingSettings.get(),p=await profile(uid),rows=[...p.bag].sort((a,b)=>rarityIndex(b.rarity)-rarityIndex(a.rarity)||b.weight-a.weight).slice(0,15);const text=rows.length?rows.map((c,i)=>`${i+1}. ${c.locked?'🔒 ':''}**[${c.rarity}] ${c.rarity==='??'?'???':mtx(lang,c.nameEn,c.nameVi)}** • ${c.weight.toFixed(2)} kg • ${c.value.toLocaleString()} 🌟`).join('\n'):mtx(lang,'Your Fishing Bag is empty.','Túi cá đang trống.');return{embeds:[new EmbedBuilder().setColor(0x5865F2).setTitle(mtx(lang,'🎒 Fishing Bag','🎒 Túi Cá')).setDescription(text).setFooter({text:mtx(lang,`Showing up to 15 • Stored ${p.bag.length}/${cfg.maxBag}`,`Hiển thị tối đa 15 • Đang giữ ${p.bag.length}/${cfg.maxBag}`)})],components:nav(uid,lang)};}
async function sellCenter(uid,lang){const cfg=await FishingSettings.get(),p=await profile(uid);const unlocked=[...p.bag].filter(c=>!c.locked).sort((a,b)=>rarityIndex(b.rarity)-rarityIndex(a.rarity)||b.value-a.value);const locked=p.bag.length-unlocked.length;const total=unlocked.reduce((n,c)=>n+Number(c.value||0),0);const e=new EmbedBuilder().setColor(0x2ECC71).setTitle(mtx(lang,'💰 Fish Market','💰 Khu Bán Cá')).setDescription(unlocked.length?mtx(lang,'Choose one fish below to sell, or sell every unlocked fish at once. Locked fish are always protected.','Chọn một con cá bên dưới để bán, hoặc bán toàn bộ cá chưa khóa cùng lúc. Cá đã khóa luôn được bảo vệ.'):mtx(lang,'You have no unlocked fish to sell.','Bạn không có cá chưa khóa để bán.')).addFields({name:mtx(lang,'🐟 Sellable fish','🐟 Cá có thể bán'),value:unlocked.length.toLocaleString(),inline:true},{name:mtx(lang,'🔒 Locked','🔒 Đã khóa'),value:locked.toLocaleString(),inline:true},{name:mtx(lang,'🌟 Total sell value','🌟 Tổng giá bán'),value:`${total.toLocaleString()} CXu`,inline:true});const rows=[];if(unlocked.length){rows.push(new ActionRowBuilder().addComponents(new StringSelectMenuBuilder().setCustomId(`fish:sellpick:${uid}`).setPlaceholder(mtx(lang,'Choose a fish to sell','Chọn cá muốn bán')).addOptions(unlocked.slice(0,25).map(c=>({label:`[${c.rarity}] ${(c.rarity==='??'?'???':mtx(lang,c.nameEn,c.nameVi)).slice(0,70)}`,description:`${c.weight.toFixed(2)} kg • ${c.value.toLocaleString()} CXu`,value:c.catchId})))));if(cfg.sellAllEnabled)rows.push(new ActionRowBuilder().addComponents(new ButtonBuilder().setCustomId(`fish:sellall:${uid}`).setLabel(mtx(lang,`Sell All Unlocked (${unlocked.length})`,`Bán Tất Cả Chưa Khóa (${unlocked.length})`)).setEmoji('💰').setStyle(ButtonStyle.Danger)));}rows.push(...nav(uid,lang));return{embeds:[e],components:rows.slice(0,5)};}
async function sellAll(uid,lang){const cfg=await FishingSettings.get();if(!cfg.sellAllEnabled)return{error:mtx(lang,'❌ Sell All is disabled by the Developer.','❌ Bán tất cả hiện đã bị Developer tắt.')};const p=await profile(uid);const sellable=p.bag.filter(c=>!c.locked);if(!sellable.length)return{error:mtx(lang,'❌ You have no unlocked fish to sell.','❌ Bạn không có cá chưa khóa để bán.')};const total=sellable.reduce((n,c)=>n+Number(c.value||0),0);const count=sellable.length;p.bag=p.bag.filter(c=>c.locked);p.totalSold+=count;p.totalEarned+=total;await p.save();await ensureWallet(uid);const w=await UserEconomy.findOneAndUpdate(walletFilter(uid),{$inc:{cstar:total}},{returnDocument:'after'});return{content:mtx(lang,`💰 Sold **${count} unlocked fish** for **${total.toLocaleString()} <:cxu_coin:1551759873241251912> CXu**. Balance: **${w.cstar.toLocaleString()}**.`,`💰 Đã bán **${count} cá chưa khóa** nhận **${total.toLocaleString()} <:cxu_coin:1551759873241251912> CXu**. Số dư: **${w.cstar.toLocaleString()}**.`),components:nav(uid,lang)};}
async function dex(uid,lang){const p=await profile(uid);const by={};for(const r of RARITIES)by[r.id]=FISH.filter(f=>f.rarity===r.id).map(f=>p.fishdex.includes(f.id)?(r.id==='??'?mtx(lang,'✨ Discovered Infiniti Rare','✨ Đã khám phá Hiếm Vô Cực'):mtx(lang,f.en,f.vi)):'???');const desc=RARITIES.map(r=>`**${r.id} • ${mtx(lang,r.en,r.vi)}** — ${by[r.id].join(', ')}`).join('\n');return{embeds:[new EmbedBuilder().setColor(0x9B59FF).setTitle(`📖 Fishdex • ${p.fishdex.length}/${FISH.length}`).setDescription(desc.slice(0,4000))],components:nav(uid,lang)};}
async function shop(uid,lang){const cfg=await FishingSettings.get(),p=await profile(uid),w=await ensureWallet(uid),cur=cfg.rods[p.rodLevel],next=cfg.rods[p.rodLevel+1];let rodText=mtx(lang,`Current: **${cur.nameEn}**`,`Hiện tại: **${cur.nameVi}**`);if(next)rodText+=mtx(lang,`\nNext: **${next.nameEn}**\n🐟 ${p.totalCaught.toLocaleString()}/${next.fish.toLocaleString()} • ⚖️ ${p.totalWeight.toFixed(0)}/${next.kg.toLocaleString()} kg • 🌟 ${w.cstar.toLocaleString()}/${next.cost.toLocaleString()}`,`\nTiếp theo: **${next.nameVi}**\n🐟 ${p.totalCaught.toLocaleString()}/${next.fish.toLocaleString()} • ⚖️ ${p.totalWeight.toFixed(0)}/${next.kg.toLocaleString()} kg • 🌟 ${w.cstar.toLocaleString()}/${next.cost.toLocaleString()}`);else rodText+=mtx(lang,'\n👑 Maximum rod reached.','\n👑 Đã đạt cấp cần tối đa.');const baitText=Object.entries(cfg.baits).map(([k,b])=>`${p.selectedBait===k?'▶️ ':''}${mtx(lang,b.en,b.vi)} • ${b.qty}x = ${b.cost.toLocaleString()} 🌟 • 🎒 ${Number(p.bait.get?.(k)||0)}`).join('\n');const rows=[];if(next)rows.push(new ActionRowBuilder().addComponents(new ButtonBuilder().setCustomId(`fish:upgrade:${uid}`).setLabel(mtx(lang,'Upgrade Rod','Nâng Cần')).setEmoji('🎣').setStyle(ButtonStyle.Success)));rows.push(new ActionRowBuilder().addComponents(new StringSelectMenuBuilder().setCustomId(`fish:buybait:${uid}`).setPlaceholder(mtx(lang,'Buy bait','Mua mồi')).addOptions(Object.entries(cfg.baits).map(([k,b])=>({label:mtx(lang,b.en,b.vi),description:`${b.qty}x • ${b.cost.toLocaleString()} CXu`,value:k})))));rows.push(...nav(uid,lang));return{embeds:[new EmbedBuilder().setColor(0xF1C40F).setTitle(mtx(lang,'🛒 Fishing Shop','🛒 Cửa Hàng Câu Cá')).addFields({name:mtx(lang,'🎣 Rod Upgrade','🎣 Nâng cấp cần'),value:rodText},{name:mtx(lang,'🪱 Bait','🪱 Mồi câu'),value:baitText},{name:'🌟 CXu',value:w.cstar.toLocaleString()})],components:rows.slice(0,5)};}
async function upgrade(uid,lang){const cfg=await FishingSettings.get(),p=await profile(uid),next=cfg.rods[p.rodLevel+1];if(!next)return{error:mtx(lang,'👑 Your rod is already maxed.','👑 Cần câu đã đạt cấp tối đa.')};if(p.totalCaught<next.fish||p.totalWeight<next.kg)return{error:mtx(lang,`🔒 Need ${next.fish.toLocaleString()} lifetime fish and ${next.kg.toLocaleString()} kg lifetime weight.`,`🔒 Cần tích lũy ${next.fish.toLocaleString()} cá đã câu và ${next.kg.toLocaleString()} kg tổng cân nặng.`)};await ensureWallet(uid);const wallet=await UserEconomy.findOneAndUpdate({...walletFilter(uid),cstar:{$gte:next.cost}},{$inc:{cstar:-next.cost}},{returnDocument:'after'});if(!wallet)return{error:mtx(lang,`❌ Need ${next.cost.toLocaleString()} <:cxu_coin:1551759873241251912> CXu.`,`❌ Cần ${next.cost.toLocaleString()} <:cxu_coin:1551759873241251912> CXu.`)};p.rodLevel++;await p.save();return shop(uid,lang);}
async function buyBait(uid,key,lang){const cfg=await FishingSettings.get(),b=cfg.baits[key];if(!b)return{error:mtx(lang,'❌ Invalid bait.','❌ Mồi câu không hợp lệ.')};await ensureWallet(uid);const wallet=await UserEconomy.findOneAndUpdate({...walletFilter(uid),cstar:{$gte:b.cost}},{$inc:{cstar:-b.cost}},{returnDocument:'after'});if(!wallet)return{error:mtx(lang,'❌ Not enough <:cxu_coin:1551759873241251912> CXu.','❌ Không đủ <:cxu_coin:1551759873241251912> CXu.')};const p=await profile(uid);p.bait.set(key,Number(p.bait.get(key)||0)+b.qty);p.selectedBait=key;await p.save();return shop(uid,lang);}
async function sell(uid,cid,lang){const p=await profile(uid),idx=p.bag.findIndex(x=>x.catchId===cid);if(idx<0)return{error:mtx(lang,'This fish is no longer in your bag.','Cá này không còn trong túi.')};const c=p.bag[idx];if(c.locked)return{error:mtx(lang,'🔒 Unlock this fish before selling it.','🔒 Hãy mở khóa cá trước khi bán.')};p.bag.splice(idx,1);p.totalSold++;p.totalEarned+=c.value;await p.save();await ensureWallet(uid);const w=await UserEconomy.findOneAndUpdate(walletFilter(uid),{$inc:{cstar:c.value}},{returnDocument:'after'});return{content:mtx(lang,`💰 Sold **[${c.rarity}] ${c.rarity==='??'?'???':c.nameEn}** for **${c.value.toLocaleString()} <:cxu_coin:1551759873241251912> CXu**. Balance: **${w.cstar.toLocaleString()}**.`,`💰 Đã bán **[${c.rarity}] ${c.rarity==='??'?'???':c.nameVi}** nhận **${c.value.toLocaleString()} <:cxu_coin:1551759873241251912> CXu**. Số dư: **${w.cstar.toLocaleString()}**.`),components:nav(uid,lang)};}
async function lock(uid,cid,lang){const p=await profile(uid),c=p.bag.find(x=>x.catchId===cid);if(!c)return{error:mtx(lang,'Fish not found.','Không tìm thấy cá.')};c.locked=!c.locked;await p.save();return{content:mtx(lang,`${c.locked?'🔒 Locked':'🔓 Unlocked'} **[${c.rarity}] ${c.rarity==='??'?'???':c.nameEn}**.`,`${c.locked?'🔒 Đã khóa':'🔓 Đã mở khóa'} **[${c.rarity}] ${c.rarity==='??'?'???':c.nameVi}**.`),components:nav(uid,lang)};}
function score(p,cfg=null){const sw=cfg?.scoreWeights||{catch:2,weight:.4,dex:250,bestWeight:2};const rare=[...RARITIES].reduce((s,r)=>s+Number(p.rarityCaught?.get?.(r.id)||p.rarityCaught?.[r.id]||0)*Number(cfg?.rarityScores?.[r.id]??r.score),0);return Math.round((p.totalCaught||0)*sw.catch+(p.totalWeight||0)*sw.weight+(p.fishdex?.length||0)*sw.dex+(p.bestWeight||0)*sw.bestWeight+rare);}
async function ranking(uid,lang){const cfg=await FishingSettings.get();if(!cfg.rankingEnabled)return{error:mtx(lang,'🏆 Global Fishing Ranking is disabled by the Developer.','🏆 Xếp hạng Câu cá Toàn cầu hiện đã bị Developer tắt.')};const ps=await FishingProfile.find({totalCaught:{$gt:0}}).lean();const top=ps.map(p=>({...p,fishingScore:score(p,cfg)})).sort((a,b)=>b.fishingScore-a.fishingScore||b.totalWeight-a.totalWeight).slice(0,10);const lines=top.map((p,i)=>`${['🥇','🥈','🥉'][i]||`**#${i+1}**`} <@${p.userId}> — **${p.fishingScore.toLocaleString()} ${mtx(lang,'pts','điểm')}**\n🐟 ${p.totalCaught.toLocaleString()} • ⚖️ ${p.totalWeight.toFixed(1)} kg • 💎 ${p.bestRarity} • 📖 ${p.fishdex.length}/${FISH.length}`);const me=ps.find(x=>x.userId===String(uid));return{embeds:[new EmbedBuilder().setColor(0xFFD700).setTitle(mtx(lang,'🏆 Global Fishing Ranking','🏆 Xếp Hạng Câu Cá Toàn Cầu')).setDescription(lines.join('\n\n')||mtx(lang,'No catches yet.','Chưa có dữ liệu câu cá.')).setFooter({text:me?mtx(lang,`Your Fishing Score: ${score(me,cfg).toLocaleString()} pts`,`Điểm Câu Cá của bạn: ${score(me,cfg).toLocaleString()} điểm`):'Corgi Fishing'})],components:nav(uid,lang)};}
async function handle(i,lang){const [,action,owner,arg]=i.customId.split(':');if(String(i.user.id)!==String(owner))return i.reply({content:mtx(lang,'❌ This Fishing panel belongs to another player.','❌ Bảng Câu Cá này thuộc về người chơi khác.'),flags:64});let r;if(action==='cast')r=await cast(owner,lang);else if(action==='hook')r=await fishingFight(owner,'hook',lang);else if(action==='fight')r=await fishingFight(owner,arg,lang);else if(action==='bag')r=await bag(owner,lang);else if(action==='dex')r=await dex(owner,lang);else if(action==='shop')r=await shop(owner,lang);else if(action==='rank')r=await ranking(owner,lang);else if(action==='sellcenter')r=await sellCenter(owner,lang);else if(action==='sellpick')r=await sell(owner,i.values[0],lang);else if(action==='sellall')r=await sellAll(owner,lang);else if(action==='upgrade')r=await upgrade(owner,lang);else if(action==='sell')r=await sell(owner,arg,lang);else if(action==='lock')r=await lock(owner,arg,lang);else if(action==='keep')r={content:mtx(lang,'🎒 Fish kept in your bag.','🎒 Đã giữ cá trong túi.'),components:nav(owner,lang)};else if(action==='buybait')r=await buyBait(owner,i.values[0],lang);if(!r)return;if(r.error)return i.reply({content:r.error,flags:64});return i.update(r);}
module.exports={home,cast,bag,dex,shop,ranking,handle,score};
