const {compactNumber}=require('../services/numberFormat');
const {EmbedBuilder,ActionRowBuilder,ButtonBuilder,ButtonStyle}=require('discord.js');
const {AMBER}=require('../../ui/theme');
const Giveaway=require('../../models/Giveaway');
const {isGuildOperational}=require('../../services/accessControl');
const {getGuildSettings}=require('../../services/guildSettings');
const {getWallet}=require('../../services/economyWallet');
const {mtx}=require('../../services/i18n');

function shufflePick(arr,n){const a=[...new Set(arr)];for(let x=a.length-1;x>0;x--){const j=Math.floor(Math.random()*(x+1));[a[x],a[j]]=[a[j],a[x]];}return a.slice(0,n);}
function conditionLines(g,lang){const a=[];if(g.requiredRoleId)a.push(`• ${mtx(lang,'Required role','Role bắt buộc')}: <@&${g.requiredRoleId}>`);if(g.minAccountAgeDays>0)a.push(`• ${mtx(lang,'Discord account age','Tuổi tài khoản Discord')} ≥ **${g.minAccountAgeDays} ${mtx(lang,'days','ngày')}**`);if(g.minServerAgeDays>0)a.push(`• ${mtx(lang,'Server membership','Thời gian trong server')} ≥ **${g.minServerAgeDays} ${mtx(lang,'days','ngày')}**`);if(g.minCstar>0)a.push(`• <:cxu_coin:1551759873241251912> CXu ≥ **${compactNumber(g.minCstar)}**`);return a.length?a:[`• ${mtx(lang,'Everyone can join','Mọi người đều có thể tham gia')}`];}
function buildGiveawayMessage(g,lang='en'){
 const active=g.status==='active',paused=g.status==='paused',ended=g.status==='ended';
 const state=active?mtx(lang,'🟢 ACTIVE','🟢 ĐANG DIỄN RA'):paused?mtx(lang,'⏸️ PAUSED','⏸️ TẠM DỪNG'):ended?mtx(lang,'🏁 ENDED','🏁 ĐÃ KẾT THÚC'):mtx(lang,'❌ CANCELLED','❌ ĐÃ HỦY');
 const end=active?`<t:${Math.floor(new Date(g.endsAt).getTime()/1000)}:R> • <t:${Math.floor(new Date(g.endsAt).getTime()/1000)}:F>`:state;
 const e=new EmbedBuilder().setColor(AMBER).setTitle('🎉 CORGI GIVEAWAY').setDescription(g.description||mtx(lang,'Join for a chance to win!','Tham gia để có cơ hội nhận thưởng!')).addFields(
 {name:`🎁 ${mtx(lang,'Prize','Phần thưởng')}`,value:`**${g.prize}**`,inline:false},{name:`👑 ${mtx(lang,'Winners','Số người thắng')}`,value:`**${g.winnerCount}**`,inline:true},{name:`👥 ${mtx(lang,'Entries','Đã tham gia')}`,value:`**${g.participants.length.toLocaleString()}**`,inline:true},{name:`⏰ ${mtx(lang,'Ends','Kết thúc')}`,value:end,inline:false},{name:`📋 ${mtx(lang,'Requirements','Điều kiện')}`,value:conditionLines(g,lang).join('\n'),inline:false});
 if(g.imageUrl)e.setImage(g.imageUrl);if(g.winners?.length)e.addFields({name:`🏆 ${mtx(lang,'Winners','Người thắng')}`,value:g.winners.map(x=>`<@${x}>`).join(', ')});
 e.setFooter({text:`Corgi Studio • Giveaway • ${g.messageId||mtx(lang,'Creating…','Đang tạo…')}`}).setTimestamp();
 const row=new ActionRowBuilder().addComponents(new ButtonBuilder().setCustomId('giveaway:join').setLabel(mtx(lang,'Join Giveaway','Tham gia Giveaway')).setEmoji(g.joinEmoji||'🔥').setStyle(ButtonStyle.Success).setDisabled(!active),new ButtonBuilder().setCustomId('giveaway:leave').setLabel(mtx(lang,'Leave','Rời Giveaway')).setStyle(ButtonStyle.Secondary).setDisabled(!active));
 return {embeds:[e],components:[row]};
}
async function eligibility(g,member){const lang=(await getGuildSettings(g.guildId)).language;if(!member)return {ok:false,reason:mtx(lang,'You are no longer in this server.','Bạn không còn ở trong server.')};if(g.requiredRoleId&&!member.roles.cache.has(g.requiredRoleId))return {ok:false,reason:mtx(lang,`Required role: <@&${g.requiredRoleId}>.`,`Bạn cần role <@&${g.requiredRoleId}>.`)};const now=Date.now();if(g.minAccountAgeDays>0&&now-member.user.createdTimestamp<g.minAccountAgeDays*86400000)return {ok:false,reason:mtx(lang,`Your Discord account must be at least ${g.minAccountAgeDays} days old.`,`Tài khoản Discord phải đủ ít nhất ${g.minAccountAgeDays} ngày.`)};if(g.minServerAgeDays>0&&(!member.joinedTimestamp||now-member.joinedTimestamp<g.minServerAgeDays*86400000))return {ok:false,reason:mtx(lang,`You must be in this server for at least ${g.minServerAgeDays} days.`,`Bạn phải ở server ít nhất ${g.minServerAgeDays} ngày.`)};if(g.minCstar>0){const w=await getWallet(member.id);if((w?.balance||0)<g.minCstar)return {ok:false,reason:mtx(lang,`You need at least ${compactNumber(g.minCstar)} <:cxu_coin:1551759873241251912> CXu.`,`Bạn cần tối thiểu ${compactNumber(g.minCstar)} <:cxu_coin:1551759873241251912> CXu.`)}}return {ok:true};}
async function validParticipants(g,guild){const valid=[];for(const uid of [...new Set(g.participants)]){const m=await guild.members.fetch(uid).catch(()=>null);if(m&&!m.user.bot&&(await eligibility(g,m)).ok)valid.push(uid);}return valid;}
async function finishGiveaway(g,client,{reroll=false}={}){const guild=client.guilds.cache.get(g.guildId);if(!guild)return null;const ch=await guild.channels.fetch(g.channelId).catch(()=>null);if(!ch?.isTextBased())return null;const valid=await validParticipants(g,guild);const pool=reroll?valid.filter(x=>!g.winners.includes(x)):valid;const winners=shufflePick(pool,g.winnerCount);if(!reroll){g.status='ended';g.endedAt=new Date();g.winners=winners;}else g.winners=winners;await g.save();const s=await getGuildSettings(g.guildId);const msg=await ch.messages.fetch(g.messageId).catch(()=>null);if(msg)await msg.edit(buildGiveawayMessage(g,s.language)).catch(()=>{});await ch.send(winners.length?`🎉 ${mtx(s.language,'Congratulations','Chúc mừng')} ${winners.map(x=>`<@${x}>`).join(', ')}! **${g.prize}**`:`🎉 ${mtx(s.language,'Giveaway ended with no valid entries.','Giveaway kết thúc nhưng không có lượt tham gia hợp lệ.')}`).catch(()=>{});return winners;}
function startGiveawayService(client){setInterval(async()=>{const due=await Giveaway.find({status:'active',endsAt:{$lte:new Date()}});for(const g of due){try{if(await isGuildOperational(g.guildId))await finishGiveaway(g,client);}catch(e){console.error('giveaway end',e);}}},5000).unref();}
module.exports={startGiveawayService,buildGiveawayMessage,eligibility,finishGiveaway};
